// packages/vue/registry/components/ai/context/ContextInputUsage.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { getUsage } from "tokenlens"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { formatUsd, useContextValue } from "./context"
import TokensWithCost from "./TokensWithCost.vue"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const { usage, modelId } = useContextValue()

const tokens = computed(() => usage.value?.inputTokens ?? 0)

const costText = computed(() => {
  if (!tokens.value)
    return undefined
  const cost = modelId.value
    ? getUsage({
        modelId: modelId.value,
        usage: { input: tokens.value, output: 0 },
      }).costUSD?.totalUSD
    : undefined
  return formatUsd(cost ?? 0)
})
</script>

<template>
  <slot v-if="$slots.default" />
  <div
    v-else-if="tokens > 0"
    :class="cn('flex items-center justify-between text-xs', props.class)"
  >
    <span class="text-muted-foreground">Input</span>
    <TokensWithCost :cost-text="costText" :tokens="tokens" />
  </div>
</template>

// packages/svelte/src/lib/registry/ai/context/context-input-usage.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { getUsage } from "tokenlens";
	import TokensWithCost from "./tokens-with-cost.svelte";
	import { formatUsd, useContextValue } from "./use-context.svelte.js";

	let {
		class: className,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & { children?: Snippet } = $props();

	const context = useContextValue();
	const tokens = $derived(context.usage?.inputTokens ?? 0);
	const costText = $derived.by(() => {
		if (!tokens) return undefined;
		const cost = context.modelId
			? getUsage({
					modelId: context.modelId,
					usage: { input: tokens, output: 0 },
				}).costUSD?.totalUSD
			: undefined;
		return formatUsd(cost ?? 0);
	});
</script>

{#if children}
	{@render children()}
{:else if tokens > 0}
	<div class={cn("flex items-center justify-between text-xs", className)} {...restProps}>
		<span class="text-muted-foreground">Input</span>
		<TokensWithCost {costText} {tokens} />
	</div>
{/if}
