// packages/vue/registry/components/ai/context/ContextTrigger.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Button } from "@/registry/edmi/ui/button"
import { HoverCardTrigger } from "@/registry/edmi/ui/hover-card"
import { formatPercent, useContextValue } from "./context"
import ContextIcon from "./ContextIcon.vue"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const { usedTokens, maxTokens } = useContextValue()

const usedPercent = computed(() => (maxTokens.value === 0 ? 0 : usedTokens.value / maxTokens.value))
const renderedPercent = computed(() => formatPercent(usedPercent.value))
</script>

<template>
  <HoverCardTrigger as-child>
    <slot v-if="$slots.default" />
    <Button v-else type="button" variant="ghost" :class="props.class">
      <ContextIcon />
      <span
        :class="cn(
          'font-mono text-xs font-medium',
          usedPercent >= 0.9 ? 'text-warning-text' : 'text-foreground',
        )"
      >
        {{ renderedPercent }}
      </span>
    </Button>
  </HoverCardTrigger>
</template>

// packages/svelte/src/lib/registry/ai/context/context-trigger.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { Button, type ButtonProps } from "$lib/registry/ui/button/index.js";
	import { HoverCardTrigger } from "$lib/registry/ui/hover-card/index.js";
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import ContextIcon from "./context-icon.svelte";
	import { formatPercent, useContextValue } from "./use-context.svelte.js";

	let {
		class: className,
		child: customChild,
		children,
		...restProps
	}: Omit<ButtonProps, "href" | "child"> & {
		/** Bring your own trigger element (bits-ui `child` snippet). */
		child?: Snippet<[{ props: Record<string, unknown> }]>;
	} = $props();

	const context = useContextValue();
	const usedPercent = $derived(
		context.maxTokens === 0 ? 0 : context.usedTokens / context.maxTokens
	);
</script>

<HoverCardTrigger>
	{#snippet child({ props })}
		{#if customChild}
			{@render customChild({ props })}
		{:else}
			<Button type="button" variant="ghost" class={className} {...props} {...restProps}>
				{#if children}
					{@render children()}
				{:else}
					<ContextIcon />
					<span
						class={cn(
							"font-mono text-xs font-medium",
							usedPercent >= 0.9 ? "text-warning-text" : "text-foreground"
						)}
					>
						{formatPercent(usedPercent)}
					</span>
				{/if}
			</Button>
		{/if}
	{/snippet}
</HoverCardTrigger>
