// apps/docs/src/demos/svelte/ai-jsx-preview.svelte
<script lang="ts">
	import { JSXPreview, JSXPreviewContent, JSXPreviewError } from "@edmi-svelte/ai/jsx-preview";
	import { Button } from "@edmi-svelte/ui/button";
	import { Card } from "@edmi-svelte/ui/card";
	import { Skeleton } from "@edmi-svelte/ui/skeleton";

	// Only components in this map can be rendered; markup is parsed, never evaluated.
	const components = { Card, Button, Skeleton };

	const rendered = `<Card size="sm" class="gap-0 px-4">
  <div class="font-semibold">Join MAG4</div>
  <div class="mt-0.5 text-xs text-muted-foreground">Magnificent Four · 4 tokens</div>
  <div class="mt-3.5 flex gap-2">
    <Button elevation="raised">Join index</Button>
    <Button variant="outline">Details</Button>
  </div>
</Card>`;

	// The model is still writing: <Card> is unclosed.
	const streaming = `<Card size="sm" class="gap-0 px-4">
  <div class="font-semibold">Join MAG4</div>
  <Skeleton class="mt-2 h-3 w-48" />
  <Skeleton class="mt-3.5 h-[34px] w-32" />`;

	const broken = `<Card>
  <div class="font-semibold">Join MAG4</div>
  <Chartt />
</Card>`;
</script>

<div class="flex w-full max-w-3xl flex-col gap-5">
	<div class="grid gap-5 sm:grid-cols-2">
		<div class="flex flex-col gap-2">
			<span class="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase"
				>Rendered</span
			>
			<JSXPreview {components} jsx={rendered}>
				<JSXPreviewContent />
				<JSXPreviewError />
			</JSXPreview>
		</div>
		<div class="flex flex-col gap-2">
			<span class="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase"
				>Streaming</span
			>
			<JSXPreview {components} isStreaming jsx={streaming}>
				<JSXPreviewContent />
				<JSXPreviewError />
			</JSXPreview>
		</div>
	</div>
	<div class="flex max-w-sm flex-col gap-2">
		<span class="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase">Error</span>
		<JSXPreview {components} jsx={broken}>
			<JSXPreviewContent />
			<JSXPreviewError />
		</JSXPreview>
	</div>
</div>

// apps/docs/src/demos/react/ai-jsx-preview.tsx
import {
	JSXPreview,
	JSXPreviewContent,
	JSXPreviewError,
} from "@edmi-react/components/ai/jsx-preview";
import { Button } from "@edmi-react/ui/button";
import { Card } from "@edmi-react/ui/card";
import { Skeleton } from "@edmi-react/ui/skeleton";

const components = {
	Card: (props: React.ComponentProps<typeof Card>) => (
		<Card className="gap-0 px-4" size="sm" {...props} />
	),
	Button,
	Skeleton,
};

const rendered = `<Card>
  <div className="font-semibold">Join MAG4</div>
  <div className="mt-0.5 text-xs text-muted-foreground">Magnificent Four · 4 tokens</div>
  <div className="mt-3.5 flex gap-2">
    <Button elevation="raised">Join index</Button>
    <Button variant="outline">Details</Button>
  </div>
</Card>`;

// The model is still writing: <Card> and the last <div> are unclosed.
const streaming = `<Card>
  <div className="font-semibold">Join MAG4</div>
  <Skeleton className="mt-2 h-3 w-48" />
  <Skeleton className="mt-3.5 h-[34px] w-32" />`;

const broken = `<Card>
  <div className="font-semibold">Join MAG4</div>
  <Chartt data={`;

export default function Demo() {
	return (
		<div className="flex w-full max-w-3xl flex-col gap-5">
			<div className="grid gap-5 sm:grid-cols-2">
				<div className="flex flex-col gap-2">
					<span className="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase">
						Rendered
					</span>
					<JSXPreview components={components} jsx={rendered}>
						<JSXPreviewContent />
						<JSXPreviewError />
					</JSXPreview>
				</div>
				<div className="flex flex-col gap-2">
					<span className="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase">
						Streaming
					</span>
					<JSXPreview components={components} isStreaming jsx={streaming}>
						<JSXPreviewContent />
						<JSXPreviewError />
					</JSXPreview>
				</div>
			</div>
			<div className="flex max-w-sm flex-col gap-2">
				<span className="font-mono text-[10.5px] tracking-wide text-muted-foreground uppercase">
					Error
				</span>
				<JSXPreview components={components} jsx={broken}>
					<JSXPreviewContent />
					<JSXPreviewError />
				</JSXPreview>
			</div>
		</div>
	);
}
