// apps/docs/src/demos/vue/field.vue
<script setup lang="ts">
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSet,
  FieldTitle,
} from "@edmi-vue/ui/field";
import { Input } from "@edmi-vue/ui/input";
import { Switch } from "@edmi-vue/ui/switch";
</script>

<template>
  <FieldSet class="w-full max-w-sm">
    <FieldLegend>Mandate</FieldLegend>
    <FieldDescription>Rules the keeper follows after launch.</FieldDescription>
    <FieldGroup>
      <Field>
        <FieldLabel for="field-name">Index name</FieldLabel>
        <Input id="field-name" default-value="Magnificent Four" />
      </Field>
      <Field data-invalid="true">
        <FieldLabel for="field-ticker">Ticker</FieldLabel>
        <Input id="field-ticker" aria-invalid="true" default-value="mag 4" />
        <FieldError>Use 2-6 capital letters.</FieldError>
      </Field>
      <Field orientation="horizontal">
        <FieldContent>
          <FieldTitle>Allow keeper</FieldTitle>
          <FieldDescription>
            Rebalance automatically when drift passes the limit.
          </FieldDescription>
        </FieldContent>
        <Switch default-value="true" />
      </Field>
    </FieldGroup>
  </FieldSet>
</template>

// apps/docs/src/demos/react/field.tsx
import {
	Field,
	FieldContent,
	FieldDescription,
	FieldError,
	FieldGroup,
	FieldLabel,
	FieldLegend,
	FieldSet,
	FieldTitle,
} from "@edmi-react/ui/field";
import { Input } from "@edmi-react/ui/input";
import { Switch } from "@edmi-react/ui/switch";

export default function Demo() {
	return (
		<FieldSet className="w-full max-w-sm">
			<FieldLegend>Mandate</FieldLegend>
			<FieldDescription>
				Rules the keeper follows after launch.
			</FieldDescription>
			<FieldGroup>
				<Field>
					<FieldLabel htmlFor="field-name">Index name</FieldLabel>
					<Input id="field-name" defaultValue="Magnificent Four" />
				</Field>
				<Field data-invalid="true">
					<FieldLabel htmlFor="field-ticker">Ticker</FieldLabel>
					<Input id="field-ticker" aria-invalid defaultValue="MAG" />
					<FieldError>Use 2-6 capital letters.</FieldError>
				</Field>
				<Field orientation="horizontal">
					<FieldContent>
						<FieldTitle>Allow keeper</FieldTitle>
						<FieldDescription>
							Rebalance automatically when drift passes the limit.
						</FieldDescription>
					</FieldContent>
					<Switch defaultChecked />
				</Field>
			</FieldGroup>
		</FieldSet>
	);
}
