// apps/docs/src/demos/svelte/pricing-plan-raised.svelte
<script lang="ts">
	import { Button } from "@edmi-svelte/ui/button";
	import { PricingPlan } from "@edmi-svelte/ui/pricing-plan";
</script>

<PricingPlan
	raised
	class="w-[300px] max-w-full"
	name="Creator"
	tagline="Launch your own index"
	price="1% fee to you"
	priceNote="Earned on every holder’s share."
	features={["Custom weights and mandate", "Pre-IPO sleeve", "Share cards and Blinks"]}
>
	{#snippet action()}
		<Button size="lg" elevation="raised">Launch an index</Button>
	{/snippet}
</PricingPlan>

// apps/docs/src/demos/react/pricing-plan-raised.tsx
import { PricingPlan } from "@edmi-react/blocks/pricing-plan/pricing-plan";
import { Button } from "@edmi-react/ui/button";

export default function Demo() {
	return (
		<PricingPlan
			elevation="raised"
			className="w-[300px] max-w-full"
			name="Creator"
			tagline="Launch your own index"
			price="1% fee to you"
			priceNote="Earned on every holder’s share."
			action={<Button size="lg">Launch an index</Button>}
			features={[
				"Custom weights and mandate",
				"Pre-IPO sleeve",
				"Share cards and Blinks",
			]}
		/>
	);
}
