// apps/docs/src/demos/svelte/resizable.svelte
<script lang="ts">
	import * as Resizable from "@edmi-svelte/ui/resizable";

	const pane = "flex h-full items-center justify-center text-sm text-muted-foreground";
</script>

<div class="flex w-full shrink-0 flex-col gap-6">
	<div class="h-[180px] w-full max-w-md">
	<Resizable.PaneGroup
		direction="horizontal"
		class="rounded-xl border border-border bg-card"
	>
		<Resizable.Pane defaultSize={60}>
			<div class={pane}>Chart</div>
		</Resizable.Pane>
		<Resizable.Handle withHandle />
		<Resizable.Pane defaultSize={40}>
			<div class={pane}>Order book</div>
		</Resizable.Pane>
	</Resizable.PaneGroup>
	</div>
	<div class="h-[220px] w-full max-w-md">
	<Resizable.PaneGroup
		direction="horizontal"
		class="rounded-xl border border-border bg-card"
	>
		<Resizable.Pane defaultSize={30}>
			<div class={pane}>Sidebar</div>
		</Resizable.Pane>
		<Resizable.Handle withHandle />
		<Resizable.Pane defaultSize={70}>
			<Resizable.PaneGroup direction="vertical" class="h-full">
				<Resizable.Pane defaultSize={60}>
					<div class={pane}>Editor</div>
				</Resizable.Pane>
				<Resizable.Handle withHandle />
				<Resizable.Pane defaultSize={40}>
					<div class={pane}>Agent log</div>
				</Resizable.Pane>
			</Resizable.PaneGroup>
		</Resizable.Pane>
	</Resizable.PaneGroup>
	</div>
</div>

// apps/docs/src/demos/react/resizable.tsx
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from "@edmi-react/ui/resizable";

const pane =
	"flex h-full items-center justify-center text-sm text-muted-foreground";

export default function Demo() {
	return (
		<div className="flex w-full shrink-0 flex-col gap-6">
			<ResizablePanelGroup
				orientation="horizontal"
				className="min-h-[180px] w-full max-w-md shrink-0 rounded-xl border border-border bg-card"
			>
				<ResizablePanel defaultSize="60%">
					<div className={pane}>Chart</div>
				</ResizablePanel>
				<ResizableHandle withHandle />
				<ResizablePanel defaultSize="40%">
					<div className={pane}>Order book</div>
				</ResizablePanel>
			</ResizablePanelGroup>
			<ResizablePanelGroup
				orientation="horizontal"
				className="min-h-[220px] w-full max-w-md shrink-0 rounded-xl border border-border bg-card"
			>
				<ResizablePanel defaultSize="30%">
					<div className={pane}>Sidebar</div>
				</ResizablePanel>
				<ResizableHandle withHandle />
				<ResizablePanel defaultSize="70%">
					<ResizablePanelGroup orientation="vertical" className="h-full">
						<ResizablePanel defaultSize="60%">
							<div className={pane}>Editor</div>
						</ResizablePanel>
						<ResizableHandle withHandle />
						<ResizablePanel defaultSize="40%">
							<div className={pane}>Agent log</div>
						</ResizablePanel>
					</ResizablePanelGroup>
				</ResizablePanel>
			</ResizablePanelGroup>
		</div>
	);
}
