// apps/docs/src/demos/vue/site-header-raised.vue
<script setup lang="ts">
import { SiteHeader } from "@edmi-vue/ui/site-header";
import { Button } from "@edmi-vue/ui/button";

const steps = [
	{ label: "Start", href: "#start" },
	{ label: "Build", href: "#build" },
	{ label: "Sell", href: "#sell" },
	{ label: "Scale", href: "#scale" },
];
const links = [
	{ label: "Resources", href: "#resources" },
	{ label: "Pricing", href: "#pricing" },
];
</script>

<template>
	<SiteHeader raised lead="How to" :steps="steps" :links="links">
		<template #action>
			<Button elevation="raised">Create an index</Button>
		</template>
	</SiteHeader>
</template>

// apps/docs/src/demos/react/site-header-raised.tsx
import { SiteHeader } from "@edmi-react/blocks/site-header/site-header";
import { Button } from "@edmi-react/ui/button";

export default function Demo() {
	return (
		<SiteHeader
			raised
			lead="How to"
			steps={[
				{ label: "Start", href: "#start" },
				{ label: "Build", href: "#build" },
				{ label: "Sell", href: "#sell" },
				{ label: "Scale", href: "#scale" },
			]}
			links={[
				{ label: "Resources", href: "#resources" },
				{ label: "Pricing", href: "#pricing" },
			]}
			action={<Button elevation="raised">Create an index</Button>}
		/>
	);
}
