// examples/layerbeat-vue/src/components/ui/pagination/Pagination.vue
<script setup lang="ts">
import type { PaginationRootEmits, PaginationRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { PaginationRoot, useForwardPropsEmits } from "reka-ui"
import { provide } from "vue"
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<PaginationRootProps & {
  class?: HTMLAttributes["class"]
  /** ✦ the active page link gets the one-step 3D look */
  raised?: boolean
}>(), { raised: false })

provide("pagination", {
  get raised() { return props.raised },
})
const emits = defineEmits<PaginationRootEmits>()

const delegatedProps = reactiveOmit(props, "class", "raised")
const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <PaginationRoot
    v-slot="slotProps"
    data-slot="pagination"
    v-bind="forwarded"
    :class="cn('mx-auto flex w-full justify-center', props.class)"
  >
    <slot v-bind="slotProps" />
  </PaginationRoot>
</template>

// examples/svelte/src/lib/components/ui/pagination/pagination.svelte
<script lang="ts" module>
	import { getContext, setContext } from "svelte";

	interface PaginationContext {
		raised: boolean;
	}

	export function setPaginationCtx(ctx: PaginationContext) {
		setContext("pagination", ctx);
	}

	export function getPaginationCtx() {
		return getContext<PaginationContext | undefined>("pagination");
	}
</script>

<script lang="ts">
	import { Pagination as PaginationPrimitive } from "bits-ui";
	import { cn } from "#lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		count = 0,
		perPage = 10,
		page = $bindable(1),
		siblingCount = 1,
		raised = false,
		...restProps
	}: PaginationPrimitive.RootProps & {
		/** ✦ opt-in one-step 3D look for the active link. */
		raised?: boolean;
	} = $props();

	setPaginationCtx({
		get raised() {
			return raised;
		},
	});
</script>

<PaginationPrimitive.Root
	bind:ref
	bind:page
	role="navigation"
	aria-label="pagination"
	data-slot="pagination"
	{count}
	{perPage}
	{siblingCount}
	class={cn("mx-auto flex w-full justify-center", className)}
	{...restProps}
/>
