// examples/react/src/shell/app-shell.tsx
import { useState } from "react";
import {
	getLayoutCookie,
	type Layout,
	LayoutPickerToast,
} from "@/components/layout-picker";
import { DashboardLayout } from "./dashboard-layout";
import { NavbarLayout } from "./navbar-layout";

// First visit: dashboard + a corner toast to pick a layout; the choice lives in a cookie (DESIGN §6).
export function AppShell({ children }: { children: React.ReactNode }) {
	const [layout, setLayout] = useState<Layout>(
		() => getLayoutCookie() ?? "dashboard",
	);
	const Shell = layout === "navbar" ? NavbarLayout : DashboardLayout;
	return (
		<>
			<Shell>{children}</Shell>
			<LayoutPickerToast raised onValueChange={setLayout} />
		</>
	);
}

// examples/svelte/src/lib/app/shell/app-shell.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import { LayoutPickerToast, type Layout } from "#lib/components/ui/layout-picker/index.js";
	import DashboardLayout from "./dashboard-layout.svelte";
	import NavbarLayout from "./navbar-layout.svelte";

	// SSR renders the cookie's layout (`layout` from the root load); the first-visit toast changes it live (DESIGN §6).
	let { layout: initial, children }: { layout: Layout; children: Snippet } = $props();
	let layout = $state<Layout>("dashboard");
	$effect.pre(() => {
		layout = initial;
	});
</script>

{#if layout === "navbar"}
	<NavbarLayout {children} />
{:else}
	<DashboardLayout {children} />
{/if}
<LayoutPickerToast raised onValueChange={(v) => (layout = v)} />
