// packages/vue/registry/ui/calendar/CalendarCaption.vue
<script setup lang="ts">
import type { DateValue } from "reka-ui"
import type { LayoutTypes } from "."
import { ChevronDown } from "@lucide/vue"
import { useDateFormatter } from "reka-ui"
import { createYear, createYearRange, toDate } from "reka-ui/date"
import { computed } from "vue"

// ✦ Month/year dropdown caption (React `captionLayout="dropdown"`): a styled native <select> under a label.
const props = defineProps<{
  date: DateValue
  layout?: LayoutTypes
  locale?: string
  yearRange?: DateValue[]
  minValue?: DateValue
  maxValue?: DateValue
}>()
const emit = defineEmits<{ (e: "update:placeholder", value: DateValue): void }>()

const formatter = useDateFormatter(props.locale ?? "en")

const years = computed(
  () =>
    props.yearRange ??
    createYearRange({
      start: props.minValue ?? props.date.cycle("year", -100),
      end: props.maxValue ?? props.date.cycle("year", 10),
    }),
)
const months = computed(() => createYear({ dateObj: props.date }))

const wrap =
  "relative rounded-md border border-input bg-card has-focus:border-ring has-focus:shadow-ring"
const label =
  "pointer-events-none flex h-7 items-center gap-1 rounded-md pr-1.5 pl-2 text-[13px] font-medium [&>svg]:size-3.5 [&>svg]:text-muted-foreground"
const select = "absolute inset-0 w-full cursor-pointer bg-popover opacity-0"
</script>

<template>
  <div class="flex h-7 w-full items-center justify-center gap-1.5">
    <div v-if="layout !== 'year-only'" :class="wrap">
      <div :class="label">
        {{ formatter.custom(toDate(date), { month: "short" }) }}
        <ChevronDown />
      </div>
      <select
        :class="select"
        aria-label="Month"
        :value="date.month"
        @change="(e: Event) => emit('update:placeholder', date.set({ month: Number((e.target as HTMLSelectElement).value) }))"
      >
        <option v-for="m in months" :key="m.toString()" :value="m.month">
          {{ formatter.custom(toDate(m), { month: "short" }) }}
        </option>
      </select>
    </div>
    <span v-else class="text-[13px] font-medium">
      {{ formatter.custom(toDate(date), { month: "short" }) }}
    </span>
    <div v-if="layout !== 'month-only'" :class="wrap">
      <div :class="label">
        {{ formatter.custom(toDate(date), { year: "numeric" }) }}
        <ChevronDown />
      </div>
      <select
        :class="select"
        aria-label="Year"
        :value="date.year"
        @change="(e: Event) => emit('update:placeholder', date.set({ year: Number((e.target as HTMLSelectElement).value) }))"
      >
        <option v-for="y in years" :key="y.toString()" :value="y.year">
          {{ formatter.custom(toDate(y), { year: "numeric" }) }}
        </option>
      </select>
    </div>
    <span v-else class="text-[13px] font-medium">
      {{ formatter.custom(toDate(date), { year: "numeric" }) }}
    </span>
  </div>
</template>

// packages/svelte/src/lib/registry/ui/calendar/calendar-caption.svelte
<script lang="ts">
	import { DateFormatter, getLocalTimeZone, type DateValue } from "@internationalized/date";
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";

	// ✦ Month/year dropdown caption (React `captionLayout="dropdown"`): a styled native <select> under a label.
	let {
		captionLayout = "label",
		month,
		placeholder = $bindable(),
		locale = "en-US",
		monthIndex = 0,
		minValue,
		maxValue,
	}: {
		captionLayout?: "dropdown" | "dropdown-months" | "dropdown-years" | "label";
		/** The month this caption is for (first of the displayed month). */
		month: DateValue;
		placeholder: DateValue | undefined;
		locale?: string;
		monthIndex?: number;
		minValue?: DateValue;
		maxValue?: DateValue;
	} = $props();

	const tz = getLocalTimeZone();
	const monthFmt = $derived(new DateFormatter(locale, { month: "short" }));
	const longFmt = $derived(new DateFormatter(locale, { month: "long" }));
	const yearFmt = $derived(new DateFormatter(locale, { year: "numeric" }));

	const months = $derived(
		Array.from({ length: 12 }, (_, i) => {
			const m = i + 1;
			return { value: m, label: monthFmt.format(month.set({ month: m, day: 1 }).toDate(tz)) };
		})
	);
	const years = $derived.by(() => {
		const from = minValue?.year ?? month.year - 100;
		const to = maxValue?.year ?? month.year + 10;
		return Array.from({ length: to - from + 1 }, (_, i) => {
			const y = from + i;
			return { value: y, label: yearFmt.format(month.set({ year: y, day: 1 }).toDate(tz)) };
		});
	});

	function setPlaceholder(part: { month: number } | { year: number }) {
		if (!placeholder) return;
		placeholder = placeholder.set(part).subtract({ months: monthIndex });
	}
</script>

{#snippet Caret()}
	<IconPlaceholder
		lucide="ChevronDownIcon"
		tabler="IconChevronDown"
		hugeicons="ArrowDown01Icon"
		phosphor="CaretDownIcon"
		remixicon="RiArrowDownSLine"
	/>
{/snippet}

{#snippet MonthSelect()}
	<span
		class="relative rounded-md border border-input bg-card has-focus:border-ring has-focus:shadow-ring"
	>
		<span
			class="pointer-events-none flex h-7 items-center gap-1 rounded-md pr-1.5 pl-2 text-[13px] font-medium [&>svg]:size-3.5 [&>svg]:text-muted-foreground"
			aria-hidden="true"
		>
			{monthFmt.format(month.toDate(tz))}
			{@render Caret()}
		</span>
		<select
			class="absolute inset-0 w-full cursor-pointer bg-popover opacity-0"
			aria-label="Month"
			value={month.month}
			onchange={(e) => setPlaceholder({ month: Number.parseInt(e.currentTarget.value) })}
		>
			{#each months as m (m.value)}
				<option value={m.value} selected={m.value === month.month}>{m.label}</option>
			{/each}
		</select>
	</span>
{/snippet}

{#snippet YearSelect()}
	<span
		class="relative rounded-md border border-input bg-card has-focus:border-ring has-focus:shadow-ring"
	>
		<span
			class="pointer-events-none flex h-7 items-center gap-1 rounded-md pr-1.5 pl-2 text-[13px] font-medium [&>svg]:size-3.5 [&>svg]:text-muted-foreground"
			aria-hidden="true"
		>
			{yearFmt.format(month.toDate(tz))}
			{@render Caret()}
		</span>
		<select
			class="absolute inset-0 w-full cursor-pointer bg-popover opacity-0"
			aria-label="Year"
			value={month.year}
			onchange={(e) => setPlaceholder({ year: Number.parseInt(e.currentTarget.value) })}
		>
			{#each years as y (y.value)}
				<option value={y.value} selected={y.value === month.year}>{y.label}</option>
			{/each}
		</select>
	</span>
{/snippet}

{#if captionLayout === "dropdown"}
	{@render MonthSelect()}
	{@render YearSelect()}
{:else if captionLayout === "dropdown-months"}
	{@render MonthSelect()}
	<span class="text-[13px] font-medium">{yearFmt.format(month.toDate(tz))}</span>
{:else if captionLayout === "dropdown-years"}
	<span class="text-[13px] font-medium">{monthFmt.format(month.toDate(tz))}</span>
	{@render YearSelect()}
{:else}
	<span class="text-sm font-semibold select-none">
		{longFmt.format(month.toDate(tz))}
		{yearFmt.format(month.toDate(tz))}
	</span>
{/if}
