// packages/vue/registry/ui/site-header/SiteHeaderMark.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { ChartLineIcon } from '@lucide/vue'
import { computed } from 'vue'
import { cn } from '@/registry/edmi/lib/utils'
import { type Elevation, useElevation } from '@/registry/edmi/ui/elevation'

const props = withDefaults(defineProps<{
  /** ✦ raised +1 / floating +2 give the mark the raised face */
  elevation?: Elevation
  class?: HTMLAttributes['class']
}>(), { elevation: undefined })

const level = useElevation(() => props.elevation, 'handle')
const raised = computed(() => level.value === 'raised' || level.value === 'floating')
</script>

<template>
  <!-- Dark tile with a chart glyph: the Stockbreak mark. Use the `logo` slot of the brand/header to replace it. -->
  <span
    data-slot="site-header-mark"
    :class="cn(
      'inline-flex size-7 items-center justify-center rounded-lg border border-transparent bg-primary text-primary-foreground',
      raised && '[background-image:var(--r1-p-face)] shadow-btn-raised-primary [background-origin:border-box]',
      props.class,
    )"
  >
    <ChartLineIcon class="size-[15px]" />
  </span>
</template>

// packages/svelte/src/lib/registry/ui/site-header/site-header-mark.svelte
<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";
	import { type Elevation, useElevation } from "$lib/registry/ui/elevation/index.js";

	let {
		ref = $bindable(null),
		class: className,
		elevation = "auto",
		...restProps
	}: WithElementRef<Omit<HTMLAttributes<HTMLSpanElement>, "children">> & {
		/** ✦ raised +1 / floating +2 give the mark the raised face. */
		elevation?: Elevation;
	} = $props();

	const level = useElevation(() => elevation, "handle");
	const raised = $derived(level.current === "raised" || level.current === "floating");
</script>

<!-- Dark tile with a chart glyph: the Stockbreak mark. Pass a `logo` snippet to the brand/header to replace it. -->
<span
	bind:this={ref}
	data-slot="site-header-mark"
	class={cn(
		"inline-flex size-7 items-center justify-center rounded-lg border border-primary bg-primary text-primary-foreground",
		raised && "[background-image:var(--r1-p-face)] shadow-btn-raised-primary [background-origin:border-box]",
		className
	)}
	{...restProps}
>
	<IconPlaceholder
		lucide="ChartLineIcon"
		tabler="IconChartLine"
		hugeicons="ChartLineData01Icon"
		phosphor="ChartLineUpIcon"
		remixicon="RiLineChartLine"
		class="size-[15px]"
	/>
</span>
