// examples/layerbeat-vue/src/components/ui/pagination/Pagination.vue
<script setup lang="ts">
import type { PaginationRootEmits, PaginationRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { PaginationRoot, useForwardPropsEmits } from "reka-ui"
import { computed, provide } from "vue"
import { cn } from '@/lib/utils'
import { type Elevation, useElevation } from '@/components/ui/elevation'

const props = withDefaults(defineProps<PaginationRootProps & {
  class?: HTMLAttributes["class"]
  /** ✦ depth: raised +1 / floating +2 make the active page link rise */
  elevation?: Elevation
}>(), { elevation: undefined })

const level = useElevation(() => props.elevation, "control")
const raised = computed(() => level.value === "raised" || level.value === "floating")

provide("pagination", {
  get raised() { return raised.value },
})
const emits = defineEmits<PaginationRootEmits>()

const delegatedProps = reactiveOmit(props, "class", "elevation")
const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <PaginationRoot
    v-slot="slotProps"
    data-slot="pagination"
    v-bind="forwarded"
    :class="cn('mx-auto flex w-full justify-center', props.class)"
  >
    <slot v-bind="slotProps" />
  </PaginationRoot>
</template>

// examples/layerbeat-svelte/src/lib/components/ui/pagination/pagination.svelte
<script lang="ts" module>
	import { getContext, setContext } from "svelte";

	interface PaginationContext {
		raised: boolean;
	}

	export function setPaginationCtx(ctx: PaginationContext) {
		setContext("pagination", ctx);
	}

	export function getPaginationCtx() {
		return getContext<PaginationContext | undefined>("pagination");
	}
</script>

<script lang="ts">
	import { Pagination as PaginationPrimitive } from "bits-ui";
	import { cn } from "#lib/utils.js";
	import { type Elevation, useElevation } from "#lib/components/ui/elevation/index.js";

	let {
		ref = $bindable(null),
		class: className,
		count = 0,
		perPage = 10,
		page = $bindable(1),
		siblingCount = 1,
		elevation = "auto",
		...restProps
	}: PaginationPrimitive.RootProps & {
		/** ✦ depth: raised +1 / floating +2 make the active link rise. */
		elevation?: Elevation;
	} = $props();

	const level = useElevation(() => elevation, "control");
	const raised = $derived(level.current === "raised" || level.current === "floating");

	setPaginationCtx({
		get raised() {
			return raised;
		},
	});
</script>

<PaginationPrimitive.Root
	bind:ref
	bind:page
	role="navigation"
	aria-label="pagination"
	data-slot="pagination"
	{count}
	{perPage}
	{siblingCount}
	class={cn("mx-auto flex w-full justify-center", className)}
	{...restProps}
/>
