// packages/svelte/src/lib/registry/ui/calendar/calendar.svelte
<script lang="ts">
	import { Calendar as CalendarPrimitive } from "bits-ui";
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { cn, type WithoutChildrenOrChild } from "$lib/utils.js";
	import { buttonVariants } from "$lib/registry/ui/button/index.js";
	import { type Elevation, useElevation } from "$lib/registry/ui/elevation/index.js";
	import CalendarCaption from "./calendar-caption.svelte";
	import {
		calendarCellClass,
		calendarDayClass,
		calendarHeadCellClass,
		calendarNavButtonClass,
		calendarRootClass,
		calendarShellElevation,
		calendarShellInHost,
		calendarSingleSelectedClass,
		calendarSingleSelectedRaisedClass,
	} from "./classes.js";

	let {
		ref = $bindable(null),
		value = $bindable(),
		placeholder = $bindable(),
		class: className,
		weekdayFormat = "short",
		captionLayout = "label",
		locale = "en-US",
		disableDaysOutsideMonth = false,
		elevation = "auto",
		...restProps
	}: WithoutChildrenOrChild<CalendarPrimitive.RootProps> & {
		/** ✦ `dropdown*` renders month/year selects instead of a text heading. */
		captionLayout?: "dropdown" | "dropdown-months" | "dropdown-years" | "label";
		/** ✦ depth of the calendar shell: sunken -1, flat 0, raised +1, floating +2 (selected day rises when raised). */
		elevation?: Elevation;
	} = $props();

	const shell = useElevation(() => elevation, "surface");
	const handle = useElevation(() => (elevation === "sunken" ? "flat" : elevation), "handle");
	const raised = $derived(handle.current === "raised" || handle.current === "floating");
</script>

<!--
Discriminated Unions + Destructing (required for bindable) do not
get along, so we shut typescript up by casting `value` to `never`.
-->
<CalendarPrimitive.Root
	bind:value={value as never}
	bind:ref
	bind:placeholder
	{weekdayFormat}
	{disableDaysOutsideMonth}
	{locale}
	data-slot="calendar"
	class={cn(calendarRootClass, calendarShellElevation[shell.current], calendarShellInHost, className)}
	{...restProps}
>
	{#snippet children({ months, weekdays })}
		<div class="relative flex flex-col gap-4 md:flex-row">
			<nav
				class="pointer-events-none absolute inset-x-0 top-0 flex h-7 w-full items-center justify-between gap-1"
			>
				<CalendarPrimitive.PrevButton
					data-slot="calendar-prev-button"
					class={cn(buttonVariants({ variant: "outline" }), calendarNavButtonClass)}
				>
					<IconPlaceholder
						lucide="ChevronLeftIcon"
						tabler="IconChevronLeft"
						hugeicons="ArrowLeft01Icon"
						phosphor="CaretLeftIcon"
						remixicon="RiArrowLeftSLine"
						class="size-4"
					/>
				</CalendarPrimitive.PrevButton>
				<CalendarPrimitive.NextButton
					data-slot="calendar-next-button"
					class={cn(buttonVariants({ variant: "outline" }), calendarNavButtonClass)}
				>
					<IconPlaceholder
						lucide="ChevronRightIcon"
						tabler="IconChevronRight"
						hugeicons="ArrowRight01Icon"
						phosphor="CaretRightIcon"
						remixicon="RiArrowRightSLine"
						class="size-4"
					/>
				</CalendarPrimitive.NextButton>
			</nav>
			{#each months as month, monthIndex (month)}
				<div class="flex w-full flex-col gap-3">
					<CalendarPrimitive.Header
						data-slot="calendar-header"
						class="flex h-7 w-full items-center justify-center gap-1.5 px-9"
					>
						<CalendarCaption
							{captionLayout}
							month={month.value}
							bind:placeholder
							{locale}
							{monthIndex}
							minValue={restProps.minValue}
							maxValue={restProps.maxValue}
						/>
					</CalendarPrimitive.Header>
					<CalendarPrimitive.Grid data-slot="calendar-grid" class="w-full border-collapse">
						<CalendarPrimitive.GridHead>
							<CalendarPrimitive.GridRow class="flex select-none">
								{#each weekdays as weekday, i (i)}
									<CalendarPrimitive.HeadCell class={calendarHeadCellClass}>
										{weekday.slice(0, 2)}
									</CalendarPrimitive.HeadCell>
								{/each}
							</CalendarPrimitive.GridRow>
						</CalendarPrimitive.GridHead>
						<CalendarPrimitive.GridBody>
							{#each month.weeks as weekDates (weekDates)}
								<CalendarPrimitive.GridRow class="flex w-full">
									{#each weekDates as date (date)}
										<CalendarPrimitive.Cell
											{date}
											month={month.value}
											data-slot="calendar-cell"
											class={calendarCellClass}
										>
											<CalendarPrimitive.Day
												data-slot="calendar-day"
												class={cn(
													buttonVariants({ variant: "ghost", size: "icon" }),
													calendarDayClass,
													calendarSingleSelectedClass,
													raised && calendarSingleSelectedRaisedClass
												)}
											/>
										</CalendarPrimitive.Cell>
									{/each}
								</CalendarPrimitive.GridRow>
							{/each}
						</CalendarPrimitive.GridBody>
					</CalendarPrimitive.Grid>
				</div>
			{/each}
		</div>
	{/snippet}
</CalendarPrimitive.Root>

// examples/vue/src/components/ui/calendar/Calendar.vue
<script lang="ts" setup>
import type { CalendarRootEmits, CalendarRootProps, DateValue } from "reka-ui"
import type { HTMLAttributes, Ref } from "vue"
import type { LayoutTypes } from "."
import { getLocalTimeZone, today } from "@internationalized/date"
import { PhCaretLeft, PhCaretRight } from '@phosphor-icons/vue'
import { reactiveOmit, useVModel } from "@vueuse/core"
import {
  CalendarCell,
  CalendarCellTrigger,
  CalendarGrid,
  CalendarGridBody,
  CalendarGridHead,
  CalendarGridRow,
  CalendarHeadCell,
  CalendarHeader,
  CalendarHeading,
  CalendarNext,
  CalendarPrev,
  CalendarRoot,
  useForwardPropsEmits,
} from "reka-ui"
import { computed } from "vue"
import { cn } from '@/lib/utils'
import { buttonVariants } from '@/components/ui/button'
import { type Elevation, useElevation } from '@/components/ui/elevation'
import CalendarCaption from "./CalendarCaption.vue"
import {
  calendarCellClass,
  calendarHeadCellClass,
  calendarNavButtonClass,
  calendarRootClass,
  calendarShellElevation,
  calendarShellInHost,
  calendarSingleSelectedClass,
  calendarSingleSelectedRaisedClass,
  calendarTriggerClass,
} from "./classes"

const props = withDefaults(
  defineProps<
    CalendarRootProps & {
      class?: HTMLAttributes["class"]
      /** ✦ month/year dropdowns instead of a text heading. */
      layout?: LayoutTypes
      yearRange?: DateValue[]
      /** ✦ depth of the calendar shell: sunken -1, flat 0, raised +1, floating +2 (selected day rises when raised) */
      elevation?: Elevation
    }
  >(),
  { modelValue: undefined, layout: undefined, elevation: undefined },
)
const emits = defineEmits<CalendarRootEmits>()

const delegatedProps = reactiveOmit(props, "class", "layout", "placeholder", "yearRange", "elevation")

const shell = useElevation(() => props.elevation, "surface")
const handle = useElevation(() => (props.elevation === "sunken" ? "flat" : props.elevation), "handle")
const raised = computed(() => handle.value === "raised" || handle.value === "floating")

const placeholder = useVModel(props, "placeholder", emits, {
  passive: true,
  defaultValue: props.defaultPlaceholder ?? today(getLocalTimeZone()),
}) as Ref<DateValue>

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <CalendarRoot
    v-slot="{ grid, weekDays, date }"
    v-bind="forwarded"
    :weekday-format="props.weekdayFormat ?? 'short'"
    v-model:placeholder="placeholder"
    data-slot="calendar"
    :class="cn(calendarRootClass, calendarShellElevation[shell], calendarShellInHost, props.class)"
  >
    <CalendarHeader data-slot="calendar-header" class="relative flex h-7 w-full items-center justify-center px-9">
      <CalendarCaption
        v-if="layout"
        :date="date"
        :layout="layout"
        :locale="props.locale"
        :year-range="props.yearRange"
        :min-value="props.minValue"
        :max-value="props.maxValue"
        @update:placeholder="(v) => (placeholder = v)"
      />
      <CalendarHeading v-else data-slot="calendar-heading" class="text-sm font-semibold select-none" />

      <nav class="pointer-events-none absolute inset-x-0 top-0 flex w-full items-center justify-between gap-1">
        <CalendarPrev
          data-slot="calendar-prev-button"
          :class="cn(buttonVariants({ variant: 'outline' }), calendarNavButtonClass)"
        >
          <slot name="calendar-prev-icon"><PhCaretLeft class="size-4" /></slot>
        </CalendarPrev>
        <CalendarNext
          data-slot="calendar-next-button"
          :class="cn(buttonVariants({ variant: 'outline' }), calendarNavButtonClass)"
        >
          <slot name="calendar-next-icon"><PhCaretRight class="size-4" /></slot>
        </CalendarNext>
      </nav>
    </CalendarHeader>

    <div class="mt-3 flex flex-col gap-4 sm:flex-row">
      <CalendarGrid v-for="month in grid" :key="month.value.toString()" data-slot="calendar-grid" class="w-full border-collapse">
        <CalendarGridHead>
          <CalendarGridRow class="flex">
            <CalendarHeadCell v-for="day in weekDays" :key="day" :class="calendarHeadCellClass">
              {{ day.slice(0, 2) }}
            </CalendarHeadCell>
          </CalendarGridRow>
        </CalendarGridHead>
        <CalendarGridBody>
          <CalendarGridRow v-for="(weekDates, index) in month.rows" :key="`weekDate-${index}`" class="flex w-full">
            <CalendarCell
              v-for="weekDate in weekDates"
              :key="weekDate.toString()"
              :date="weekDate"
              data-slot="calendar-cell"
              :class="calendarCellClass"
            >
              <CalendarCellTrigger
                :day="weekDate"
                :month="month.value"
                data-slot="calendar-cell-trigger"
                :class="cn(buttonVariants({ variant: 'ghost', size: 'icon' }), calendarTriggerClass, calendarSingleSelectedClass, raised && calendarSingleSelectedRaisedClass)"
              />
            </CalendarCell>
          </CalendarGridRow>
        </CalendarGridBody>
      </CalendarGrid>
    </div>
  </CalendarRoot>
</template>
