// examples/svelte/src/lib/components/ui/data-table/data-table-faceted-filter.svelte
<script lang="ts" generics="TData extends RowData, TValue">
	import type { Column, RowData } from "@tanstack/svelte-table";
	import PlusIcon from 'phosphor-svelte/lib/Plus';
	import { Badge } from "#lib/components/ui/badge/index.js";
	import { Button } from "#lib/components/ui/button/index.js";
	import type { Elevation } from "#lib/components/ui/elevation/index.js";
	import * as DropdownMenu from "#lib/components/ui/dropdown-menu/index.js";
	import type { DataTableFeatures } from "./data-table-features.js";

	/**
	 * ✦ Dashed "+ Status" filter button with a checkbox menu. The column must set
	 * `filterFn: "arrHas"`.
	 */
	let {
		column,
		title,
		options,
		elevation = "auto",
	}: {
		column?: Column<DataTableFeatures, TData, TValue>;
		title: string;
		/** Defaults to the unique values found in the column. */
		options?: { label: string; value: string }[];
		/** ✦ depth of the toolbar and pagination controls (the table container stays flat). */
		elevation?: Elevation;
	} = $props();

	const facets = $derived(column?.getFacetedUniqueValues());
	const items = $derived(
		options ??
			Array.from(facets?.keys() ?? []).map((value) => ({
				label: String(value),
				value: String(value),
			}))
	);
	const selected = $derived(new Set((column?.getFilterValue() as string[] | undefined) ?? []));

	function toggle(value: string, checked: boolean) {
		const next = new Set(selected);
		if (checked) next.add(value);
		else next.delete(value);
		column?.setFilterValue(next.size ? Array.from(next) : undefined);
	}
</script>

{#if column}
	<DropdownMenu.Root>
		<DropdownMenu.Trigger>
			{#snippet child({ props })}
				<Button {...props} variant="outline" size="sm" {elevation} class="border-dashed">
					<PlusIcon  />
					{title}
					{#if selected.size > 0}
						<Badge variant="brand" shape="number">{selected.size}</Badge>
					{/if}
				</Button>
			{/snippet}
		</DropdownMenu.Trigger>
		<DropdownMenu.Content align="start" class="w-48">
			<DropdownMenu.Group>
				<DropdownMenu.Label>{title}</DropdownMenu.Label>
				<DropdownMenu.Separator />
				{#each items as option (option.value)}
					<DropdownMenu.CheckboxItem
						class="capitalize"
						checked={selected.has(option.value)}
						onCheckedChange={(checked) => toggle(option.value, !!checked)}
					>
						{option.label}
						<span class="ml-auto font-mono text-xs text-muted-foreground">
							{facets?.get(option.value) ?? 0}
						</span>
					</DropdownMenu.CheckboxItem>
				{/each}
			</DropdownMenu.Group>
		</DropdownMenu.Content>
	</DropdownMenu.Root>
{/if}

// examples/layerbeat-vue/src/components/ui/data-table/DataTableFacetedFilter.vue
<script setup lang="ts" generic="TData extends RowData, TValue">
import type { Column, RowData } from "@tanstack/vue-table";
import { PhPlus } from '@phosphor-icons/vue';
import { computed } from "vue";
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { Elevation } from '@/components/ui/elevation';
import {
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import type { DataTableFeatures } from "./dataTableFeatures";

/**
 * ✦ Dashed "+ Status" filter button with a checkbox menu. The column must set
 * `filterFn: "arrHas"`.
 */
const props = withDefaults(defineProps<{
    column?: Column<DataTableFeatures, TData, TValue>;
    title: string;
    /** ✦ depth of the toolbar and pagination controls (the table container stays flat). */
    elevation?: Elevation;
    /** Defaults to the unique values found in the column. */
    options?: { label: string; value: string }[];
}>(), { elevation: undefined });

const facets = computed(() => props.column?.getFacetedUniqueValues());
const items = computed(
    () =>
        props.options ??
        Array.from(facets.value?.keys() ?? []).map((value) => ({
            label: String(value),
            value: String(value),
        })),
);
const selected = computed(
    () => new Set((props.column?.getFilterValue() as string[] | undefined) ?? []),
);

function toggle(value: string, checked: boolean) {
    const next = new Set(selected.value);
    if (checked) next.add(value);
    else next.delete(value);
    props.column?.setFilterValue(next.size ? Array.from(next) : undefined);
}
</script>

<template>
	<DropdownMenu v-if="column">
		<DropdownMenuTrigger as-child>
			<Button variant="outline" size="sm" :elevation="elevation" class="border-dashed">
				<PhPlus />
				{{ title }}
				<Badge v-if="selected.size > 0" variant="brand" shape="number">
					{{ selected.size }}
				</Badge>
			</Button>
		</DropdownMenuTrigger>
		<DropdownMenuContent align="start" class="w-48">
			<DropdownMenuGroup>
				<DropdownMenuLabel>{{ title }}</DropdownMenuLabel>
				<DropdownMenuSeparator />
				<DropdownMenuCheckboxItem
					v-for="option in items"
					:key="option.value"
					class="capitalize"
					:model-value="selected.has(option.value)"
					@update:model-value="(checked: boolean) => toggle(option.value, !!checked)"
				>
					{{ option.label }}
					<span class="ml-auto font-mono text-xs text-muted-foreground">
						{{ facets?.get(option.value) ?? 0 }}
					</span>
				</DropdownMenuCheckboxItem>
			</DropdownMenuGroup>
		</DropdownMenuContent>
	</DropdownMenu>
</template>
