// examples/react/src/components/ui/toggle-group.tsx
"use client";

import { Toggle as TogglePrimitive } from "@base-ui/react/toggle";
import { ToggleGroup as ToggleGroupPrimitive } from "@base-ui/react/toggle-group";
import type { VariantProps } from "class-variance-authority";
import { cn } from "cn";
import * as React from "react";

import {
	type Elevation,
	type ElevationLevel,
	useElevation,
} from "@/components/ui/elevation";
import { toggleVariants } from "@/components/ui/toggle";

const ToggleGroupContext = React.createContext<
	VariantProps<typeof toggleVariants> & {
		spacing?: number;
		orientation?: "horizontal" | "vertical";
		elevation?: ElevationLevel;
	}
>({
	size: "default",
	variant: "default",
	spacing: 2,
	orientation: "horizontal",
	elevation: undefined,
});

function ToggleGroup({
	className,
	variant,
	size,
	spacing = 2,
	orientation = "horizontal",
	elevation,
	children,
	...props
}: ToggleGroupPrimitive.Props &
	VariantProps<typeof toggleVariants> & {
		spacing?: number;
		orientation?: "horizontal" | "vertical";
		/** ✦ depth, passed down to every item (segmented: only the ON item rises). */
		elevation?: Elevation;
	}) {
	const level = useElevation(elevation, "control");
	// ✦ `variant="segmented"` renders a flat track (DESIGN §4.5); gap is fixed at 2px.
	const segmented = variant === "segmented";
	return (
		<ToggleGroupPrimitive
			data-slot="toggle-group"
			data-variant={variant}
			data-size={size}
			data-spacing={segmented ? 0.5 : spacing}
			data-orientation={orientation}
			style={{ "--gap": segmented ? 0.5 : spacing } as React.CSSProperties}
			className={cn(
				"group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] rounded-lg data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch",
				segmented &&
					"rounded-[10px] border border-border bg-muted p-[3px] shadow-[inset_0_1px_2px_rgb(0_0_0/0.04)]",
				className,
			)}
			{...props}
		>
			<ToggleGroupContext.Provider
				value={{ variant, size, spacing, orientation, elevation: level }}
			>
				{children}
			</ToggleGroupContext.Provider>
		</ToggleGroupPrimitive>
	);
}

function ToggleGroupItem({
	className,
	children,
	variant = "default",
	size = "default",
	elevation,
	...props
}: TogglePrimitive.Props &
	Omit<VariantProps<typeof toggleVariants>, "elevation"> & {
		elevation?: Elevation;
	}) {
	const context = React.useContext(ToggleGroupContext);

	return (
		<TogglePrimitive
			data-slot="toggle-group-item"
			data-variant={context.variant || variant}
			data-size={context.size || size}
			data-spacing={context.spacing}
			className={cn(
				"shrink-0 focus:z-10 focus-visible:z-10 group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-2 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-end]:pr-1.5 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-start]:pl-1.5 group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:first:rounded-l-lg group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:first:rounded-t-lg group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:last:rounded-r-lg group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:last:rounded-b-lg group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-[orientation=horizontal]/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-[orientation=vertical]/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t",
				toggleVariants({
					variant: context.variant || variant,
					size: context.size || size,
					elevation:
						elevation && elevation !== "auto" ? elevation : context.elevation,
				}),
				className,
			)}
			{...props}
		>
			{children}
		</TogglePrimitive>
	);
}

export { ToggleGroup, ToggleGroupItem };

// examples/svelte/src/lib/components/ui/toggle-group/toggle-group.svelte
<script lang="ts" module>
	import { getContext, setContext } from "svelte";
	import { type Elevation, type ElevationLevel, useElevation } from "#lib/components/ui/elevation/index.js";
	import { toggleVariants } from "#lib/components/ui/toggle/index.js";
	import type { VariantProps } from "tailwind-variants";

	type ToggleVariants = VariantProps<typeof toggleVariants>;

	interface ToggleGroupContext extends ToggleVariants {
		spacing?: number;
		orientation?: "horizontal" | "vertical";
		elevation?: ElevationLevel;
	}

	export function setToggleGroupCtx(props: ToggleGroupContext) {
		setContext("toggleGroup", props);
	}

	export function getToggleGroupCtx() {
		return getContext<Required<ToggleGroupContext>>("toggleGroup");
	}
</script>

<script lang="ts">
	import { ToggleGroup as ToggleGroupPrimitive } from "bits-ui";
	import { cn } from "#lib/utils.js";

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		size = "default",
		spacing = 2,
		orientation = "horizontal",
		variant = "default",
		elevation = "auto",
		...restProps
	}: ToggleGroupPrimitive.RootProps &
		Omit<ToggleVariants, "elevation"> & {
			spacing?: number;
			orientation?: "horizontal" | "vertical";
			/** ✦ depth passed down to every item (segmented: only the ON item rises). */
			elevation?: Elevation;
		} = $props();

	const level = useElevation(() => elevation, "control");

	setToggleGroupCtx({
		get variant() {
			return variant;
		},
		get size() {
			return size;
		},
		get spacing() {
			return spacing;
		},
		get orientation() {
			return orientation;
		},
		get elevation() {
			return level.current;
		},
	});

	// ✦ `variant="segmented"` renders a flat track (DESIGN §4.5); gap is fixed at 2px.
	const segmented = $derived(variant === "segmented");
</script>

<!--
Discriminated Unions + Destructing (required for bindable) do not
get along, so we shut typescript up by casting `value` to `never`.
-->
<ToggleGroupPrimitive.Root
	bind:value={value as never}
	bind:ref
	{orientation}
	data-slot="toggle-group"
	data-variant={variant}
	data-size={size}
	data-elevation={level.current === "flat" ? undefined : level.current}
	data-spacing={segmented ? 0.5 : spacing}
	style={`--gap: ${segmented ? 0.5 : spacing}`}
	class={cn(
		"group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] rounded-lg data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch",
		segmented && "rounded-[10px] border border-border bg-muted p-[3px] shadow-[inset_0_1px_2px_rgb(0_0_0/0.04)]",
		className
	)}
	{...restProps}
/>
