// packages/svelte/src/lib/registry/ai/audio-player/audio-player-element.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import type { Experimental_SpeechResult as SpeechResult } from "ai";
	import type { HTMLAudioAttributes } from "svelte/elements";

	// Pass `src`, or `data` (an AI SDK speech result). Captions are provided by the consumer.
	let {
		src,
		data,
		...restProps
	}: Omit<HTMLAudioAttributes, "src"> & {
		src?: string;
		data?: SpeechResult["audio"];
	} = $props();

	const audioSrc = $derived(
		src ?? (data ? `data:${data.mediaType};base64,${data.base64}` : undefined)
	);
</script>

<!-- svelte-ignore a11y_media_has_caption -->
<audio
	data-slot="ai-audio-player-element"
	src={audioSrc}
	{...restProps}
	{...{ slot: "media" }}
></audio>

// packages/vue/registry/components/ai/audio-player/AudioPlayerElement.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { Experimental_SpeechResult as SpeechResult } from "ai"
import { computed } from "vue"

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  src?: string
  data?: SpeechResult["audio"]
}>()

const audioSrc = computed(() => {
  if (props.src)
    return props.src
  if (props.data)
    return `data:${props.data.mediaType};base64,${props.data.base64}`
  return undefined
})
</script>

<template>
  <!-- Captions are provided by the consumer. -->
  <audio
    v-bind="{ ...$attrs, slot: 'media' }"
    data-slot="ai-audio-player-element"
    :src="audioSrc"
  />
</template>
