// packages/svelte/src/lib/registry/ai/attachments/attachment-info.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";
	import { useAttachmentContext } from "./use-attachments.svelte.js";
	import { formatSize, getAttachmentLabel } from "./utils.js";

	let {
		showMediaType = false,
		class: className,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		showMediaType?: boolean;
	} = $props();

	const attachment = useAttachmentContext();
	const label = $derived(getAttachmentLabel(attachment.data));
	const meta = $derived(
		[attachment.data.mediaType, formatSize(attachment.data.size)].filter(Boolean).join(" · ")
	);
	const variant = $derived(attachment.variant);
</script>

<div
	data-slot="ai-attachment-info"
	class={cn("min-w-0", variant === "grid" ? "mt-1.5 w-full" : "flex-1", className)}
	{...restProps}
>
	<span
		class={cn(
			"block truncate",
			variant === "inline" && "font-medium",
			variant === "list" && "text-[13.5px] font-medium",
			variant === "grid" && "text-xs text-foreground"
		)}
	>
		{label}
	</span>
	{#if showMediaType && meta}
		<span class="block truncate text-xs text-muted-foreground">{meta}</span>
	{/if}
</div>

// packages/vue/registry/components/ai/attachments/AttachmentInfo.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { useAttachmentContext } from "./context"
import { formatSize, getAttachmentLabel } from "./utils"

const props = withDefaults(defineProps<{
  showMediaType?: boolean
  class?: HTMLAttributes["class"]
}>(), {
  showMediaType: false,
})

const { data, variant } = useAttachmentContext()
const label = computed(() => getAttachmentLabel(data.value))
const meta = computed(() =>
  [data.value.mediaType, formatSize(data.value.size)].filter(Boolean).join(" · "))
</script>

<template>
  <div
    data-slot="ai-attachment-info"
    :class="cn('min-w-0', variant === 'grid' ? 'mt-1.5 w-full' : 'flex-1', props.class)"
  >
    <span
      :class="cn(
        'block truncate',
        variant === 'inline' && 'font-medium',
        variant === 'list' && 'text-[13.5px] font-medium',
        variant === 'grid' && 'text-xs text-foreground',
      )"
    >
      {{ label }}
    </span>
    <span v-if="props.showMediaType && meta" class="block truncate text-xs text-muted-foreground">
      {{ meta }}
    </span>
  </div>
</template>
