// packages/vue/registry/components/ai/task/TaskItem.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes, VNode } from "vue"
import { AlertCircleIcon, CircleCheckIcon, CircleIcon, Loader2Icon } from "@lucide/vue"
import { Text, h, useSlots } from "vue"
import { cn } from "@/registry/edmi/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
  /** ✦ Leading status icon: pending, in-progress (spinner), completed (struck through), error. */
  status?: "pending" | "in-progress" | "completed" | "error"
}>()

const slots = useSlots()

// line-through only the text, not the file chips (decorations propagate into flex items)
function Content() {
  const nodes: VNode[] = slots.default?.() ?? []
  if (props.status !== "completed")
    return nodes
  return nodes.map(node =>
    node.type === Text && typeof node.children === "string"
      ? h("span", { class: "line-through" }, node.children)
      : node,
  )
}
</script>

<template>
  <div
    v-if="status"
    data-slot="ai-task-item"
    :data-status="status"
    :class="cn(
      'flex flex-wrap items-center gap-2 text-[13.5px] [&>svg]:size-4 [&>svg]:shrink-0',
      status === 'completed' && 'text-muted-foreground',
      status === 'pending' && 'text-muted-foreground',
      status === 'error' && 'text-destructive-text',
      props.class,
    )"
  >
    <CircleIcon v-if="status === 'pending'" class="text-muted-foreground-2" />
    <Loader2Icon v-else-if="status === 'in-progress'" class="animate-spin text-info-text" />
    <CircleCheckIcon v-else-if="status === 'completed'" class="text-success-text" />
    <AlertCircleIcon v-else class="text-destructive-text" />
    <Content />
  </div>
  <div v-else data-slot="ai-task-item" :class="cn('text-[13.5px] text-muted-foreground', props.class)">
    <slot />
  </div>
</template>

// packages/svelte/src/lib/registry/ai/task/task-item.svelte
<!-- Derived from Svelte AI Elements (MIT), modified for Edmi UI. -->
<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { cn } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		class: className,
		status,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		/** ✦ Leading status icon: pending, in-progress (spinner), completed (struck through), error. */
		status?: "pending" | "in-progress" | "completed" | "error";
	} = $props();
</script>

{#if status}
	<div
		data-slot="ai-task-item"
		data-status={status}
		class={cn(
			"flex items-start gap-2 text-[13.5px] [&>svg]:mt-0.5 [&>svg]:size-4 [&>svg]:shrink-0",
			(status === "completed" || status === "pending") && "text-muted-foreground",
			status === "error" && "text-destructive-text",
			className
		)}
		{...restProps}
	>
		{#if status === "pending"}
			<IconPlaceholder
				lucide="CircleIcon"
				tabler="IconCircle"
				hugeicons="CircleIcon"
				phosphor="CircleIcon"
				remixicon="RiCircleLine"
				class="text-muted-foreground-2"
			/>
		{:else if status === "in-progress"}
			<IconPlaceholder
				lucide="Loader2Icon"
				tabler="IconLoader"
				hugeicons="Loading03Icon"
				phosphor="SpinnerIcon"
				remixicon="RiLoaderLine"
				class="animate-spin text-info-text"
			/>
		{:else if status === "completed"}
			<IconPlaceholder
				lucide="CircleCheckIcon"
				tabler="IconCircleCheck"
				hugeicons="CheckmarkCircle02Icon"
				phosphor="CheckCircleIcon"
				remixicon="RiCheckboxCircleLine"
				class="text-success-text"
			/>
		{:else}
			<IconPlaceholder
				lucide="CircleAlertIcon"
				tabler="IconAlertCircle"
				hugeicons="AlertCircleIcon"
				phosphor="WarningCircleIcon"
				remixicon="RiErrorWarningLine"
				class="text-destructive-text"
			/>
		{/if}
		<!-- Inline flow: the line-through reaches the text but not the inline-flex file chips. -->
		<span class={cn("min-w-0", status === "completed" && "line-through")}>
			{@render children?.()}
		</span>
	</div>
{:else}
	<div data-slot="ai-task-item" class={cn("text-[13.5px] text-muted-foreground", className)} {...restProps}>
		{@render children?.()}
	</div>
{/if}
