// examples/svelte/src/lib/components/ui/feature-row/feature-row.svelte
<script lang="ts">
	import { cn } from "#lib/utils.js";
	import { Card } from "#lib/components/ui/card/index.js";
	import * as Collapsible from "#lib/components/ui/collapsible/index.js";
	import PlusIcon from 'phosphor-svelte/lib/Plus';
	import type { ComponentProps, Snippet } from "svelte";

	let {
		class: className,
		index,
		title,
		icon,
		children,
		...restProps
	}: Omit<ComponentProps<typeof Card>, "title" | "children"> & {
		/** Mono number, e.g. "1.1". */
		index: string | number;
		title: string;
		/** Trailing icon; defaults to a plus. */
		icon?: Snippet;
		/** When set the row expands to show this content. */
		children?: Snippet;
	} = $props();
</script>

{#snippet plus()}
	<PlusIcon class="size-4" />
{/snippet}

{#if !children}
	<Card data-slot="feature-row" class={cn("h-14 flex-row items-center gap-4 px-5 py-0", className)} {...restProps}>
		<span class="font-mono text-xs text-muted-foreground">{index}</span>
		<span class="flex-1 text-left text-base font-medium">{title}</span>
		<span class="text-muted-foreground">{@render (icon ?? plus)()}</span>
	</Card>
{:else}
	<Card data-slot="feature-row" class={cn("gap-0 py-0", className)} {...restProps}>
		<Collapsible.Root class="group/feature-row">
			<Collapsible.Trigger
				class="flex h-14 w-full cursor-pointer items-center gap-4 px-5 outline-none focus-visible:bg-accent"
			>
				<span class="font-mono text-xs text-muted-foreground">{index}</span>
				<span class="flex-1 text-left text-base font-medium">{title}</span>
				<span class="text-muted-foreground transition-transform group-data-[state=open]/feature-row:rotate-45">
					{@render (icon ?? plus)()}
				</span>
			</Collapsible.Trigger>
			<Collapsible.Content class="px-5 pb-4 pl-[52px] text-sm text-muted-foreground">
				{@render children()}
			</Collapsible.Content>
		</Collapsible.Root>
	</Card>
{/if}

// packages/react/registry/blocks/feature-row/feature-row.tsx
"use client";

import { cn } from "cn";
import type * as React from "react";
import { IconPlaceholder } from "@/edmi/icon-placeholder";
import { Card } from "@/registry/edmi/ui/card";
import {
	Collapsible,
	CollapsibleContent,
	CollapsibleTrigger,
} from "@/registry/edmi/ui/collapsible";

type FeatureRowProps = Omit<React.ComponentProps<typeof Card>, "title"> & {
	/** Mono number, e.g. "1.1". */
	index: React.ReactNode;
	title: React.ReactNode;
	/** Trailing icon element; defaults to a plus. */
	icon?: React.ReactNode;
	/** When set the row expands to show this content. */
	children?: React.ReactNode;
};

const plus = (
	<IconPlaceholder
		lucide="PlusIcon"
		tabler="IconPlus"
		hugeicons="Add01Icon"
		phosphor="PlusIcon"
		remixicon="RiAddLine"
		className="size-4"
	/>
);

function FeatureRow({
	className,
	index,
	title,
	icon = plus,
	children,
	...props
}: FeatureRowProps) {
	const head = (
		<>
			<span className="font-mono text-xs text-muted-foreground">{index}</span>
			<span className="flex-1 text-left text-base font-medium">{title}</span>
			<span className="text-muted-foreground transition-transform group-data-[panel-open]/feature-row:rotate-45">
				{icon}
			</span>
		</>
	);
	if (!children) {
		return (
			<Card
				data-slot="feature-row"
				className={cn("h-14 flex-row items-center gap-4 px-5 py-0", className)}
				{...props}
			>
				{head}
			</Card>
		);
	}
	return (
		<Card
			data-slot="feature-row"
			className={cn("gap-0 py-0", className)}
			{...props}
		>
			<Collapsible>
				<CollapsibleTrigger className="group/feature-row flex h-14 w-full cursor-pointer items-center gap-4 px-5 outline-none focus-visible:bg-accent">
					{head}
				</CollapsibleTrigger>
				<CollapsibleContent className="px-5 pb-4 pl-[52px] text-sm text-muted-foreground">
					{children}
				</CollapsibleContent>
			</Collapsible>
		</Card>
	);
}

export { FeatureRow };
