// packages/vue/registry/components/ai/voice-selector/VoiceSelectorPreview.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { PlayIcon } from "@lucide/vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Button } from "@/registry/edmi/ui/button"
import { Spinner } from "@/registry/edmi/ui/spinner"

const props = defineProps<{
  class?: HTMLAttributes["class"]
  playing?: boolean
  loading?: boolean
}>()

const emit = defineEmits<{
  (e: "play"): void
}>()

function handleClick(event: MouseEvent) {
  event.stopPropagation()
  emit("play")
}
</script>

<template>
  <Button
    data-slot="ai-voice-selector-preview"
    type="button"
    variant="ghost"
    size="icon-xs"
    :aria-label="props.playing ? 'Pause preview' : 'Play preview'"
    :disabled="props.loading"
    :class="cn('mt-px', props.class)"
    @click="handleClick"
  >
    <Spinner v-if="props.loading" class="size-3" />
    <svg v-else-if="props.playing" class="size-3" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M7 4h4v16H7zM13 4h4v16h-4z" />
    </svg>
    <PlayIcon v-else class="size-3 fill-current" />
  </Button>
</template>

// packages/svelte/src/lib/registry/ai/voice-selector/voice-selector-preview.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { Button, type ButtonProps } from "$lib/registry/ui/button/index.js";
	import { Spinner } from "$lib/registry/ui/spinner/index.js";
	import { cn } from "$lib/utils.js";

	let {
		class: className,
		playing = false,
		loading = false,
		onPlay,
		onclick,
		...restProps
	}: Omit<ButtonProps, "children" | "href" | "onclick"> & {
		onclick?: (event: MouseEvent) => void;
		playing?: boolean;
		loading?: boolean;
		onPlay?: () => void;
	} = $props();
</script>

<Button
	data-slot="ai-voice-selector-preview"
	type="button"
	variant="ghost"
	size="icon-xs"
	aria-label={playing ? "Pause preview" : "Play preview"}
	disabled={loading}
	class={cn("mt-px", className)}
	onclick={(event) => {
		event.stopPropagation();
		onclick?.(event);
		onPlay?.();
	}}
	{...restProps}
>
	{#if loading}
		<Spinner class="size-3" />
	{:else if playing}
		<IconPlaceholder
			lucide="PauseIcon"
			tabler="IconPlayerPause"
			hugeicons="PauseIcon"
			phosphor="PauseIcon"
			remixicon="RiPauseLine"
			class="size-3 fill-current"
		/>
	{:else}
		<IconPlaceholder
			lucide="PlayIcon"
			tabler="IconPlayerPlay"
			hugeicons="PlayIcon"
			phosphor="PlayIcon"
			remixicon="RiPlayLine"
			class="size-3 fill-current"
		/>
	{/if}
</Button>
