// packages/vue/registry/ui/data-table/DataTablePagination.vue
<script setup lang="ts" generic="TData extends RowData">
import type { RowData, Table } from "@tanstack/vue-table";
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "@lucide/vue";
import { computed } from "vue";
import { Button } from "@/registry/edmi/ui/button";
import type { Elevation } from "@/registry/edmi/ui/elevation";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/registry/edmi/ui/select";
import type { DataTableFeatures } from "./dataTableFeatures";

const props = withDefaults(
	defineProps<{
		table: Table<DataTableFeatures, TData>;
		pageSizes?: number[];
		/** ✦ depth of the toolbar and pagination controls (the table container stays flat). */
		elevation?: Elevation;
	}>(),
	{ pageSizes: () => [10, 20, 30, 40, 50] },
);

// The current size (e.g. `DataTable :page-size="5"`) must be an option, or the trigger renders blank.
const sizes = computed(() => {
	const current = props.table.atoms.pagination.get().pageSize;
	return props.pageSizes.includes(current)
		? props.pageSizes
		: [...props.pageSizes, current].sort((a, b) => a - b);
});
</script>

<template>
	<div class="flex items-center justify-between gap-4 text-[13px]">
		<div class="flex-1 text-muted-foreground">
			{{ table.getFilteredSelectedRowModel().rows.length }} of
			{{ table.getFilteredRowModel().rows.length }} row(s) selected.
		</div>
		<div class="flex items-center gap-4 lg:gap-6">
			<div class="flex items-center gap-2">
				<span class="text-muted-foreground">Rows per page</span>
				<Select
					:model-value="`${table.atoms.pagination.get().pageSize}`"
					@update:model-value="(value) => table.setPageSize(Number(value))"
				>
					<SelectTrigger size="sm" :elevation="elevation" class="w-[72px]">
						<SelectValue />
					</SelectTrigger>
					<SelectContent side="top">
						<SelectItem v-for="size in sizes" :key="size" :value="`${size}`">
							{{ size }}
						</SelectItem>
					</SelectContent>
				</Select>
			</div>
			<div class="flex min-w-[88px] items-center justify-center font-medium">
				Page {{ table.atoms.pagination.get().pageIndex + 1 }} of
				{{ table.getPageCount() }}
			</div>
			<div class="flex items-center gap-1">
				<Button
					variant="outline"
					size="icon-sm"
					:elevation="elevation"
					class="hidden lg:inline-flex"
					:disabled="!table.getCanPreviousPage()"
					@click="table.setPageIndex(0)"
				>
					<span class="sr-only">Go to first page</span>
					<ChevronsLeft />
				</Button>
				<Button
					variant="outline"
					size="icon-sm"
					:elevation="elevation"
					:disabled="!table.getCanPreviousPage()"
					@click="table.previousPage()"
				>
					<span class="sr-only">Go to previous page</span>
					<ChevronLeft />
				</Button>
				<Button
					variant="outline"
					size="icon-sm"
					:elevation="elevation"
					:disabled="!table.getCanNextPage()"
					@click="table.nextPage()"
				>
					<span class="sr-only">Go to next page</span>
					<ChevronRight />
				</Button>
				<Button
					variant="outline"
					size="icon-sm"
					:elevation="elevation"
					class="hidden lg:inline-flex"
					:disabled="!table.getCanNextPage()"
					@click="table.setPageIndex(table.getPageCount() - 1)"
				>
					<span class="sr-only">Go to last page</span>
					<ChevronsRight />
				</Button>
			</div>
		</div>
	</div>
</template>

// packages/react/registry/blocks/data-table/data-table-pagination.tsx
import type { ReactTable, RowData } from "@tanstack/react-table";
import { IconPlaceholder } from "@/edmi/icon-placeholder";
import { Button } from "@/registry/edmi/ui/button";
import type { Elevation } from "@/registry/edmi/ui/elevation";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/registry/edmi/ui/select";
import type { DataTableFeatures } from "./data-table-features";

interface DataTablePaginationProps<TData extends RowData> {
	table: ReactTable<DataTableFeatures, TData>;
	pageSizes?: number[];
	/** ✦ depth of the toolbar and pagination controls (the table container stays flat). */
	elevation?: Elevation;
}

export function DataTablePagination<TData extends RowData>({
	table,
	pageSizes = [10, 20, 30, 40, 50],
	elevation,
}: DataTablePaginationProps<TData>) {
	const { pageIndex, pageSize } = table.state.pagination;
	// The current size (e.g. `DataTable pageSize={5}`) must be an option, or the trigger renders blank.
	const sizes = pageSizes.includes(pageSize)
		? pageSizes
		: [...pageSizes, pageSize].sort((a, b) => a - b);

	return (
		<div className="flex items-center justify-between gap-4 text-[13px]">
			<div className="flex-1 text-muted-foreground">
				{table.getFilteredSelectedRowModel().rows.length} of{" "}
				{table.getFilteredRowModel().rows.length} row(s) selected.
			</div>
			<div className="flex items-center gap-4 lg:gap-6">
				<div className="flex items-center gap-2">
					<span className="text-muted-foreground">Rows per page</span>
					<Select
						value={`${pageSize}`}
						onValueChange={(value) => table.setPageSize(Number(value))}
					>
						<SelectTrigger size="sm" elevation={elevation} className="w-[72px]">
							<SelectValue />
						</SelectTrigger>
						<SelectContent side="top">
							{sizes.map((size) => (
								<SelectItem key={size} value={`${size}`}>
									{size}
								</SelectItem>
							))}
						</SelectContent>
					</Select>
				</div>
				<div className="flex min-w-[88px] items-center justify-center font-medium">
					Page {pageIndex + 1} of {table.getPageCount()}
				</div>
				<div className="flex items-center gap-1">
					<Button
						variant="outline"
						size="icon-sm"
						elevation={elevation}
						className="hidden lg:inline-flex"
						onClick={() => table.setPageIndex(0)}
						disabled={!table.getCanPreviousPage()}
					>
						<span className="sr-only">Go to first page</span>
						<IconPlaceholder
							lucide="ChevronsLeftIcon"
							tabler="IconChevronsLeft"
							hugeicons="ArrowLeftDoubleIcon"
							phosphor="CaretDoubleLeftIcon"
							remixicon="RiSkipLeftLine"
						/>
					</Button>
					<Button
						variant="outline"
						size="icon-sm"
						elevation={elevation}
						onClick={() => table.previousPage()}
						disabled={!table.getCanPreviousPage()}
					>
						<span className="sr-only">Go to previous page</span>
						<IconPlaceholder
							lucide="ChevronLeftIcon"
							tabler="IconChevronLeft"
							hugeicons="ArrowLeft01Icon"
							phosphor="CaretLeftIcon"
							remixicon="RiArrowLeftSLine"
						/>
					</Button>
					<Button
						variant="outline"
						size="icon-sm"
						elevation={elevation}
						onClick={() => table.nextPage()}
						disabled={!table.getCanNextPage()}
					>
						<span className="sr-only">Go to next page</span>
						<IconPlaceholder
							lucide="ChevronRightIcon"
							tabler="IconChevronRight"
							hugeicons="ArrowRight01Icon"
							phosphor="CaretRightIcon"
							remixicon="RiArrowRightSLine"
						/>
					</Button>
					<Button
						variant="outline"
						size="icon-sm"
						elevation={elevation}
						className="hidden lg:inline-flex"
						onClick={() => table.setPageIndex(table.getPageCount() - 1)}
						disabled={!table.getCanNextPage()}
					>
						<span className="sr-only">Go to last page</span>
						<IconPlaceholder
							lucide="ChevronsRightIcon"
							tabler="IconChevronsRight"
							hugeicons="ArrowRightDoubleIcon"
							phosphor="CaretDoubleRightIcon"
							remixicon="RiSkipRightLine"
						/>
					</Button>
				</div>
			</div>
		</div>
	);
}
