// packages/vue/registry/components/ai/mic-selector/MicSelectorTrigger.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { ChevronsUpDown } from "@lucide/vue"
import { useResizeObserver } from "@vueuse/core"
import { ref } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Button } from "@/registry/edmi/ui/button"
import { PopoverTrigger } from "@/registry/edmi/ui/popover"
import { useMicSelector } from "./context"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()

const { setWidth } = useMicSelector("MicSelectorTrigger")
const triggerRef = ref<InstanceType<typeof Button> | null>(null)

// Track the trigger width so the list below matches it.
useResizeObserver(triggerRef, (entries) => {
  const entry = entries[0]
  if (!entry)
    return
  const next = (entry.target as HTMLElement).offsetWidth
  if (next)
    setWidth(next)
})
</script>

<template>
  <PopoverTrigger as-child>
    <Button
      ref="triggerRef"
      data-slot="ai-mic-selector-trigger"
      variant="outline"
      :class="cn('justify-start font-normal', props.class)"
    >
      <slot />
      <ChevronsUpDown class="ml-auto size-3.5 shrink-0 text-muted-foreground" />
    </Button>
  </PopoverTrigger>
</template>

// packages/svelte/src/lib/registry/ai/mic-selector/mic-selector-trigger.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { Button } from "$lib/registry/ui/button/index.js";
	import { PopoverTrigger } from "$lib/registry/ui/popover/index.js";
	import { cn } from "$lib/utils.js";
	import type { ComponentProps, Snippet } from "svelte";
	import { useMicSelector } from "./use-mic-selector.svelte.js";

	let {
		class: className,
		children,
		...restProps
	}: Omit<ComponentProps<typeof Button>, "children"> & { children?: Snippet } = $props();

	const ctx = useMicSelector("MicSelectorTrigger");
	let el = $state<HTMLElement | null>(null);

	// Track the trigger width so the list below matches it.
	$effect(() => {
		if (!el) return;
		const target = el;
		const observer = new ResizeObserver(() => {
			if (target.offsetWidth) ctx.setWidth(target.offsetWidth);
		});
		observer.observe(target);
		return () => observer.disconnect();
	});
</script>

<PopoverTrigger data-slot="ai-mic-selector-trigger">
	{#snippet child({ props })}
		<Button
			bind:ref={el}
			variant="outline"
			class={cn("justify-start font-normal", className)}
			{...props}
			{...restProps}
		>
			{@render children?.()}
			<IconPlaceholder
				lucide="ChevronsUpDownIcon"
				tabler="IconSelector"
				hugeicons="UnfoldMoreIcon"
				phosphor="CaretUpDownIcon"
				remixicon="RiArrowUpDownLine"
				class="ml-auto size-3.5 shrink-0 text-muted-foreground"
			/>
		</Button>
	{/snippet}
</PopoverTrigger>
