// packages/vue/registry/components/ai/mic-selector/MicSelectorLabel.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"

const props = withDefaults(defineProps<{
  device: MediaDeviceInfo
  /** Show the hardware id (`1a2b:3c4d`) in muted mono after the name. */
  showId?: boolean
  class?: HTMLAttributes["class"]
}>(), { showId: true })

const deviceIdRegex = /\(([\da-f]{4}:[\da-f]{4})\)$/i

const parsed = computed(() => {
  const matches = props.device.label.match(deviceIdRegex)
  if (!matches)
    return { name: props.device.label, deviceId: null }
  return { name: props.device.label.replace(deviceIdRegex, "").trim(), deviceId: matches[1] }
})
</script>

<template>
  <span :class="cn('flex min-w-0 flex-1 items-center gap-2', props.class)">
    <span class="truncate">{{ parsed.name }}</span>
    <span
      v-if="parsed.deviceId && showId"
      class="ml-auto shrink-0 font-mono text-[11.5px] text-muted-foreground"
    >{{ parsed.deviceId }}</span>
  </span>
</template>

// packages/svelte/src/lib/registry/ai/mic-selector/mic-selector-label.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		device,
		showId = true,
		class: className,
		...restProps
	}: HTMLAttributes<HTMLSpanElement> & {
		device: MediaDeviceInfo;
		/** Show the hardware id (`1a2b:3c4d`) in muted mono after the name. */
		showId?: boolean;
	} = $props();

	const deviceIdRegex = /\(([\da-f]{4}:[\da-f]{4})\)$/i;
	const parsed = $derived.by(() => {
		const matches = device.label.match(deviceIdRegex);
		if (!matches) return { name: device.label, deviceId: null };
		return { name: device.label.replace(deviceIdRegex, "").trim(), deviceId: matches[1] };
	});
</script>

<span class={cn("flex min-w-0 flex-1 items-center gap-2", className)} {...restProps}>
	<span class="truncate">{parsed.name}</span>
	{#if parsed.deviceId && showId}
		<span class="ml-auto shrink-0 font-mono text-[11.5px] text-muted-foreground">{parsed.deviceId}</span>
	{/if}
</span>
