// packages/vue/registry/ui/pricing-plan/PricingPlan.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { Check } from '@lucide/vue'
import { Card } from '@/registry/edmi/ui/card'
import { Separator } from '@/registry/edmi/ui/separator'
import { cn } from '@/registry/edmi/lib/utils'

const props = defineProps<{
  /** ✦ one-step 3D look, forwarded to the card */
  raised?: boolean
  class?: HTMLAttributes['class']
  name: string
  tagline?: string
  /** Headline price, e.g. "1% fee to you". */
  price?: string
  /** Small note under the price. */
  priceNote?: string
  features?: string[]
  /** ✦ Lead row above the features, e.g. "Included:" or "Everything in Holder, plus:". */
  featuresLead?: string
}>()
// Slot `action` = call to action, usually a full-width `Button`.
// ✦ Slot `features-lead` = rich lead row (overrides `featuresLead`).
// ✦ Scoped slot `feature` ({ feature, index }) = rich content for a feature row (default: the text).
</script>

<template>
  <Card :raised="raised" data-slot="pricing-plan" :class="cn('gap-0 p-6', props.class)">
    <div class="text-[22px] font-semibold">{{ name }}</div>
    <div v-if="tagline" class="mt-1 text-[13.5px] text-muted-foreground">{{ tagline }}</div>
    <div v-if="price" class="mt-[22px] text-[22px] font-semibold">{{ price }}</div>
    <div v-if="priceNote" class="mt-1 text-[12.5px] text-muted-foreground">{{ priceNote }}</div>
    <div v-if="$slots.action" class="mt-[18px] [&>[data-slot=button]]:w-full">
      <slot name="action" />
    </div>
    <template v-if="features?.length">
      <Separator class="my-[18px]" />
      <div v-if="featuresLead || $slots['features-lead']" data-slot="pricing-plan-lead" class="mb-3.5 text-[15px] font-semibold">
        <slot name="features-lead">
          {{ featuresLead }}
        </slot>
      </div>
      <ul class="flex flex-col gap-2.5 text-[13.5px]">
        <li v-for="(f, i) in features" :key="i" class="flex items-center gap-2.5">
          <Check class="size-3.5 text-muted-foreground" />
          <slot name="feature" :feature="f" :index="i">
            {{ f }}
          </slot>
        </li>
      </ul>
    </template>
  </Card>
</template>

// examples/svelte/src/lib/components/ui/pricing-plan/pricing-plan.svelte
<script lang="ts">
	import { cn } from "#lib/utils.js";
	import { Card } from "#lib/components/ui/card/index.js";
	import { Separator } from "#lib/components/ui/separator/index.js";
	import CheckIcon from 'phosphor-svelte/lib/Check';
	import type { ComponentProps, Snippet } from "svelte";

	let {
		class: className,
		name,
		tagline,
		price,
		priceNote,
		action,
		features,
		featuresLead,
		feature,
		...restProps
	}: Omit<ComponentProps<typeof Card>, "title" | "children"> & {
		name: string;
		tagline?: string;
		/** Headline price, e.g. "1% fee to you". */
		price?: string;
		/** Small note under the price. */
		priceNote?: string;
		/** Call to action, usually a full-width `Button`. */
		action?: Snippet;
		features?: string[];
		/** ✦ Lead row above the features, e.g. "Included:" or "Everything in Holder, plus:". */
		featuresLead?: string | Snippet;
		/** ✦ Rich content for a feature row (default: the text). */
		feature?: Snippet<[string, number]>;
	} = $props();
</script>

<Card data-slot="pricing-plan" class={cn("gap-0 p-6", className)} {...restProps}>
	<div class="text-[22px] font-semibold">{name}</div>
	{#if tagline}<div class="mt-1 text-[13.5px] text-muted-foreground">{tagline}</div>{/if}
	{#if price}<div class="mt-[22px] text-[22px] font-semibold">{price}</div>{/if}
	{#if priceNote}<div class="mt-1 text-[12.5px] text-muted-foreground">{priceNote}</div>{/if}
	{#if action}
		<div class="mt-[18px] [&>[data-slot=button]]:w-full">{@render action()}</div>
	{/if}
	{#if features?.length}
		<Separator class="my-[18px]" />
		{#if featuresLead}
			<div data-slot="pricing-plan-lead" class="mb-3.5 text-[15px] font-semibold">
				{#if typeof featuresLead === "function"}{@render featuresLead()}{:else}{featuresLead}{/if}
			</div>
		{/if}
		<ul class="flex flex-col gap-2.5 text-[13.5px]">
			{#each features as f, i (i)}
				<li class="flex items-center gap-2.5">
					<CheckIcon class="size-3.5 text-muted-foreground" />
					{#if feature}{@render feature(f, i)}{:else}{f}{/if}
				</li>
			{/each}
		</ul>
	{/if}
</Card>
