// packages/vue/registry/components/ai/prompt-input/PromptInputActionAddScreenshot.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import { MonitorIcon } from "@lucide/vue"
import { DropdownMenuItem } from "@/registry/edmi/ui/dropdown-menu"
import { usePromptInputAttachments } from "./context"
import { captureScreenshot } from "./screenshot"

type Props = InstanceType<typeof DropdownMenuItem>["$props"]
interface PromptInputActionAddScreenshotProps extends /* @vue-ignore */ Props {
  label?: string
}

const props = withDefaults(defineProps<PromptInputActionAddScreenshotProps>(), {
  label: "Take screenshot",
})

const attachments = usePromptInputAttachments()

async function handleSelect(event: Event) {
  if (event.defaultPrevented)
    return
  try {
    const screenshot = await captureScreenshot()
    if (screenshot)
      attachments.add([screenshot])
  }
  catch (error) {
    // The user dismissed the capture picker: not an error.
    if (error instanceof DOMException && (error.name === "NotAllowedError" || error.name === "AbortError"))
      return
    throw error
  }
}
</script>

<template>
  <DropdownMenuItem @select="handleSelect">
    <MonitorIcon class="size-4" />
    {{ props.label }}
  </DropdownMenuItem>
</template>

// packages/svelte/src/lib/registry/ai/prompt-input/prompt-input-action-add-screenshot.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { DropdownMenuItem } from "$lib/registry/ui/dropdown-menu/index.js";
	import type { ComponentProps } from "svelte";
	import { captureScreenshot } from "./screenshot.js";
	import { usePromptInputAttachments } from "./use-prompt-input.svelte.js";

	let {
		label = "Take screenshot",
		...restProps
	}: Omit<ComponentProps<typeof DropdownMenuItem>, "children"> & { label?: string } = $props();

	const attachments = usePromptInputAttachments();

	async function handleSelect() {
		try {
			const screenshot = await captureScreenshot();
			if (screenshot) attachments.add([screenshot]);
		} catch (error) {
			// The user dismissed the capture picker: not an error.
			if (
				error instanceof DOMException &&
				(error.name === "NotAllowedError" || error.name === "AbortError")
			) {
				return;
			}
			throw error;
		}
	}
</script>

<DropdownMenuItem {...restProps} onSelect={handleSelect}>
	<IconPlaceholder
		lucide="MonitorIcon"
		tabler="IconDeviceDesktop"
		hugeicons="ComputerIcon"
		phosphor="MonitorIcon"
		remixicon="RiComputerLine"
		class="size-4"
	/>
	{label}
</DropdownMenuItem>
