// packages/vue/registry/components/ai/package-info/PackageInfo.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import type { PackageChangeType } from "./context"
import { computed, provide, useSlots } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { PackageInfoKey } from "./context"
import PackageInfoChangeType from "./PackageInfoChangeType.vue"
import PackageInfoHeader from "./PackageInfoHeader.vue"
import PackageInfoName from "./PackageInfoName.vue"
import PackageInfoVersion from "./PackageInfoVersion.vue"

const props = defineProps<{
  name: string
  currentVersion?: string
  newVersion?: string
  changeType?: PackageChangeType
  class?: HTMLAttributes["class"]
}>()

provide(PackageInfoKey, {
  name: computed(() => props.name),
  currentVersion: computed(() => props.currentVersion),
  newVersion: computed(() => props.newVersion),
  changeType: computed(() => props.changeType),
})

const slots = useSlots()
</script>

<template>
  <div
    data-slot="ai-package-info"
    :class="cn('rounded-xl border border-border bg-card px-4 py-3.5 text-card-foreground', props.class)"
  >
    <slot v-if="slots.default" />
    <PackageInfoHeader v-else>
      <PackageInfoName />
      <PackageInfoChangeType v-if="props.changeType" />
      <PackageInfoVersion />
    </PackageInfoHeader>
  </div>
</template>

// packages/svelte/src/lib/registry/ai/package-info/package-info.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import PackageInfoChangeType from "./package-info-change-type.svelte";
	import PackageInfoHeader from "./package-info-header.svelte";
	import PackageInfoName from "./package-info-name.svelte";
	import PackageInfoVersion from "./package-info-version.svelte";
	import { type PackageChangeType, setPackageInfoContext } from "./use-package-info.svelte.js";

	let {
		name,
		currentVersion,
		newVersion,
		changeType,
		class: className,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		name: string;
		currentVersion?: string;
		newVersion?: string;
		changeType?: PackageChangeType;
		children?: Snippet;
	} = $props();

	setPackageInfoContext({
		get name() {
			return name;
		},
		get currentVersion() {
			return currentVersion;
		},
		get newVersion() {
			return newVersion;
		},
		get changeType() {
			return changeType;
		},
	});
</script>

<div
	data-slot="ai-package-info"
	class={cn("rounded-xl border border-border bg-card px-4 py-3.5 text-card-foreground", className)}
	{...restProps}
>
	{#if children}
		{@render children()}
	{:else}
		<PackageInfoHeader>
			<PackageInfoName />
			{#if changeType}<PackageInfoChangeType />{/if}
			<PackageInfoVersion />
		</PackageInfoHeader>
	{/if}
</div>
