// packages/svelte/src/lib/registry/ai/transcription/transcription.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { setTranscriptionContext, type TranscriptionSegment } from "./use-transcription.svelte.js";

	let {
		segments,
		currentTime = $bindable(0),
		onSeek,
		class: className,
		children,
		...restProps
	}: Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
		segments: TranscriptionSegment[];
		/** Seconds; `bind:currentTime` to follow an audio element. */
		currentTime?: number;
		onSeek?: (time: number) => void;
		/** Receives each segment and its index: `{#snippet children(segment, index)}`. */
		children: Snippet<[TranscriptionSegment, number]>;
	} = $props();

	setTranscriptionContext({
		get segments() {
			return segments;
		},
		get currentTime() {
			return currentTime;
		},
		get onSeek() {
			return onSeek
				? (time: number) => {
						currentTime = time;
						onSeek(time);
					}
				: undefined;
		},
	});
</script>

<div
	data-slot="ai-transcription"
	class={cn("flex flex-wrap gap-x-1 gap-y-0.5 text-[15px] leading-[1.9]", className)}
	{...restProps}
>
	{#each segments as segment, index (`${segment.startSecond}-${segment.endSecond}-${index}`)}
		{#if segment.text.trim()}
			{@render children(segment, index)}
		{/if}
	{/each}
</div>

// packages/vue/registry/components/ai/transcription/Transcription.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import type { TranscriptionSegment } from "./context"
import { useVModel } from "@vueuse/core"
import { computed, getCurrentInstance, provide } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { TranscriptionKey } from "./context"

const props = withDefaults(defineProps<{
  segments: TranscriptionSegment[]
  currentTime?: number
  class?: HTMLAttributes["class"]
}>(), { currentTime: undefined })

const emit = defineEmits<{
  (e: "update:currentTime", time: number): void
  (e: "seek", time: number): void
}>()

const model = useVModel(props, "currentTime", emit, { defaultValue: 0, passive: true })
const currentTime = computed({
  get: () => model.value ?? 0,
  set: (time: number) => { model.value = time },
})

// Segments are clickable only when somebody listens for `seek` or `update:currentTime`.
const vnodeProps = getCurrentInstance()?.vnode.props ?? {}
const seekable = "onSeek" in vnodeProps || "onUpdate:currentTime" in vnodeProps

provide(TranscriptionKey, {
  segments: computed(() => props.segments),
  currentTime,
  onSeek: seekable
    ? (time: number) => {
        currentTime.value = time
        emit("seek", time)
      }
    : undefined,
})
</script>

<template>
  <div
    data-slot="ai-transcription"
    :class="cn('flex flex-wrap gap-x-1 gap-y-0.5 text-[15px] leading-[1.9]', props.class)"
  >
    <template v-for="(segment, index) in props.segments" :key="`${segment.startSecond}-${segment.endSecond}`">
      <slot v-if="segment.text.trim()" :segment="segment" :index="index" />
    </template>
  </div>
</template>
