// packages/vue/registry/components/ai/web-preview/WebPreviewConsole.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { ChevronDownIcon } from "@lucide/vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/registry/edmi/ui/collapsible"
import { useWebPreviewContext } from "./context"

type LogLevel = "log" | "warn" | "error"

interface ConsoleLog {
  level: LogLevel
  message: string
  timestamp: Date
}

const props = withDefaults(defineProps<{
  logs?: ConsoleLog[]
  class?: HTMLAttributes["class"]
}>(), {
  logs: () => [],
})

const context = useWebPreviewContext()

function levelClass(level: LogLevel) {
  if (level === "error")
    return "text-destructive-text"
  if (level === "warn")
    return "text-warning-text"
  return "text-foreground"
}
</script>

<template>
  <Collapsible
    data-slot="ai-web-preview-console"
    :class="cn('border-t border-border bg-card font-mono text-[11.5px] leading-[1.8]', props.class)"
    :open="context.consoleOpen.value"
    @update:open="context.setConsoleOpen"
  >
    <CollapsibleTrigger class="group/ai-console flex w-full items-center justify-between px-3 pt-2 pb-1 text-left font-mono text-[11px] font-medium tracking-[0.8px] text-muted-foreground uppercase outline-none focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-ring">
      Console
      <ChevronDownIcon class="size-3.5 transition-transform duration-200 group-data-[state=open]/ai-console:rotate-180" />
    </CollapsibleTrigger>
    <CollapsibleContent class="overflow-hidden">
      <div class="max-h-48 overflow-y-auto px-3 pb-2">
        <p v-if="!props.logs.length" class="text-muted-foreground">
          No console output
        </p>
        <template v-else>
          <div
            v-for="(log, index) in props.logs"
            :key="`${log.timestamp.getTime?.() ?? index}-${index}`"
            :class="levelClass(log.level)"
          >
            <span class="text-muted-foreground">{{ log.timestamp.toLocaleTimeString([], { hour12: false }) }}</span>
            {{ " " }}{{ log.level.padEnd(4, " ") }} {{ log.message }}
          </div>
        </template>
        <slot />
      </div>
    </CollapsibleContent>
  </Collapsible>
</template>

// packages/svelte/src/lib/registry/ai/web-preview/web-preview-console.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import * as Collapsible from "$lib/registry/ui/collapsible/index.js";
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import { useWebPreviewContext } from "./use-web-preview.svelte.js";

	type LogLevel = "log" | "warn" | "error";

	let {
		logs = [],
		class: className,
		children,
	}: {
		logs?: { level: LogLevel; message: string; timestamp: Date }[];
		class?: string;
		children?: Snippet;
	} = $props();

	const preview = useWebPreviewContext();

	function levelClass(level: LogLevel) {
		if (level === "error") return "text-destructive-text";
		if (level === "warn") return "text-warning-text";
		return "text-foreground";
	}
</script>

<Collapsible.Root
	open={preview.consoleOpen}
	onOpenChange={(value) => (preview.consoleOpen = value)}
	data-slot="ai-web-preview-console"
	class={cn("border-t border-border bg-card font-mono text-[11.5px] leading-[1.8]", className)}
>
	<Collapsible.Trigger
		class="group/ai-console flex w-full items-center justify-between px-3 pt-2 pb-1 text-left font-mono text-[11px] font-medium tracking-[0.8px] text-muted-foreground uppercase outline-none focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-ring"
	>
		Console
		<IconPlaceholder
			lucide="ChevronDownIcon"
			tabler="IconChevronDown"
			hugeicons="ArrowDown01Icon"
			phosphor="CaretDownIcon"
			remixicon="RiArrowDownSLine"
			class="size-3.5 transition-transform duration-200 group-data-[state=open]/ai-console:rotate-180"
		/>
	</Collapsible.Trigger>
	<Collapsible.Content class="overflow-hidden">
		<div class="max-h-48 overflow-y-auto px-3 pb-2">
			{#if logs.length === 0}
				<p class="text-muted-foreground">No console output</p>
			{:else}
				{#each logs as log, index (`${log.timestamp.getTime()}-${index}`)}
					<div class={levelClass(log.level)}>
						<span class="text-muted-foreground"
							>{log.timestamp.toLocaleTimeString([], { hour12: false })}</span
						>
						{log.level.padEnd(4, " ")}
						{log.message}
					</div>
				{/each}
			{/if}
			{@render children?.()}
		</div>
	</Collapsible.Content>
</Collapsible.Root>
