// packages/vue/registry/components/ai/web-preview/WebPreviewBody.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { IframeHTMLAttributes, VNodeChild } from "vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { useWebPreviewContext } from "./context"

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: IframeHTMLAttributes["class"]
  src?: string
}>()

defineSlots<{
  loading?: () => VNodeChild
}>()

const { url } = useWebPreviewContext()

const frameSrc = computed(() => (props.src ?? url.value) || undefined)
</script>

<template>
  <div data-slot="ai-web-preview-body" class="relative min-h-0 flex-1 bg-background">
    <iframe
      :class="cn('size-full', props.class)"
      sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-presentation"
      :src="frameSrc"
      title="Preview"
      v-bind="$attrs"
    />
    <slot name="loading" />
  </div>
</template>

// packages/svelte/src/lib/registry/ai/web-preview/web-preview-body.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLIframeAttributes } from "svelte/elements";
	import { useWebPreviewContext } from "./use-web-preview.svelte.js";

	let {
		class: className,
		src,
		loading,
		...restProps
	}: HTMLIframeAttributes & {
		/** Rendered over the frame, e.g. a spinner while the preview is generated. */
		loading?: Snippet;
	} = $props();

	const preview = useWebPreviewContext();
	const frameSrc = $derived((src ?? preview.url) || undefined);
</script>

<div data-slot="ai-web-preview-body" class="relative min-h-0 flex-1 bg-background">
	<iframe
		class={cn("size-full", className)}
		sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-presentation"
		src={frameSrc}
		title="Preview"
		{...restProps}
	></iframe>
	{@render loading?.()}
</div>
