// packages/svelte/src/lib/registry/ai/sources/source.svelte
<!-- Derived from Svelte AI Elements (MIT), modified for Edmi UI. -->
<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { cn } from "$lib/utils.js";
	import type { HTMLAnchorAttributes } from "svelte/elements";

	let { class: className, href, title, children, ...restProps }: HTMLAnchorAttributes = $props();

	const host = $derived.by(() => {
		if (!href) return undefined;
		try {
			return new URL(href).hostname.replace(/^www\./, "");
		} catch {
			return undefined;
		}
	});
</script>

<a
	data-slot="ai-source"
	class={cn("flex items-center gap-2 text-foreground", className)}
	{href}
	rel="noreferrer"
	target="_blank"
	{...restProps}
>
	{#if children}
		{@render children()}
	{:else}
		<IconPlaceholder
			lucide="GlobeIcon"
			tabler="IconWorld"
			hugeicons="Globe02Icon"
			phosphor="GlobeIcon"
			remixicon="RiGlobalLine"
			class="size-3.5 shrink-0 text-muted-foreground"
		/>
		<span class="underline underline-offset-[3px]">{title}</span>
		{#if host}
			<span class="font-mono text-[11.5px] text-muted-foreground">{host}</span>
		{/if}
	{/if}
</a>

// packages/vue/registry/components/ai/sources/Source.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { GlobeIcon } from "@lucide/vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"

const props = defineProps<{
  href?: string
  title?: string
  class?: HTMLAttributes["class"]
}>()

const host = computed(() => {
  if (!props.href)
    return undefined
  try {
    return new URL(props.href).hostname.replace(/^www\./, "")
  }
  catch {
    return undefined
  }
})
</script>

<template>
  <a
    data-slot="ai-source"
    :class="cn('flex items-center gap-2 text-foreground', props.class)"
    :href="href"
    rel="noreferrer"
    target="_blank"
  >
    <slot>
      <GlobeIcon class="size-3.5 shrink-0 text-muted-foreground" />
      <span class="underline underline-offset-[3px]">{{ title }}</span>
      <span v-if="host" class="font-mono text-[11.5px] text-muted-foreground">{{ host }}</span>
    </slot>
  </a>
</template>
