// packages/svelte/src/lib/registry/ai/test-results/test.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";
	import TestDuration from "./test-duration.svelte";
	import TestName from "./test-name.svelte";
	import TestStatus from "./test-status.svelte";
	import { setTestContext, type TestStatusType } from "./use-test-results.svelte.js";

	let {
		ref = $bindable(null),
		name,
		status,
		duration,
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		name: string;
		status: TestStatusType;
		duration?: number;
	} = $props();

	setTestContext({
		get name() {
			return name;
		},
		get status() {
			return status;
		},
		get duration() {
			return duration;
		},
	});
</script>

<div
	bind:this={ref}
	data-slot="ai-test"
	data-status={status}
	class={cn("flex flex-wrap items-center gap-x-2 py-[5px] text-[12.5px]", className)}
	{...restProps}
>
	{#if children}
		{@render children()}
	{:else}
		<TestStatus />
		<TestName />
		{#if duration !== undefined}
			<TestDuration />
		{/if}
	{/if}
</div>

// packages/vue/registry/components/ai/test-results/Test.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import type { TestStatusType } from "./context"
import { computed, provide, reactive } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { TestContextKey } from "./context"
import TestDuration from "./TestDuration.vue"
import TestName from "./TestName.vue"
import TestStatus from "./TestStatus.vue"

const props = defineProps<{
  name: string
  status: TestStatusType
  duration?: number
  class?: HTMLAttributes["class"]
}>()

const context = reactive({
  name: computed(() => props.name),
  status: computed(() => props.status),
  duration: computed(() => props.duration),
})

provide(TestContextKey, context)
</script>

<template>
  <div
    data-slot="ai-test"
    :data-status="props.status"
    :class="cn('flex flex-wrap items-center gap-x-2 py-[5px] text-[12.5px]', props.class)"
  >
    <slot>
      <TestStatus />
      <TestName />
      <TestDuration v-if="props.duration !== undefined" />
    </slot>
  </div>
</template>
