// packages/vue/registry/ui/kanban-column/KanbanItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { ArrowUpRightIcon } from '@lucide/vue'
import { inject } from 'vue'
import { Card } from '@/registry/edmi/ui/card'
import { cn } from '@/registry/edmi/lib/utils'
import type { Elevation } from '@/registry/edmi/ui/elevation'

const props = withDefaults(defineProps<{
  /** ✦ depth of this card; defaults to the column's `elevation` */
  elevation?: Elevation
  class?: HTMLAttributes['class']
  title: string
  description?: string
  /** Dims the card (not yet reachable). */
  disabled?: boolean
}>(), { elevation: undefined })

const column = inject<{ elevation?: Elevation } | null>('kanbanColumn', null)
// Slots: `icon` (leading), `action` (trailing; defaults to an arrow up-right).
</script>

<template>
  <Card
    :elevation="props.elevation ?? column?.elevation"
    data-slot="kanban-item"
    :data-disabled="disabled ? '' : undefined"
    :class="cn('flex-row items-center gap-2.5 px-3 py-2.5 data-[disabled]:opacity-60', props.class)"
  >
    <span
      v-if="$slots.icon"
      class="grid size-7 shrink-0 place-items-center rounded-lg border border-border bg-muted [&_svg]:size-3.5"
    >
      <slot name="icon" />
    </span>
    <div class="min-w-0 flex-1">
      <div class="text-[13px] font-medium">{{ title }}</div>
      <div v-if="description" class="text-[11px] text-muted-foreground">{{ description }}</div>
    </div>
    <span class="text-muted-foreground">
      <slot name="action"><ArrowUpRightIcon class="size-[13px]" /></slot>
    </span>
  </Card>
</template>

// packages/svelte/src/lib/registry/ui/kanban-column/kanban-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import { Card } from "$lib/registry/ui/card/index.js";
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import type { ComponentProps, Snippet } from "svelte";
	import type { Elevation } from "$lib/registry/ui/elevation/index.js";
	import { getKanbanColumnCtx } from "./kanban-column.svelte";

	let {
		class: className,
		title,
		description,
		icon,
		action,
		disabled,
		elevation = "auto",
		...restProps
	}: Omit<ComponentProps<typeof Card>, "title" | "children"> & {
		title: string;
		description?: string;
		/** Leading icon (an `IconPlaceholder`). */
		icon?: Snippet;
		/** Trailing element; defaults to an arrow up-right. */
		action?: Snippet;
		/** Dims the card (not yet reachable). */
		disabled?: boolean;
		/** ✦ depth of this card; defaults to the column's `elevation`. */
		elevation?: Elevation;
	} = $props();

	const ctx = getKanbanColumnCtx();
</script>

<Card
	data-slot="kanban-item"
	elevation={elevation !== "auto" ? elevation : ctx?.elevation}
	data-disabled={disabled ? "" : undefined}
	class={cn("flex-row items-center gap-2.5 px-3 py-2.5 data-[disabled]:opacity-60", className)}
	{...restProps}
>
	{#if icon}
		<span class="grid size-7 shrink-0 place-items-center rounded-lg border border-border bg-muted [&_svg]:size-3.5">
			{@render icon()}
		</span>
	{/if}
	<div class="min-w-0 flex-1">
		<div class="text-[13px] font-medium">{title}</div>
		{#if description}
			<div class="text-[11px] text-muted-foreground">{description}</div>
		{/if}
	</div>
	<span class="text-muted-foreground">
		{#if action}
			{@render action()}
		{:else}
			<IconPlaceholder
				lucide="ArrowUpRightIcon"
				tabler="IconArrowUpRight"
				hugeicons="ArrowUpRightIcon"
				phosphor="ArrowUpRightIcon"
				remixicon="RiArrowRightUpLine"
				class="size-[13px]"
			/>
		{/if}
	</span>
</Card>
