// packages/svelte/src/lib/registry/ai/voice-selector/voice-selector-item.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { CommandItem } from "$lib/registry/ui/command/index.js";
	import { cn } from "$lib/utils.js";
	import type { ComponentProps } from "svelte";
	import { useVoiceSelector } from "./use-voice-selector.svelte.js";

	// A two-line row: lay out `VoiceSelectorPreview`, then a `VoiceSelectorDetails` block. The item whose `value`
	// equals the selector value shows the check; selecting sets the value and closes unless `onSelect` is used.
	let {
		value,
		onSelect,
		class: className,
		children,
		...restProps
	}: ComponentProps<typeof CommandItem> = $props();

	const ctx = useVoiceSelector();
</script>

<CommandItem
	{value}
	data-checked={value !== undefined && value === ctx.value}
	class={cn("h-auto items-start p-2 whitespace-normal", className)}
	onSelect={() => {
		if (onSelect) {
			onSelect();
			return;
		}
		ctx.setValue(value);
		ctx.setOpen(false);
	}}
	{...restProps}
>
	{@render children?.()}
</CommandItem>

// packages/vue/registry/components/ai/voice-selector/VoiceSelectorItem.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { Check } from "@lucide/vue"
import { cn } from "@/registry/edmi/lib/utils"
import { CommandItem } from "@/registry/edmi/ui/command"
import { useVoiceSelector } from "./context"

// A two-line row: lay out `VoiceSelectorPreview`, then a `VoiceSelectorDetails` block. The item whose `value`
// equals the selector value shows the check; selecting sets the value and closes the dialog.
const props = defineProps<{
  /** The voice id. */
  value: string
  class?: HTMLAttributes["class"]
}>()

const { value: selected, setValue, setOpen } = useVoiceSelector("VoiceSelectorItem")

function handleSelect() {
  setValue(props.value)
  setOpen(false)
}
</script>

<template>
  <CommandItem
    :value="props.value"
    :data-checked="props.value === selected"
    :class="cn('h-auto items-start p-2 whitespace-normal', props.class)"
    @select="handleSelect"
  >
    <slot />
    <Check class="ml-auto opacity-0 group-data-[checked=true]/command-item:opacity-100" />
  </CommandItem>
</template>
