// packages/vue/registry/components/ai/artifact-card/ArtifactCardActions.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { ChevronDown } from "@lucide/vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Button } from "@/registry/edmi/ui/button"
import { ButtonGroup } from "@/registry/edmi/ui/button-group"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/registry/edmi/ui/dropdown-menu"
import { useArtifactCardState } from "./context"

const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  /** Label of the primary half of the split button. */
  label?: string
}>(), {
  label: "Download",
})

const emit = defineEmits<{
  (e: "download"): void
}>()

const state = useArtifactCardState()
</script>

<template>
  <!-- The default slot holds `DropdownMenuItem`s for the chevron half; no chevron without them. -->
  <ButtonGroup
    v-if="state !== 'generating'"
    data-slot="ai-artifact-card-actions"
    :class="cn('shrink-0', props.class)"
  >
    <Button variant="secondary" size="sm" type="button" @click="emit('download')">
      {{ label }}
    </Button>
    <DropdownMenu v-if="$slots.default">
      <DropdownMenuTrigger as-child>
        <Button variant="secondary" size="icon-sm" type="button" aria-label="More download options">
          <ChevronDown class="size-3.5" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <slot />
      </DropdownMenuContent>
    </DropdownMenu>
  </ButtonGroup>
</template>

// packages/svelte/src/lib/registry/ai/artifact-card/artifact-card-actions.svelte
<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { Button } from "$lib/registry/ui/button/index.js";
	import { ButtonGroup } from "$lib/registry/ui/button-group/index.js";
	import * as DropdownMenu from "$lib/registry/ui/dropdown-menu/index.js";
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { getArtifactCardState } from "./use-artifact-card.svelte.js";

	let {
		label = "Download",
		onDownload,
		class: className,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		/** Label of the primary half of the split button. */
		label?: string;
		onDownload?: () => void;
		/** `DropdownMenu.Item`s for the chevron half (copy link, open, ...). No chevron without them. */
		children?: Snippet;
	} = $props();

	const card = getArtifactCardState();
</script>

<!-- Split Download button; hidden while the card is generating. -->
{#if card.state !== "generating"}
	<ButtonGroup data-slot="ai-artifact-card-actions" class={cn("shrink-0", className)} {...restProps}>
		<Button variant="secondary" size="sm" type="button" onclick={() => onDownload?.()}>
			{label}
		</Button>
		{#if children}
			<DropdownMenu.Root>
				<DropdownMenu.Trigger>
					{#snippet child({ props })}
						<Button
							{...props}
							variant="secondary"
							size="icon-sm"
							type="button"
							aria-label="More download options"
						>
							<IconPlaceholder
								lucide="ChevronDownIcon"
								tabler="IconChevronDown"
								hugeicons="ArrowDown01Icon"
								phosphor="CaretDownIcon"
								remixicon="RiArrowDownSLine"
								class="size-3.5"
							/>
						</Button>
					{/snippet}
				</DropdownMenu.Trigger>
				<DropdownMenu.Content align="end">
					{@render children()}
				</DropdownMenu.Content>
			</DropdownMenu.Root>
		{/if}
	</ButtonGroup>
{/if}
