// packages/svelte/src/lib/registry/ai/snippet/snippet-input.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import * as InputGroup from "$lib/registry/ui/input-group/index.js";
	import { cn } from "$lib/utils.js";
	import type { HTMLInputAttributes } from "svelte/elements";
	import { useSnippetContext } from "./use-snippet.svelte.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: Omit<HTMLInputAttributes, "value" | "readonly" | "type"> & { ref?: HTMLElement | null } = $props();

	const snippet = useSnippetContext();
</script>

<InputGroup.Input
	bind:ref
	class={cn("font-mono text-xs text-foreground", className)}
	readonly
	value={snippet.code}
	{...(restProps as Record<string, unknown>)}
/>

// packages/vue/registry/components/ai/snippet/SnippetInput.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { InputGroupInput } from "@/registry/edmi/ui/input-group"
import { useSnippetContext } from "./context"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const { code } = useSnippetContext("SnippetInput")
</script>

<template>
  <InputGroupInput
    :class="cn('font-mono text-xs text-foreground', props.class)"
    readonly
    :model-value="code"
  />
</template>
