// packages/svelte/src/lib/registry/ui/questionnaire/questionnaire-input.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLInputAttributes } from "svelte/elements";
	import { untrack } from "svelte";
	import { useElevation } from "$lib/registry/ui/elevation/index.js";
	import {
		type QuestionnaireInputType,
		getAnswerKeyShortcuts,
		getQuestionnaireItemContext,
		getQuestionnaireRootContext,
		hasInputValue,
	} from "./use-questionnaire.svelte.js";

	let {
		ref = $bindable(null),
		class: className,
		/** Fills the answer on mount and after a native form reset. */
		defaultValue = undefined,
		disabled: disabledProp = false,
		/** Controlled value. Use with `bind:value`. */
		value: valueProp = $bindable(undefined),
		type = "text",
		oninput,
		...restProps
	}: Omit<
		WithElementRef<HTMLInputAttributes, HTMLInputElement>,
		"type" | "form" | "name" | "disabled"
	> & {
		disabled?: boolean;
		defaultValue?: string | number;
		type?: QuestionnaireInputType;
	} = $props();

	const item = getQuestionnaireItemContext();
	const root = getQuestionnaireRootContext();
	const level = useElevation(() => root.elevation, "field");
	const inputElevation = {
		sunken: "border-sk-bd bg-sk-bg shadow-sunken",
		flat: "",
		raised: "border-transparent shadow-raised",
		floating: "border-transparent shadow-floating",
	};
	const answerId = $props.id();
	const initialDefaultFilled = untrack(() => hasInputValue(defaultValue));
	let uncontrolledValue = $state(untrack(() => String(defaultValue ?? "")));

	const controlled = $derived(valueProp !== undefined);
	const defaultFilled = $derived(hasInputValue(defaultValue));
	const disabled = $derived(item.disabled || disabledProp);
	const value = $derived(controlled ? String(valueProp ?? "") : uncontrolledValue);
	const filled = $derived(hasInputValue(value));
	const selected = $derived(item.selectedAnswerIds.includes(answerId));

	function handleInput(event: Event & { currentTarget: EventTarget & HTMLInputElement }) {
		const nextValue = event.currentTarget.value;
		oninput?.(event);
		if (controlled) valueProp = nextValue;
		else uncontrolledValue = nextValue;
		item.setAnswerSelectionFromInteraction(answerId, hasInputValue(nextValue));
	}

	$effect(() => item.registerAnswerSelection(answerId, initialDefaultFilled));

	$effect(() => {
		const element = ref;
		if (!element) return;
		return item.registerAnswerControl({
			disabled,
			element,
			id: answerId,
			ownDisabled: disabledProp,
			type: "input",
			value: "",
		});
	});

	$effect(() => {
		item.setAnswerDefault(answerId, defaultFilled);
	});

	// A host update clears the skipped state even when the answer stays filled.
	$effect(() => {
		void value;
		if (controlled) item.syncControlledAnswerSelection(answerId, filled);
	});

	$effect(() => {
		void item.resetVersion;
		untrack(() => {
			if (!controlled) uncontrolledValue = String(defaultValue ?? "");
		});
	});

	$effect(() => {
		if (!ref) return;
		// A native form reset restores `defaultValue`, so keep it in sync with the value we own.
		ref.defaultValue = String((controlled ? valueProp : defaultValue) ?? "");
	});
</script>

<div
	data-slot="questionnaire-input-wrapper"
	class="group/questionnaire-input relative w-full min-w-0"
>
	<input
		bind:this={ref}
		id={answerId}
		data-slot="questionnaire-input"
		aria-invalid={item.invalid || undefined}
		aria-keyshortcuts={getAnswerKeyShortcuts(null, !disabled && filled && selected)}
		data-disabled={disabled ? "" : undefined}
		data-empty={filled ? undefined : ""}
		data-filled={filled ? "" : undefined}
		data-invalid={item.invalid ? "" : undefined}
		{disabled}
		form={selected ? undefined : ""}
		name={selected ? item.name : undefined}
		{type}
		{value}
		class={cn(
			"h-12 w-full min-w-0 rounded-xl border border-border bg-card px-3.5 text-sm transition-colors outline-none focus-visible:border-ring focus-visible:shadow-[0_0_0_1px_var(--ring)] disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive",
			"placeholder:text-muted-foreground",
			inputElevation[level.current],
			className
		)}
		oninput={handleInput}
		{...restProps}
	/>
</div>

// packages/vue/registry/ui/questionnaire/QuestionnaireInput.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { QuestionnaireInputType } from "./useQuestionnaire"
import { computed, nextTick, onBeforeUnmount, ref, useId, watch } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { useElevation } from "@/registry/edmi/ui/elevation"
import {
  getAnswerKeyShortcuts,
  hasInputValue,
  injectQuestionnaireItemContext,
  injectQuestionnaireRootContext,
} from "./useQuestionnaire"

defineOptions({
  // The wrapper is the root element, so attributes have to reach the input.
  inheritAttrs: false,
})

const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  /** Fills the answer on mount and after a native form reset. */
  defaultValue?: string | number
  disabled?: boolean
  /** Controlled value. Use with `v-model`. */
  modelValue?: string | number
  type?: QuestionnaireInputType
}>(), {
  disabled: false,
  type: "text",
})

const emits = defineEmits<{
  "update:modelValue": [value: string]
}>()

const item = injectQuestionnaireItemContext()
const root = injectQuestionnaireRootContext()
const level = useElevation(() => root.elevation.value, "field")
const inputElevation = {
  sunken: "border-sk-bd bg-sk-bg shadow-sunken",
  flat: "",
  raised: "border-transparent shadow-raised",
  floating: "border-transparent shadow-floating",
}

const answerId = useId()
const inputElement = ref<HTMLInputElement | null>(null)
const initialDefaultFilled = hasInputValue(props.defaultValue)
const uncontrolledValue = ref(String(props.defaultValue ?? ""))

const controlled = computed(() => props.modelValue !== undefined)
const defaultFilled = computed(() => hasInputValue(props.defaultValue))
const disabled = computed(() => item.disabled.value || props.disabled)
// Vue re-applies `value` on every render, so the input always renders the value
// the questionnaire owns instead of an undefined binding that would clear it.
const value = computed(() =>
  controlled.value ? String(props.modelValue ?? "") : uncontrolledValue.value)
const filled = computed(() => hasInputValue(value.value))
const selected = computed(() => item.selectedAnswerIds.value.includes(answerId))

function syncValueElement() {
  if (inputElement.value && inputElement.value.value !== value.value) {
    inputElement.value.value = value.value
  }
}

function handleInput(event: Event) {
  const nextValue = (event.target as HTMLInputElement).value

  emits("update:modelValue", nextValue)

  if (controlled.value) {
    // The host owns the value, so restore whatever it kept.
    nextTick(syncValueElement)
    return
  }

  uncontrolledValue.value = nextValue
  item.setAnswerSelectionFromInteraction(answerId, hasInputValue(nextValue))
}

const unregisterSelection = item.registerAnswerSelection(answerId, initialDefaultFilled)

let unregisterControl: (() => void) | null = null

watch([inputElement, disabled, () => props.disabled], ([element]) => {
  unregisterControl?.()
  unregisterControl = null

  if (!element) {
    return
  }

  unregisterControl = item.registerAnswerControl({
    disabled: disabled.value,
    element,
    id: answerId,
    ownDisabled: props.disabled,
    type: "input",
    value: "",
  })
}, { flush: "post" })

watch(defaultFilled, (nextDefaultFilled) => {
  item.setAnswerDefault(answerId, nextDefaultFilled)
})

// Watching the value as well as `filled` lets a host update clear the skipped
// state even when the answer stays filled.
watch([value, filled], () => {
  if (controlled.value) {
    item.syncControlledAnswerSelection(answerId, filled.value)
  }
}, { immediate: true })

watch(item.resetVersion, () => {
  if (!controlled.value) {
    uncontrolledValue.value = String(props.defaultValue ?? "")
  }
})

watch([value, inputElement], () => {
  if (!inputElement.value) {
    return
  }

  // A native form reset restores `defaultValue`, so keep it in sync with the
  // value the questionnaire owns.
  inputElement.value.defaultValue = String(
    (controlled.value ? props.modelValue : props.defaultValue) ?? "",
  )
}, { flush: "post" })

onBeforeUnmount(() => {
  unregisterControl?.()
  unregisterControl = null
  unregisterSelection()
})
</script>

<template>
  <div
    data-slot="questionnaire-input-wrapper"
    class="group/questionnaire-input relative w-full min-w-0"
  >
    <input
      v-bind="$attrs"
      :id="answerId"
      ref="inputElement"
      data-slot="questionnaire-input"
      :aria-invalid="item.invalid.value || undefined"
      :aria-keyshortcuts="getAnswerKeyShortcuts(null, !disabled && filled && selected)"
      :data-disabled="disabled ? '' : undefined"
      :data-empty="filled ? undefined : ''"
      :data-filled="filled ? '' : undefined"
      :data-invalid="item.invalid.value ? '' : undefined"
      :disabled="disabled"
      :form="selected ? undefined : ''"
      :name="selected ? item.name.value : undefined"
      :type="props.type"
      :value="value"
      :class="cn(
        'h-12 w-full min-w-0 rounded-xl border border-border bg-card px-3.5 text-sm transition-colors outline-none focus-visible:border-ring focus-visible:shadow-[0_0_0_1px_var(--ring)] disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive',
        'placeholder:text-muted-foreground',
        inputElevation[level],
        props.class,
      )"
      @input="handleInput"
    >
  </div>
</template>
