// examples/vue/src/components/ui/menubar/Menubar.vue
<script setup lang="ts">
import type { MenubarRootEmits, MenubarRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import {
  MenubarRoot,
  useForwardPropsEmits,
} from "reka-ui"
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<MenubarRootProps & { class?: HTMLAttributes["class"], raised?: boolean }>(), { raised: false })
const emits = defineEmits<MenubarRootEmits>()

const delegatedProps = reactiveOmit(props, "class", "raised")

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <MenubarRoot
    v-slot="slotProps"
    data-slot="menubar"
    v-bind="forwarded"
    :class="
      cn(
      `flex items-center gap-0.5 rounded-[10px] border border-border bg-card p-[3px]`,
        props.raised && 'border-b-lip shadow-btn-outline',
        props.class,
      )
    "
  >
    <slot v-bind="slotProps" />
  </MenubarRoot>
</template>

// examples/svelte/src/lib/components/ui/menubar/menubar.svelte
<script lang="ts">
	import { Menubar as MenubarPrimitive } from "bits-ui";
	import { cn } from "#lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		raised = false,
		...restProps
	}: MenubarPrimitive.RootProps & {
		/** ✦ opt-in one-step 3D look for the bar. */
		raised?: boolean;
	} = $props();
</script>

<MenubarPrimitive.Root
	bind:ref
	data-slot="menubar"
	class={cn(
		"flex items-center gap-0.5 rounded-[10px] border border-border bg-card p-[3px]",
		raised && "border-b-lip shadow-btn-outline",
		className
	)}
	{...restProps}
/>
