// examples/layerbeat-svelte/src/lib/components/ui/leaderboard-podium/leaderboard-podium.svelte
<script lang="ts" module>
	export type PodiumAllocation = {
		label: string;
		/** Weight in percent (bars are proportional). */
		value: number;
		/** Any CSS color; defaults cycle `--chart-1…5`. */
		color?: string;
	};

	export type PodiumEntry = {
		rank: 1 | 2 | 3;
		name: string;
		/** Mono caption under the name, e.g. `$49.2K AUM · 412 holders`. */
		meta?: string;
		image?: string;
		/** Avatar initials; defaults to the first two letters of `name`. */
		initials?: string;
		href?: string;
		/** ✦ `variant="cards"`: mono ticker under the name. */
		symbol?: string;
		/** ✦ `variant="cards"`: mono creator, top right of the card. */
		creator?: string;
		/** ✦ `variant="cards"`: signed headline percentage, e.g. `+1.12%`. */
		change?: string;
		/** ✦ `variant="cards"`: series for the sparkline. */
		spark?: number[];
		/** ✦ `variant="cards"`: weights bar with legend. */
		allocation?: PodiumAllocation[];
		/** ✦ `variant="cards"`: footer stats. */
		aum?: string;
		holders?: string | number;
	};
</script>

<script lang="ts">
	import { Avatar, AvatarFallback, AvatarImage } from "#lib/components/ui/avatar/index.js";
	import { Badge } from "#lib/components/ui/badge/index.js";
	import { Card } from "#lib/components/ui/card/index.js";
	import { cn, type WithElementRef } from "#lib/utils.js";
	import type { HTMLOlAttributes } from "svelte/elements";
	import type { Elevation } from "#lib/components/ui/elevation/index.js";

	let {
		ref = $bindable(null),
		class: className,
		entries,
		elevation = "auto",
		variant = "podium",
		...restProps
	}: WithElementRef<Omit<HTMLOlAttributes, "children">, HTMLOListElement> & {
		entries: PodiumEntry[];
		/** ✦ depth of the cards (forwarded to each Card). */
		elevation?: Elevation;
		/** ✦ `podium` (default) or `cards`. */
		variant?: "podium" | "cards";
	} = $props();

	const isDown = (s: string) => /^[-−–]/.test(s.trim());
	const color = (c: string | undefined, i: number) => c ?? `var(--chart-${(i % 5) + 1})`;

	// `podium` (default): #1 raised in the middle (warning badge), #2 left and #3 right sit lower.
	// `cards` ✦: three equal stat cards in rank order (leaderboard board).
	const ordered = $derived(
		(variant === "cards" ? ([1, 2, 3] as const) : ([2, 1, 3] as const))
			.map((r) => entries.find((e) => e.rank === r))
			.filter((e): e is PodiumEntry => !!e)
	);

	function sparkPoints(data: number[], width = 150, height = 34) {
		const min = Math.min(...data);
		const span = Math.max(...data) - min || 1;
		const pad = 2;
		return data
			.map((v, i) => {
				const x = pad + (i / (data.length - 1)) * (width - pad * 2);
				const y = pad + (1 - (v - min) / span) * (height - pad * 2);
				return `${x.toFixed(1)},${y.toFixed(1)}`;
			})
			.join(" ");
	}
</script>

{#if variant === "cards"}
	<ol
		bind:this={ref}
		data-slot="leaderboard-podium"
		data-variant="cards"
		class={cn("grid gap-4 lg:grid-cols-3", className)}
		{...restProps}
	>
		{#each ordered as e (e.rank)}
			{@const down = e.change ? isDown(e.change) : false}
			<li>
				<Card {elevation} class="h-full gap-0 p-6">
					<div class="flex items-center justify-between text-[13px]">
						<span class="font-medium">No. {e.rank}</span>
						{#if e.creator}<span class="font-mono text-xs text-muted-foreground">{e.creator}</span>{/if}
					</div>
					<div class="mt-3 flex items-center gap-3">
						<Avatar class="size-11 rounded-xl after:rounded-xl">
							{#if e.image}<AvatarImage src={e.image} alt="" class="rounded-xl" />{/if}
							<AvatarFallback class="rounded-xl bg-muted font-mono text-sm text-foreground-2">
								{(e.initials ?? e.name.slice(0, 2)).toUpperCase()}
							</AvatarFallback>
						</Avatar>
						<div>
							{#if e.href}
								<a href={e.href} class="text-lg font-medium hover:underline">{e.name}</a>
							{:else}
								<div class="text-lg font-medium">{e.name}</div>
							{/if}
							{#if e.symbol}<div class="font-mono text-xs text-muted-foreground">{e.symbol}</div>{/if}
						</div>
					</div>
					{#if e.change}
						<div class="mt-4 flex items-end justify-between gap-3">
							<span class={cn("text-[30px] leading-none tracking-[-0.8px]", down ? "text-destructive-text" : "text-brand-text")}>
								{e.change}
							</span>
							{#if e.spark && e.spark.length > 1}
								<svg
									width="150"
									height="34"
									viewBox="0 0 150 34"
									fill="none"
									aria-hidden="true"
									class={cn("max-w-[45%]", down ? "text-destructive-text" : "text-success-text")}
								>
									<polyline
										points={sparkPoints(e.spark)}
										stroke="currentColor"
										stroke-width="1.6"
										stroke-linecap="round"
										stroke-linejoin="round"
									/>
								</svg>
							{/if}
						</div>
					{/if}
					{#if e.allocation?.length}
						<div class="mt-4">
							<div class="flex h-2 gap-[3px]" role="img" aria-label={e.allocation.map((s) => `${s.label} ${s.value}%`).join(", ")}>
								{#each e.allocation as s, i (s.label)}
									<span class="rounded-[3px]" style="flex: {s.value}; background: {color(s.color, i)}"></span>
								{/each}
							</div>
							<ul class="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-xs text-foreground-2">
								{#each e.allocation as s, i (s.label)}
									<li class="flex items-center gap-1.5">
										<span class="size-2 rounded-[2px]" style="background: {color(s.color, i)}"></span>
										<span class="font-mono">{s.label}</span>
										<b class="font-semibold text-foreground">{s.value}%</b>
									</li>
								{/each}
							</ul>
						</div>
					{/if}
					{#if e.aum !== undefined || e.holders !== undefined}
						<div class="mt-4 flex items-center gap-4 border-t border-border-2 pt-3.5 text-[13px] text-muted-foreground">
							{#if e.aum !== undefined}<span>AUM <b class="font-mono font-medium text-foreground">{e.aum}</b></span>{/if}
							{#if e.holders !== undefined}<span>Holders <b class="font-mono font-medium text-foreground">{e.holders}</b></span>{/if}
						</div>
					{/if}
				</Card>
			</li>
		{/each}
	</ol>
{:else}
	<ol bind:this={ref} data-slot="leaderboard-podium" class={cn("flex items-start gap-3", className)} {...restProps}>
		{#each ordered as e (e.rank)}
			<li class={cn("w-[200px]", e.rank !== 1 && "mt-6")}>
				<Card size="sm" {elevation} class="items-center gap-0 p-[18px] text-center">
					<Badge shape="number" variant={e.rank === 1 ? "warning" : "secondary"} class="rounded-full">#{e.rank}</Badge>
					<Avatar class="mt-3 size-11">
						{#if e.image}<AvatarImage src={e.image} alt="" />{/if}
						<AvatarFallback class="bg-linear-to-br from-info to-brand text-sm text-white">
							{(e.initials ?? e.name.slice(0, 2)).toUpperCase()}
						</AvatarFallback>
					</Avatar>
					{#if e.href}
						<a href={e.href} class="mt-2.5 font-semibold hover:underline">{e.name}</a>
					{:else}
						<div class="mt-2.5 font-semibold">{e.name}</div>
					{/if}
					{#if e.meta}<div class="mt-0.5 font-mono text-xs text-muted-foreground">{e.meta}</div>{/if}
				</Card>
			</li>
		{/each}
	</ol>
{/if}

// packages/react/registry/blocks/leaderboard-podium/leaderboard-podium.tsx
import { cn } from "cn";
import type * as React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/registry/edmi/ui/avatar";
import { Badge } from "@/registry/edmi/ui/badge";
import { Card } from "@/registry/edmi/ui/card";
import type { Elevation } from "@/registry/edmi/ui/elevation";

type PodiumAllocation = {
	label: string;
	/** Weight in percent (bars are proportional). */
	value: number;
	/** Any CSS color; defaults cycle `--chart-1…5`. */
	color?: string;
};

type PodiumEntry = {
	rank: 1 | 2 | 3;
	name: string;
	/** Mono caption under the name, e.g. `$49.2K AUM · 412 holders`. */
	meta?: string;
	image?: string;
	/** Avatar initials; defaults to the first two letters of `name`. */
	initials?: string;
	href?: string;
	/** ✦ `variant="cards"`: mono ticker under the name. */
	symbol?: string;
	/** ✦ `variant="cards"`: mono creator, top right of the card. */
	creator?: string;
	/** ✦ `variant="cards"`: signed headline percentage, e.g. `+1.12%`. */
	change?: string;
	/** ✦ `variant="cards"`: series for the sparkline. */
	spark?: number[];
	/** ✦ `variant="cards"`: weights bar with legend. */
	allocation?: PodiumAllocation[];
	/** ✦ `variant="cards"`: footer stats. */
	aum?: string;
	holders?: string | number;
};

const isDown = (s: string) => /^[-−–]/.test(s.trim());

function PodiumSpark({
	data,
	down,
	width = 150,
	height = 34,
}: {
	data: number[];
	down: boolean;
	width?: number;
	height?: number;
}) {
	if (data.length < 2) return null;
	const min = Math.min(...data);
	const span = Math.max(...data) - min || 1;
	const pad = 2;
	const points = data
		.map((v, i) => {
			const x = pad + (i / (data.length - 1)) * (width - pad * 2);
			const y = pad + (1 - (v - min) / span) * (height - pad * 2);
			return `${x.toFixed(1)},${y.toFixed(1)}`;
		})
		.join(" ");
	return (
		<svg
			width={width}
			height={height}
			viewBox={`0 0 ${width} ${height}`}
			fill="none"
			aria-hidden="true"
			className={cn(
				"max-w-[45%]",
				down ? "text-destructive-text" : "text-success-text",
			)}
		>
			<polyline
				points={points}
				stroke="currentColor"
				strokeWidth="1.6"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

// `podium` (default): top three, #1 raised in the middle (warning badge), #2 left and #3 right sit lower.
// `cards` ✦: three equal stat cards in rank order (leaderboard board): creator, name, headline change,
// sparkline, allocation bar and AUM / holders.
function LeaderboardPodium({
	className,
	entries,
	elevation,
	variant = "podium",
	...props
}: Omit<React.ComponentProps<"ol">, "children"> & {
	entries: PodiumEntry[];
	/** ✦ depth of the cards (forwarded to each Card). */
	elevation?: Elevation;
	/** ✦ `podium` (default) or `cards`. */
	variant?: "podium" | "cards";
}) {
	const by = (r: number) => entries.find((e) => e.rank === r);
	if (variant === "cards") {
		const sorted = [by(1), by(2), by(3)].filter((e): e is PodiumEntry => !!e);
		return (
			<ol
				data-slot="leaderboard-podium"
				data-variant="cards"
				className={cn("grid gap-4 lg:grid-cols-3", className)}
				{...props}
			>
				{sorted.map((e) => {
					const down = e.change ? isDown(e.change) : false;
					return (
						<li key={e.rank}>
							<Card elevation={elevation} className="h-full gap-0 p-6">
								<div className="flex items-center justify-between text-[13px]">
									<span className="font-medium">No. {e.rank}</span>
									{e.creator ? (
										<span className="font-mono text-xs text-muted-foreground">
											{e.creator}
										</span>
									) : null}
								</div>
								<div className="mt-3 flex items-center gap-3">
									<Avatar className="size-11 rounded-xl after:rounded-xl">
										{e.image ? (
											<AvatarImage
												src={e.image}
												alt=""
												className="rounded-xl"
											/>
										) : null}
										<AvatarFallback className="rounded-xl bg-muted font-mono text-sm text-foreground-2">
											{(e.initials ?? e.name.slice(0, 2)).toUpperCase()}
										</AvatarFallback>
									</Avatar>
									<div>
										{e.href ? (
											<a
												href={e.href}
												className="text-lg font-medium hover:underline"
											>
												{e.name}
											</a>
										) : (
											<div className="text-lg font-medium">{e.name}</div>
										)}
										{e.symbol ? (
											<div className="font-mono text-xs text-muted-foreground">
												{e.symbol}
											</div>
										) : null}
									</div>
								</div>
								{e.change ? (
									<div className="mt-4 flex items-end justify-between gap-3">
										<span
											className={cn(
												"text-[30px] leading-none tracking-[-0.8px]",
												down ? "text-destructive-text" : "text-brand-text",
											)}
										>
											{e.change}
										</span>
										{e.spark ? (
											<PodiumSpark data={e.spark} down={down} />
										) : null}
									</div>
								) : null}
								{e.allocation?.length ? (
									<div className="mt-4">
										<div
											className="flex h-2 gap-[3px]"
											role="img"
											aria-label={e.allocation
												.map((s) => `${s.label} ${s.value}%`)
												.join(", ")}
										>
											{e.allocation.map((s, i) => (
												<span
													key={s.label}
													className="rounded-[3px]"
													style={{
														flex: s.value,
														background:
															s.color ?? `var(--chart-${(i % 5) + 1})`,
													}}
												/>
											))}
										</div>
										<ul className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-xs text-foreground-2">
											{e.allocation.map((s, i) => (
												<li key={s.label} className="flex items-center gap-1.5">
													<span
														className="size-2 rounded-[2px]"
														style={{
															background:
																s.color ?? `var(--chart-${(i % 5) + 1})`,
														}}
													/>
													<span className="font-mono">{s.label}</span>
													<b className="font-semibold text-foreground">
														{s.value}%
													</b>
												</li>
											))}
										</ul>
									</div>
								) : null}
								{e.aum !== undefined || e.holders !== undefined ? (
									<div className="mt-4 flex items-center gap-4 border-t border-border-2 pt-3.5 text-[13px] text-muted-foreground">
										{e.aum !== undefined ? (
											<span>
												AUM{" "}
												<b className="font-mono font-medium text-foreground">
													{e.aum}
												</b>
											</span>
										) : null}
										{e.holders !== undefined ? (
											<span>
												Holders{" "}
												<b className="font-mono font-medium text-foreground">
													{e.holders}
												</b>
											</span>
										) : null}
									</div>
								) : null}
							</Card>
						</li>
					);
				})}
			</ol>
		);
	}
	const ordered = [by(2), by(1), by(3)].filter((e): e is PodiumEntry => !!e);
	return (
		<ol
			data-slot="leaderboard-podium"
			className={cn("flex items-start gap-3", className)}
			{...props}
		>
			{ordered.map((e) => (
				<li key={e.rank} className={cn("w-[200px]", e.rank !== 1 && "mt-6")}>
					<Card
						size="sm"
						elevation={elevation}
						className="items-center gap-0 p-[18px] text-center"
					>
						<Badge
							shape="number"
							variant={e.rank === 1 ? "warning" : "secondary"}
							className="rounded-full"
						>
							#{e.rank}
						</Badge>
						<Avatar className="mt-3 size-11">
							{e.image ? <AvatarImage src={e.image} alt="" /> : null}
							<AvatarFallback className="bg-linear-to-br from-info to-brand text-sm text-white">
								{(e.initials ?? e.name.slice(0, 2)).toUpperCase()}
							</AvatarFallback>
						</Avatar>
						{e.href ? (
							<a href={e.href} className="mt-2.5 font-semibold hover:underline">
								{e.name}
							</a>
						) : (
							<div className="mt-2.5 font-semibold">{e.name}</div>
						)}
						{e.meta ? (
							<div className="mt-0.5 font-mono text-xs text-muted-foreground">
								{e.meta}
							</div>
						) : null}
					</Card>
				</li>
			))}
		</ol>
	);
}

export type { PodiumAllocation, PodiumEntry };
export { LeaderboardPodium };
