// packages/vue/registry/components/ai/canvas/Canvas.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { FlowEmits, FlowProps } from "@vue-flow/core"
import { Background } from "@vue-flow/background"
import { VueFlow } from "@vue-flow/core"
import { useForwardPropsEmits } from "reka-ui"
import { computed, useSlots } from "vue"
import "@vue-flow/core/dist/style.css"

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<FlowProps>(), {
  deleteKeyCode: () => ["Backspace", "Delete"],
  fitViewOnInit: true,
  panOnDrag: false,
  panOnScroll: true,
  selectNodesOnDrag: true,
  zoomOnDoubleClick: false,
})

const emits = defineEmits<FlowEmits>()
const slots = useSlots()
// Every slot except the default one is handed to Vue Flow as is (#node-<type>, #edge-<type>, ...).
const forwardedSlotNames = computed(() => Object.keys(slots).filter((n) => n !== "default"))
const forwarded = useForwardPropsEmits(props, emits)
</script>

<template>
  <!--
    Workflow surface: dotted --input dots on --background. Edge, selection and connection colors are
    mapped to Edmi tokens here because Vue Flow ships its defaults as plain colors.
  -->
  <VueFlow
    data-slot="ai-canvas"
    v-bind="{ ...$attrs, ...forwarded }"
    class="bg-background"
  >
    <Background :gap="18" :size="1" pattern-color="var(--input)" bg-color="var(--background)" />

    <!-- Forward the other slots as they are: #node-<type>, #edge-<type>, #connection-line, #zoom-pane. -->
    <template v-for="name in forwardedSlotNames" :key="name" #[name]="slotData">
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <slot />
  </VueFlow>
</template>

<style>
/* Vue Flow ships its defaults as plain colors; map them to Edmi tokens (specificity 0,2,0 beats the library). */
[data-slot="ai-canvas"] .vue-flow__edge-path {
  stroke: var(--muted-foreground);
  stroke-width: 1.6;
}
[data-slot="ai-canvas"] .vue-flow__edge.selected .vue-flow__edge-path {
  stroke: var(--foreground);
}
[data-slot="ai-canvas"] .vue-flow__connection-path {
  stroke: var(--ring);
  stroke-width: 1.6;
}
[data-slot="ai-canvas"] .vue-flow__selection,
[data-slot="ai-canvas"] .vue-flow__nodesselection-rect {
  border: 1px solid var(--ring);
  background: var(--ring-soft);
}
</style>

// packages/react/registry/components/ai/canvas.tsx
// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
import type { ReactFlowProps } from "@xyflow/react";
import { Background, BackgroundVariant, ReactFlow } from "@xyflow/react";
import { cn } from "cn";
import type { CSSProperties, ReactNode } from "react";

import "@xyflow/react/dist/style.css";

export type CanvasProps = ReactFlowProps & {
	children?: ReactNode;
};

const deleteKeyCode = ["Backspace", "Delete"];

/** xyflow reads these variables; mapping them to Edmi tokens keeps every mode and theme in sync. */
const tokenVars = {
	"--xy-edge-stroke-default": "var(--muted-foreground)",
	"--xy-edge-stroke-selected-default": "var(--foreground)",
	"--xy-edge-stroke-width-default": "1.6",
	"--xy-connectionline-stroke-default": "var(--ring)",
	"--xy-connectionline-stroke-width-default": "1.6",
	"--xy-background-color-default": "var(--background)",
	"--xy-selection-background-color-default": "var(--ring-soft)",
	"--xy-selection-border-default": "1px solid var(--ring)",
	"--xy-attribution-background-color-default": "var(--card)",
} as CSSProperties;

/** Workflow surface: dotted `--input` dots on `--background`, pan and zoom, fit view on load. */
export const Canvas = ({
	children,
	className,
	style,
	...props
}: CanvasProps) => (
	<ReactFlow
		data-slot="ai-canvas"
		className={cn("bg-background", className)}
		deleteKeyCode={deleteKeyCode}
		fitView
		panOnDrag={false}
		panOnScroll
		selectionOnDrag={true}
		style={{ ...tokenVars, ...style }}
		zoomOnDoubleClick={false}
		{...props}
	>
		<Background
			color="var(--input)"
			gap={18}
			size={1}
			variant={BackgroundVariant.Dots}
		/>
		{children}
	</ReactFlow>
);
