// packages/svelte/src/lib/registry/ai/confirmation/confirmation.svelte
<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	import { cn } from "$lib/utils.js";
	import { Alert } from "$lib/registry/ui/alert/index.js";
	import type { Elevation } from "$lib/registry/ui/elevation/index.js";
	import type { ToolUIPart } from "ai";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { setConfirmationContext, type ToolUIPartApproval } from "./use-confirmation.svelte.js";

	let {
		class: className,
		approval,
		state,
		elevation = "auto",
		icon,
		children,
		...restProps
	}: Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
		approval?: ToolUIPartApproval;
		state: ToolUIPart["state"];
		/** ✦ depth of the action buttons (they inherit it, each can override). The alert itself stays flat. */
		elevation?: Elevation;
		/** Leading icon of the request. Defaults to a shield. */
		icon?: Snippet;
		children?: Snippet;
	} = $props();

	setConfirmationContext({
		get approval() {
			return approval;
		},
		get state() {
			return state;
		},
		get elevation() {
			return elevation;
		},
	});

	const hidden = $derived(!approval || state === "input-streaming" || state === "input-available");
</script>

{#if !hidden}
	<!-- Request = warning alert with Approve / Reject; once answered it collapses to a plain status line. -->
	{#if state === "approval-requested"}
		<Alert data-slot="ai-confirmation" data-state={state} variant="warning" class={className} {...restProps}>
			{#if icon}
				{@render icon()}
			{:else}
				<IconPlaceholder
					lucide="ShieldIcon"
					tabler="IconShield"
					hugeicons="ShieldIcon"
					phosphor="ShieldIcon"
					remixicon="RiShieldLine"
				/>
			{/if}
			{@render children?.()}
		</Alert>
	{:else}
		<div
			data-slot="ai-confirmation"
			data-state={state}
			class={cn("flex items-center gap-2 text-[13.5px]", className)}
			{...restProps}
		>
			{@render children?.()}
		</div>
	{/if}
{/if}

// packages/react/registry/components/ai/confirmation.tsx
"use client";

import type { ToolUIPart } from "ai";
import { cn } from "cn";
import type { ComponentProps, ReactNode } from "react";
import { createContext, useContext, useMemo } from "react";
import { IconPlaceholder } from "@/edmi/icon-placeholder";
import { Alert } from "@/registry/edmi/ui/alert";
import { Button } from "@/registry/edmi/ui/button";
import type { Elevation } from "@/registry/edmi/ui/elevation";

type ToolUIPartApproval =
	| {
			id: string;
			approved?: never;
			reason?: never;
	  }
	| {
			id: string;
			approved: boolean;
			reason?: string;
	  }
	| undefined;

interface ConfirmationContextValue {
	approval: ToolUIPartApproval;
	state: ToolUIPart["state"];
	elevation: Elevation | undefined;
}

const ConfirmationContext = createContext<ConfirmationContextValue | null>(
	null,
);

const useConfirmation = () => {
	const context = useContext(ConfirmationContext);

	if (!context) {
		throw new Error("Confirmation components must be used within Confirmation");
	}

	return context;
};

export type ConfirmationProps = Omit<
	ComponentProps<typeof Alert>,
	"variant"
> & {
	approval?: ToolUIPartApproval;
	state: ToolUIPart["state"];
	/** ✦ depth of the action buttons (they inherit it, each can override). The alert itself stays flat. */
	elevation?: Elevation;
	/** Leading icon of the request. Defaults to a shield. */
	icon?: ReactNode;
};

/**
 * Request = warning alert with Approve / Reject. Once answered it collapses to a plain status line
 * (green check for approved, muted cross for rejected), as on board AI 02.
 */
export const Confirmation = ({
	className,
	approval,
	state,
	elevation,
	icon,
	children,
	...props
}: ConfirmationProps) => {
	const contextValue = useMemo(
		() => ({ approval, elevation, state }),
		[approval, elevation, state],
	);

	if (!approval || state === "input-streaming" || state === "input-available") {
		return null;
	}

	if (state !== "approval-requested") {
		return (
			<ConfirmationContext.Provider value={contextValue}>
				<div
					data-slot="ai-confirmation"
					data-state={state}
					className={cn("flex items-center gap-2 text-[13.5px]", className)}
					{...(props as ComponentProps<"div">)}
				>
					{children}
				</div>
			</ConfirmationContext.Provider>
		);
	}

	return (
		<ConfirmationContext.Provider value={contextValue}>
			<Alert
				data-slot="ai-confirmation"
				data-state={state}
				variant="warning"
				className={className}
				{...props}
			>
				{icon ?? (
					<IconPlaceholder
						lucide="ShieldIcon"
						tabler="IconShield"
						hugeicons="ShieldIcon"
						phosphor="ShieldIcon"
						remixicon="RiShieldLine"
					/>
				)}
				{children}
			</Alert>
		</ConfirmationContext.Provider>
	);
};

export type ConfirmationTitleProps = ComponentProps<"div">;

export const ConfirmationTitle = ({
	className,
	...props
}: ConfirmationTitleProps) => {
	const { state } = useConfirmation();
	return (
		<div
			data-slot="ai-confirmation-title"
			className={cn(
				state === "approval-requested"
					? "col-start-2 font-medium text-foreground"
					: "flex items-center gap-2",
				className,
			)}
			{...props}
		/>
	);
};

export type ConfirmationDescriptionProps = ComponentProps<"div">;

/** ✦ Muted second line under the request title (only while the request is open). */
export const ConfirmationDescription = ({
	className,
	...props
}: ConfirmationDescriptionProps) => {
	const { state } = useConfirmation();
	if (state !== "approval-requested") {
		return null;
	}
	return (
		<div
			data-slot="ai-confirmation-description"
			className={cn("col-start-2 text-[13px] text-foreground-2", className)}
			{...props}
		/>
	);
};

export interface ConfirmationRequestProps {
	children?: ReactNode;
}

export const ConfirmationRequest = ({ children }: ConfirmationRequestProps) => {
	const { state } = useConfirmation();

	// Only show when approval is requested
	if (state !== "approval-requested") {
		return null;
	}

	return children;
};

export interface ConfirmationAcceptedProps {
	children?: ReactNode;
}

export const ConfirmationAccepted = ({
	children,
}: ConfirmationAcceptedProps) => {
	const { approval, state } = useConfirmation();

	// Only show when approved and in response states
	if (
		!approval?.approved ||
		(state !== "approval-responded" &&
			state !== "output-denied" &&
			state !== "output-available")
	) {
		return null;
	}

	return (
		<span className="inline-flex items-center gap-2 text-success-text">
			{children}
		</span>
	);
};

export interface ConfirmationRejectedProps {
	children?: ReactNode;
}

export const ConfirmationRejected = ({
	children,
}: ConfirmationRejectedProps) => {
	const { approval, state } = useConfirmation();

	// Only show when rejected and in response states
	if (
		approval?.approved !== false ||
		(state !== "approval-responded" &&
			state !== "output-denied" &&
			state !== "output-available")
	) {
		return null;
	}

	return (
		<span className="inline-flex items-center gap-2 text-muted-foreground">
			{children}
		</span>
	);
};

export type ConfirmationActionsProps = ComponentProps<"div">;

export const ConfirmationActions = ({
	className,
	...props
}: ConfirmationActionsProps) => {
	const { state } = useConfirmation();

	// Only show when approval is requested
	if (state !== "approval-requested") {
		return null;
	}

	return (
		<div
			data-slot="ai-confirmation-actions"
			className={cn("col-start-2 mt-2.5 flex items-center gap-2", className)}
			{...props}
		/>
	);
};

export type ConfirmationActionProps = ComponentProps<typeof Button>;

export const ConfirmationAction = ({
	elevation,
	size = "sm",
	...props
}: ConfirmationActionProps) => {
	const ctx = useContext(ConfirmationContext);
	return (
		<Button
			data-slot="ai-confirmation-action"
			elevation={elevation ?? ctx?.elevation}
			size={size}
			type="button"
			{...props}
		/>
	);
};
