// packages/vue/registry/components/ai/shimmer/Shimmer.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { Component, CSSProperties, HTMLAttributes } from "vue"
import { motion } from "motion-v"
import { computed, useSlots } from "vue"
import { cn } from "@/registry/edmi/lib/utils"

export interface TextShimmerProps {
  as?: keyof HTMLElementTagNameMap
  class?: HTMLAttributes["class"]
  /** Seconds per sweep. */
  duration?: number
  /** Highlight width per character, in px. */
  spread?: number
}

const props = withDefaults(defineProps<TextShimmerProps>(), {
  as: "p",
  duration: 2,
  spread: 2,
})

const slots = useSlots()

const textContent = computed(() => {
  const defaultSlot = slots.default?.()
  if (!defaultSlot || defaultSlot.length === 0)
    return ""
  return defaultSlot
    .map(vnode => (typeof vnode.children === "string" ? vnode.children : ""))
    .join("")
})

const dynamicSpread = computed(() => (textContent.value?.length ?? 0) * props.spread)

// The sweep is a --foreground highlight over --muted-foreground text; the 0-alpha stops only shape the
// gradient inside the text clip (no surface is transparent, DESIGN §4.16).
const componentClasses = computed(() => cn(
  "relative inline-block bg-[length:250%_100%,auto] bg-clip-text text-transparent",
  "[--bg:linear-gradient(90deg,#0000_calc(50%-var(--spread)),var(--foreground),#0000_calc(50%+var(--spread)))] [background-repeat:no-repeat,padding-box]",
  props.class,
))

const componentStyle = computed((): CSSProperties => ({
  "--spread": `${dynamicSpread.value}px`,
  "backgroundImage": "var(--bg), linear-gradient(var(--muted-foreground), var(--muted-foreground))",
}))

const MotionComponent = computed(() => (motion[props.as as keyof typeof motion] || motion.p) as Component)
</script>

<template>
  <component
    :is="MotionComponent"
    data-slot="ai-shimmer"
    :class="componentClasses"
    :style="componentStyle"
    :initial="{ backgroundPosition: '100% center' }"
    :animate="{ backgroundPosition: '0% center' }"
    :transition="{
      repeat: Number.POSITIVE_INFINITY,
      duration,
      ease: 'linear',
    }"
  >
    <slot />
  </component>
</template>

// packages/react/registry/components/ai/shimmer.tsx
"use client";

import { cn } from "cn";
// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
import type { MotionProps } from "motion/react";
import { motion } from "motion/react";
import type { CSSProperties, ElementType, JSX } from "react";
import { memo, useMemo } from "react";

type MotionHTMLProps = MotionProps & Record<string, unknown>;

// Cache motion components at module level to avoid creating them during render.
const motionComponentCache = new Map<
	keyof JSX.IntrinsicElements,
	React.ComponentType<MotionHTMLProps>
>();

const getMotionComponent = (element: keyof JSX.IntrinsicElements) => {
	let component = motionComponentCache.get(element);
	if (!component) {
		component = motion.create(element);
		motionComponentCache.set(element, component);
	}
	return component;
};

export interface TextShimmerProps {
	children: string;
	as?: ElementType;
	className?: string;
	/** Seconds per sweep. */
	duration?: number;
	/** Highlight width per character, in px. */
	spread?: number;
}

// The sweep is a --foreground highlight over --muted-foreground text; the 0-alpha stops only shape the
// gradient inside the text clip (no surface is transparent, DESIGN §4.16).
const ShimmerComponent = ({
	children,
	as: Component = "p",
	className,
	duration = 2,
	spread = 2,
}: TextShimmerProps) => {
	const MotionComponent = getMotionComponent(
		Component as keyof JSX.IntrinsicElements,
	);

	const dynamicSpread = useMemo(
		() => (children?.length ?? 0) * spread,
		[children, spread],
	);

	return (
		<MotionComponent
			animate={{ backgroundPosition: "0% center" }}
			className={cn(
				"relative inline-block bg-[length:250%_100%,auto] bg-clip-text text-transparent",
				"[--bg:linear-gradient(90deg,#0000_calc(50%-var(--spread)),var(--foreground),#0000_calc(50%+var(--spread)))] [background-repeat:no-repeat,padding-box]",
				className,
			)}
			data-slot="ai-shimmer"
			initial={{ backgroundPosition: "100% center" }}
			style={
				{
					"--spread": `${dynamicSpread}px`,
					backgroundImage:
						"var(--bg), linear-gradient(var(--muted-foreground), var(--muted-foreground))",
				} as CSSProperties
			}
			transition={{
				duration,
				ease: "linear",
				repeat: Number.POSITIVE_INFINITY,
			}}
		>
			{children}
		</MotionComponent>
	);
};

export const Shimmer = memo(ShimmerComponent);
