// packages/svelte/src/lib/registry/ai/conversation/conversation-empty-state.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		class: className,
		title = "No messages yet",
		description = "Start a conversation to see messages here",
		icon,
		variant = "default",
		children,
		...restProps
	}: Omit<HTMLAttributes<HTMLDivElement>, "title"> & {
		title?: string;
		description?: string;
		icon?: Snippet;
		/**
		 * `default`: icon tile, title and description centered.
		 * `home` ✦: greeting heading and subtitle on the empty chat; put the composer and suggestions in `children`.
		 */
		variant?: "default" | "home";
		children?: Snippet;
	} = $props();
</script>

<div
	data-slot="ai-conversation-empty"
	data-variant={variant}
	class={cn(
		"flex size-full flex-col items-center justify-center gap-3 p-8 text-center",
		variant === "home" && "gap-6",
		className
	)}
	{...restProps}
>
	{#if variant === "home"}
		<div class="flex flex-col items-center gap-2">
			{#if icon}
				<div class="text-muted-foreground">{@render icon()}</div>
			{/if}
			<h2 class="text-[28px] leading-tight font-normal tracking-[-0.6px] text-foreground-2">
				{title}
			</h2>
			{#if description}
				<p class="text-[15px] text-muted-foreground">{description}</p>
			{/if}
		</div>
		{@render children?.()}
	{:else if children}
		{@render children()}
	{:else}
		{#if icon}
			<div
				data-slot="ai-conversation-empty-icon"
				class="flex size-12 items-center justify-center rounded-xl border border-border bg-card text-foreground [&_svg:not([class*='size-'])]:size-5"
			>
				{@render icon()}
			</div>
		{/if}
		<div class="space-y-1">
			<h3 class="text-sm font-semibold">{title}</h3>
			{#if description}
				<p class="text-[13px] text-muted-foreground">{description}</p>
			{/if}
		</div>
	{/if}
</div>

// packages/vue/registry/components/ai/conversation/ConversationEmptyState.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { cn } from "@/registry/edmi/lib/utils"

const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  title?: string
  description?: string
  /**
   * `default`: icon tile, title and description centered.
   * `home` ✦: greeting heading and subtitle on the empty chat; put the composer and suggestions in the default slot.
   */
  variant?: "default" | "home"
}>(), {
  title: "No messages yet",
  description: "Start a conversation to see messages here",
  variant: "default",
})
</script>

<template>
  <div
    data-slot="ai-conversation-empty"
    :data-variant="props.variant"
    :class="cn(
      'flex size-full flex-col items-center justify-center gap-3 p-8 text-center',
      props.variant === 'home' && 'gap-6',
      props.class,
    )"
  >
    <template v-if="props.variant === 'home'">
      <div class="flex flex-col items-center gap-2">
        <div v-if="$slots.icon" class="text-muted-foreground">
          <slot name="icon" />
        </div>
        <h2 class="text-[28px] leading-tight font-normal tracking-[-0.6px] text-foreground-2">
          {{ props.title }}
        </h2>
        <p v-if="props.description" class="text-[15px] text-muted-foreground">
          {{ props.description }}
        </p>
      </div>
      <slot />
    </template>
    <slot v-else>
      <div
        v-if="$slots.icon"
        data-slot="ai-conversation-empty-icon"
        class="flex size-12 items-center justify-center rounded-xl border border-border bg-card text-foreground [&_svg:not([class*='size-'])]:size-5"
      >
        <slot name="icon" />
      </div>
      <div class="space-y-1">
        <h3 class="text-sm font-semibold">
          {{ props.title }}
        </h3>
        <p v-if="props.description" class="text-[13px] text-muted-foreground">
          {{ props.description }}
        </p>
      </div>
    </slot>
  </div>
</template>
