// packages/svelte/src/lib/registry/ai/chain-of-thought/chain-of-thought.svelte
<!-- Derived from Svelte AI Elements (MIT), modified for Edmi UI. -->
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";
	import { setChainOfThoughtContext } from "./use-chain-of-thought.svelte.js";

	let {
		class: className,
		open = $bindable(),
		defaultOpen = false,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & { open?: boolean; defaultOpen?: boolean } = $props();

	// svelte-ignore state_referenced_locally
	if (open === undefined) open = defaultOpen;

	setChainOfThoughtContext({
		get isOpen() {
			return !!open;
		},
		setIsOpen: (value: boolean) => {
			open = value;
		},
	});
</script>

<div data-slot="ai-chain-of-thought" class={cn("not-prose w-full space-y-3", className)} {...restProps}>
	{@render children?.()}
</div>

// packages/vue/registry/components/ai/chain-of-thought/ChainOfThought.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { useVModel } from "@vueuse/core"
import { provide } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { ChainOfThoughtKey } from "./context"

const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  open?: boolean
  defaultOpen?: boolean
}>(), {
  open: undefined,
  defaultOpen: false,
})

const emit = defineEmits<{
  (e: "update:open", value: boolean): void
}>()

const isOpen = useVModel(props, "open", emit, {
  defaultValue: props.defaultOpen,
  passive: true,
})

provide(ChainOfThoughtKey, {
  isOpen,
  setIsOpen: (value: boolean) => {
    isOpen.value = value
  },
})
</script>

<template>
  <div data-slot="ai-chain-of-thought" :class="cn('not-prose w-full space-y-3', props.class)">
    <slot />
  </div>
</template>
