// examples/svelte/src/lib/components/ui/inset-panel/inset-panel.svelte
<script lang="ts">
	// ✦ Edmi addition (DESIGN §4.7): the header sits on the shell (--muted); the body is a
	// --card panel running edge to edge with radius on the top corners only; optional bottom
	// fade; the footer is back on the shell with a top border.
	import { cn, type WithElementRef } from "#lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		raised = false,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		/** ✦ opt-in one-step 3D look (hard lip + body highlight). */
		raised?: boolean;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="inset-panel"
	data-raised={raised ? "" : undefined}
	class={cn(
		"group/inset-panel flex flex-col overflow-hidden rounded-2xl border border-border bg-muted",
		raised && "border-b-lip-strong shadow-dialog",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/registry/ui/inset-panel/InsetPanel.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/registry/edmi/lib/utils'

const props = withDefaults(defineProps<{
  class?: HTMLAttributes['class']
  /** ✦ one-step 3D look: hard strong lip, body gets a top highlight */
  raised?: boolean
}>(), { raised: false })
</script>

<template>
  <div
    data-slot="inset-panel"
    :class="cn('group/inset-panel flex flex-col overflow-hidden rounded-2xl border border-border bg-muted', props.raised && 'border-b-lip-strong shadow-dialog [&_[data-slot=inset-panel-body]]:shadow-[inset_0_1px_0_var(--card-hi)]', props.class)"
  >
    <slot />
  </div>
</template>
