// apps/docs/src/demos/svelte/questionnaire-raised.svelte
<script lang="ts">
	import * as Questionnaire from "@edmi-svelte/ui/questionnaire";

	const items = [{ name: "rebalance", choices: [{ value: "drift" }, { value: "schedule" }, { value: "sign" }] }];

	function onsubmit(event: SubmitEvent) {
		event.preventDefault();
	}

	const levels = [
		{ value: "sunken", label: "Sunken (-1)" } as const,
		{ value: "flat", label: "Flat (0)" } as const,
		{ value: "raised", label: "Raised (+1)" } as const,
		{ value: "floating", label: "Floating (+2)" } as const,
	];
</script>

<div class="flex flex-col gap-6">
	{#each levels as l (l.value)}
		<div class="flex flex-col gap-2">
			<p class="text-xs font-medium text-muted-foreground">{l.label}</p>
<div class="grid w-full max-w-3xl gap-5 md:grid-cols-2">
		<Questionnaire.Root
			{items}
			elevation={l.value}
			shortcuts="letters"
			class="rounded-2xl border border-border bg-card p-5"
			{onsubmit}
		>
			<Questionnaire.Item name="rebalance" required>
				<Questionnaire.Title>How should the index rebalance?</Questionnaire.Title>
				<Questionnaire.Choices>
					<Questionnaire.Choice value="drift">On drift</Questionnaire.Choice>
					<Questionnaire.Choice value="schedule">On a schedule</Questionnaire.Choice>
					<Questionnaire.Choice value="sign">When I sign</Questionnaire.Choice>
				</Questionnaire.Choices>
				<Questionnaire.Input placeholder="Other…" />
			</Questionnaire.Item>
		</Questionnaire.Root>
</div>
		</div>
	{/each}
</div>

// apps/docs/src/demos/vue/questionnaire-raised.vue
<script setup lang="ts">
import {
  Questionnaire,
  QuestionnaireChoice,
  QuestionnaireChoices,
  QuestionnaireInput,
  QuestionnaireItem,
  QuestionnaireTitle,
} from "@edmi-vue/ui/questionnaire";

const levels = [
	{ value: "sunken", label: "Sunken (-1)" } as const,
	{ value: "flat", label: "Flat (0)" } as const,
	{ value: "raised", label: "Raised (+1)" } as const,
	{ value: "floating", label: "Floating (+2)" } as const,
];
</script>

<template>
	<div class="flex flex-col gap-6">
		<div v-for="l in levels" :key="l.value" class="flex flex-col gap-2">
			<p class="text-xs font-medium text-muted-foreground">{{ l.label }}</p>
  <Questionnaire :elevation="l.value" shortcuts="letters" class="w-full max-w-md rounded-2xl border border-border bg-card p-6">
    <QuestionnaireItem name="rebalance">
      <QuestionnaireTitle>How should the index rebalance?</QuestionnaireTitle>
      <QuestionnaireChoices>
        <QuestionnaireChoice value="drift">When any weight drifts past a limit</QuestionnaireChoice>
        <QuestionnaireChoice value="schedule">On a fixed schedule</QuestionnaireChoice>
      </QuestionnaireChoices>
      <QuestionnaireInput placeholder="Other…" />
    </QuestionnaireItem>
  </Questionnaire>
		</div>
	</div>
</template>
