// apps/docs/src/demos/svelte/questionnaire.svelte
<script lang="ts">
	import * as Questionnaire from "@edmi-svelte/ui/questionnaire";

	const items = [
		{ name: "rebalance", choices: [{ value: "drift" }, { value: "schedule" }, { value: "sign" }] },
		{ name: "notes" },
	];
	let done = $state<string | null>(null);

	function onsubmit(event: SubmitEvent) {
		event.preventDefault();
		const data = new FormData(event.currentTarget as HTMLFormElement);
		done = JSON.stringify(Object.fromEntries(data));
	}
</script>

<Questionnaire.Root
	{items}
	shortcuts="letters"
	class="w-full max-w-md rounded-2xl border border-border bg-card p-6"
	{onsubmit}
>
	<Questionnaire.Progress />
	<Questionnaire.Item name="rebalance" required>
		<Questionnaire.Title>How should the index rebalance?</Questionnaire.Title>
		<Questionnaire.Description>You can change this later in the mandate.</Questionnaire.Description>
		<Questionnaire.Choices>
			<Questionnaire.Choice value="drift">When any weight drifts past a limit</Questionnaire.Choice>
			<Questionnaire.Choice value="schedule">On a fixed schedule</Questionnaire.Choice>
			<Questionnaire.Choice value="sign">Only when I sign</Questionnaire.Choice>
		</Questionnaire.Choices>
		<Questionnaire.Input placeholder="Other…" />
	</Questionnaire.Item>
	<Questionnaire.Item name="notes">
		<Questionnaire.Title>Any notes for the desk?</Questionnaire.Title>
		<Questionnaire.Input placeholder="Add a note…" />
	</Questionnaire.Item>
	<Questionnaire.Actions>
		<Questionnaire.Previous />
		<Questionnaire.Skip />
		<Questionnaire.Next />
		<Questionnaire.Submit />
	</Questionnaire.Actions>
	{#if done}
		<p class="font-mono text-xs text-muted-foreground">{done}</p>
	{/if}
</Questionnaire.Root>

// apps/docs/src/demos/vue/questionnaire.vue
<script setup lang="ts">
import {
  Questionnaire,
  QuestionnaireActions,
  QuestionnaireChoice,
  QuestionnaireChoices,
  QuestionnaireDescription,
  QuestionnaireInput,
  QuestionnaireItem,
  QuestionnaireNext,
  QuestionnairePrevious,
  QuestionnaireProgress,
  QuestionnaireSkip,
  QuestionnaireSubmit,
  QuestionnaireTitle,
} from "@edmi-vue/ui/questionnaire";
import { ref } from "vue";

const items = [
  { name: "rebalance", choices: [{ value: "drift" }, { value: "schedule" }, { value: "sign" }] },
  { name: "notes" },
];
const done = ref<string | null>(null);

function onSubmit(event: Event) {
  event.preventDefault();
  const data = new FormData(event.currentTarget as HTMLFormElement);
  done.value = JSON.stringify(Object.fromEntries(data));
}
</script>

<template>
  <Questionnaire
    :items="items"
    shortcuts="letters"
    class="w-full max-w-md rounded-2xl border border-border bg-card p-6"
    @submit="onSubmit"
  >
    <QuestionnaireProgress />
    <QuestionnaireItem name="rebalance" required>
      <QuestionnaireTitle>How should the index rebalance?</QuestionnaireTitle>
      <QuestionnaireDescription>You can change this later in the mandate.</QuestionnaireDescription>
      <QuestionnaireChoices>
        <QuestionnaireChoice value="drift">When any weight drifts past a limit</QuestionnaireChoice>
        <QuestionnaireChoice value="schedule">On a fixed schedule</QuestionnaireChoice>
        <QuestionnaireChoice value="sign">Only when I sign</QuestionnaireChoice>
      </QuestionnaireChoices>
      <QuestionnaireInput placeholder="Other…" />
    </QuestionnaireItem>
    <QuestionnaireItem name="notes">
      <QuestionnaireTitle>Any notes for the desk?</QuestionnaireTitle>
      <QuestionnaireInput placeholder="Add a note…" />
    </QuestionnaireItem>
    <QuestionnaireActions>
      <QuestionnairePrevious />
      <QuestionnaireSkip />
      <QuestionnaireNext />
      <QuestionnaireSubmit />
    </QuestionnaireActions>
    <p v-if="done" class="font-mono text-xs text-muted-foreground">{{ done }}</p>
  </Questionnaire>
</template>
