// apps/docs/src/demos/vue/site-header-raised.vue
<script setup lang="ts">
import { SiteHeader } from "@edmi-vue/ui/site-header";
import { Button } from "@edmi-vue/ui/button";

const steps = [
	{ label: "Start", href: "#start" },
	{ label: "Build", href: "#build" },
	{ label: "Sell", href: "#sell" },
	{ label: "Scale", href: "#scale" },
];
const links = [
	{ label: "Resources", href: "#resources" },
	{ label: "Pricing", href: "#pricing" },
];
</script>

<template>
	<SiteHeader raised lead="How to" :steps="steps" :links="links">
		<template #action>
			<Button elevation="raised">Create an index</Button>
		</template>
	</SiteHeader>
</template>

// apps/docs/src/demos/svelte/site-header-raised.svelte
<script lang="ts">
	import { Button } from "@edmi-svelte/ui/button";
	import { SiteHeader } from "@edmi-svelte/ui/site-header";

	const steps = [
		{ label: "Start", href: "#start" },
		{ label: "Build", href: "#build" },
		{ label: "Sell", href: "#sell" },
		{ label: "Scale", href: "#scale" },
	];
	const links = [
		{ label: "Resources", href: "#resources" },
		{ label: "Pricing", href: "#pricing" },
	];
</script>

<SiteHeader raised lead="How to" {steps} {links}>
	{#snippet action({ raised })}
		<Button elevation={raised ? "raised" : undefined}>Create an index</Button>
	{/snippet}
</SiteHeader>
