// packages/svelte/src/lib/registry/ai/agent/agent.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { Card } from "$lib/registry/ui/card/index.js";
	import { cn } from "$lib/utils.js";
	import type { ComponentProps } from "svelte";

	// An agent's configuration at a glance. Built on the ui card; `raised` ✦ gives the one-step 3D look.
	let { class: className, raised = false, children, ...restProps }: ComponentProps<typeof Card> =
		$props();
</script>

<Card data-slot="ai-agent" {raised} class={cn("not-prose w-full gap-0 py-0", className)} {...restProps}>
	{@render children?.()}
</Card>

// packages/vue/registry/components/ai/agent/Agent.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Card } from "@/registry/edmi/ui/card"

// An agent's configuration at a glance. Built on the ui card; `raised` ✦ gives the one-step 3D look.
const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  raised?: boolean
}>(), {
  raised: false,
})
</script>

<template>
  <Card
    data-slot="ai-agent"
    :raised="props.raised"
    :class="cn('not-prose w-full gap-0 py-0', props.class)"
  >
    <slot />
  </Card>
</template>
