// packages/svelte/src/lib/registry/ai/plan/plan.svelte
<!-- Derived from Svelte AI Elements (MIT), modified for Edmi UI. -->
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import { Card } from "$lib/registry/ui/card/index.js";
	import { Collapsible } from "$lib/registry/ui/collapsible/index.js";
	import type { ComponentProps } from "svelte";
	import { setPlanContext } from "./use-plan.svelte.js";

	let {
		class: className,
		isStreaming = false,
		raised = false,
		open = $bindable(false),
		children,
		...restProps
	}: Omit<ComponentProps<typeof Collapsible>, "child"> & {
		isStreaming?: boolean;
		/** ✦ one-step 3D look on the card. */
		raised?: boolean;
	} = $props();

	setPlanContext({
		get isStreaming() {
			return isStreaming;
		},
	});
</script>

<Collapsible bind:open data-slot="ai-plan" {...restProps}>
	{#snippet child({ props })}
		<Card {...props} {raised} class={cn("gap-0 py-0 [--card-spacing:16px]", className)}>
			{@render children?.()}
		</Card>
	{/snippet}
</Collapsible>

// packages/vue/registry/components/ai/plan/Plan.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { CollapsibleRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { computed, provide } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Card } from "@/registry/edmi/ui/card"
import { Collapsible } from "@/registry/edmi/ui/collapsible"
import { PlanKey } from "./context"

interface PlanProps extends /* @vue-ignore */ CollapsibleRootProps {
  class?: HTMLAttributes["class"]
  isStreaming?: boolean
  /** ✦ one-step 3D look on the card. */
  raised?: boolean
}

const props = withDefaults(defineProps<PlanProps>(), {
  isStreaming: false,
  raised: false,
})

provide(PlanKey, { isStreaming: computed(() => props.isStreaming) })
</script>

<template>
  <!-- Collapsible props (open, defaultOpen, update:open) fall through as attrs. -->
  <Collapsible as-child data-slot="ai-plan">
    <Card
      :raised="props.raised"
      :class="cn('gap-0 py-0 [--card-spacing:16px]', props.class)"
    >
      <slot />
    </Card>
  </Collapsible>
</template>
