// packages/svelte/src/lib/registry/ai/context/context-content-footer.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { getUsage } from "tokenlens";
	import { formatUsd, useContextValue } from "./use-context.svelte.js";

	let {
		class: className,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & { children?: Snippet } = $props();

	const context = useContextValue();
	const totalCost = $derived.by(() => {
		const costUSD = context.modelId
			? getUsage({
					modelId: context.modelId,
					usage: {
						input: context.usage?.inputTokens ?? 0,
						output: context.usage?.outputTokens ?? 0,
					},
				}).costUSD?.totalUSD
			: undefined;
		return formatUsd(costUSD ?? 0);
	});
</script>

<div
	class={cn("flex w-full items-center justify-between gap-3 bg-muted p-3 text-xs", className)}
	{...restProps}
>
	{#if children}
		{@render children()}
	{:else}
		<span class="text-muted-foreground">Total cost</span>
		<span class="font-mono font-semibold">{totalCost}</span>
	{/if}
</div>

// packages/vue/registry/components/ai/context/ContextContentFooter.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { getUsage } from "tokenlens"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { formatUsd, useContextValue } from "./context"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const { modelId, usage } = useContextValue()

const totalCost = computed(() => {
  const costUSD = modelId.value
    ? getUsage({
        modelId: modelId.value,
        usage: {
          input: usage.value?.inputTokens ?? 0,
          output: usage.value?.outputTokens ?? 0,
        },
      }).costUSD?.totalUSD
    : undefined
  return formatUsd(costUSD ?? 0)
})
</script>

<template>
  <div :class="cn('flex w-full items-center justify-between gap-3 bg-muted p-3 text-xs', props.class)">
    <slot v-if="$slots.default" />
    <template v-else>
      <span class="text-muted-foreground">Total cost</span>
      <span class="font-mono font-semibold">{{ totalCost }}</span>
    </template>
  </div>
</template>
