// packages/svelte/src/lib/registry/ai/context/context-content-header.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { Progress } from "$lib/registry/ui/progress/index.js";
	import { cn } from "$lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { formatCompact, formatPercent, useContextValue } from "./use-context.svelte.js";

	let {
		class: className,
		children,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & { children?: Snippet } = $props();

	const PERCENT_MAX = 100;
	const context = useContextValue();
	const usedPercent = $derived(
		context.maxTokens === 0 ? 0 : context.usedTokens / context.maxTokens
	);
</script>

<div class={cn("w-full space-y-2 p-3", className)} {...restProps}>
	{#if children}
		{@render children()}
	{:else}
		<div class="flex items-center justify-between gap-3 text-xs">
			<p class="font-semibold">{formatPercent(usedPercent)}</p>
			<p class="font-mono text-muted-foreground">
				{formatCompact(context.usedTokens)} / {formatCompact(context.maxTokens)}
			</p>
		</div>
		<div class="space-y-2">
			<Progress variant="brand" value={usedPercent * PERCENT_MAX} />
		</div>
	{/if}
</div>

// packages/vue/registry/components/ai/context/ContextContentHeader.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { HTMLAttributes } from "vue"
import { computed } from "vue"
import { cn } from "@/registry/edmi/lib/utils"
import { Progress } from "@/registry/edmi/ui/progress"
import { formatCompact, formatPercent, useContextValue } from "./context"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const PERCENT_MAX = 100
const { usedTokens, maxTokens } = useContextValue()

const usedPercent = computed(() => (maxTokens.value === 0 ? 0 : usedTokens.value / maxTokens.value))
const displayPct = computed(() => formatPercent(usedPercent.value))
const used = computed(() => formatCompact(usedTokens.value))
const total = computed(() => formatCompact(maxTokens.value))
</script>

<template>
  <div :class="cn('w-full space-y-2 p-3', props.class)">
    <slot v-if="$slots.default" />
    <template v-else>
      <div class="flex items-center justify-between gap-3 text-xs">
        <p class="font-semibold">
          {{ displayPct }}
        </p>
        <p class="font-mono text-muted-foreground">
          {{ used }} / {{ total }}
        </p>
      </div>
      <div class="space-y-2">
        <Progress variant="brand" :model-value="usedPercent * PERCENT_MAX" />
      </div>
    </template>
  </div>
</template>
