// packages/svelte/src/lib/registry/ai/context/context.svelte
<script lang="ts">
	// Derived from Vercel AI Elements (Apache-2.0), modified for Edmi UI.
	import { HoverCard } from "$lib/registry/ui/hover-card/index.js";
	import type { LanguageModelUsage } from "ai";
	import type { ComponentProps } from "svelte";
	import { type ModelId, setContextValue } from "./use-context.svelte.js";

	let {
		usedTokens,
		maxTokens,
		usage,
		modelId,
		open = $bindable(false),
		openDelay = 0,
		closeDelay = 0,
		children,
		...restProps
	}: ComponentProps<typeof HoverCard> & {
		usedTokens: number;
		maxTokens: number;
		usage?: LanguageModelUsage;
		modelId?: ModelId;
	} = $props();

	setContextValue({
		get usedTokens() {
			return usedTokens;
		},
		get maxTokens() {
			return maxTokens;
		},
		get usage() {
			return usage;
		},
		get modelId() {
			return modelId;
		},
	});
</script>

<HoverCard bind:open {openDelay} {closeDelay} {...restProps}>
	{@render children?.()}
</HoverCard>

// packages/vue/registry/components/ai/context/Context.vue
<script setup lang="ts">
// Derived from AI Elements Vue (Apache-2.0), modified for Edmi UI.
import type { LanguageModelUsage } from "ai"
import type { HoverCardRootProps } from "reka-ui"
import type { ModelId } from "./context"
import { computed, provide } from "vue"
import { HoverCard } from "@/registry/edmi/ui/hover-card"
import { ContextKey } from "./context"

interface ContextProps extends /* @vue-ignore */ HoverCardRootProps {
  usedTokens: number
  maxTokens: number
  usage?: LanguageModelUsage
  modelId?: ModelId
}

const props = defineProps<ContextProps>()

provide(ContextKey, {
  usedTokens: computed(() => props.usedTokens),
  maxTokens: computed(() => props.maxTokens),
  usage: computed(() => props.usage),
  modelId: computed(() => props.modelId),
})
</script>

<template>
  <!-- HoverCard props (open, delays) fall through as attrs and win over the 0 defaults. -->
  <HoverCard :open-delay="0" :close-delay="0">
    <slot />
  </HoverCard>
</template>
