// examples/svelte/src/lib/components/ui/questionnaire/questionnaire.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "#lib/utils.js";
	import type { HTMLFormAttributes } from "svelte/elements";
	import { onMount, untrack, type Snippet } from "svelte";
	import type { Elevation } from "#lib/components/ui/elevation/index.js";
	import {
		type ItemRegistration,
		type QuestionnaireItemDefinition,
		type QuestionnaireItemStatus,
		type QuestionnaireShortcutMode,
		compareDocumentOrder,
		createQuestionnaireCollection,
		getInitialItemName,
		getShortcutFromKey,
		isAnswerFilled,
		isRadioTarget,
		isTextEntryTarget,
		setQuestionnaireRootContext,
	} from "./use-questionnaire.svelte.js";

	let {
		ref = $bindable(null),
		class: className,
		/** Item shown first. Ignored when `item` is provided. */
		defaultItem = undefined,
		/** Active item. Use with `bind:item`. */
		item = $bindable(undefined),
		/** Declares the item order, and the choice order shortcuts are assigned in. */
		items = undefined,
		/** Set to `false` to run native constraint validation on answered items. */
		noValidate = true,
		/** Assigns a keyboard shortcut to every choice. */
		shortcuts = undefined,
		/** ✦ depth of every option and input: sunken -1, flat 0, raised +1, floating +2. */
		elevation = "auto",
		onItemChange = undefined,
		onsubmit,
		onreset,
		children,
		...restProps
	}: Omit<WithElementRef<HTMLFormAttributes, HTMLFormElement>, "children" | "onsubmit" | "onreset"> & {
		defaultItem?: string;
		item?: string;
		items?: readonly QuestionnaireItemDefinition[];
		noValidate?: boolean;
		shortcuts?: QuestionnaireShortcutMode;
		elevation?: Elevation;
		onItemChange?: (item: string) => void;
		onsubmit?: (event: SubmitEvent) => void;
		onreset?: (event: Event) => void;
		children?: Snippet<[{ current: number; first: boolean; last: boolean; total: number }]>;
	} = $props();

	interface PendingFocus {
		name: string;
		target: "invalid" | "item";
	}

	let registrations = $state.raw<ItemRegistration[]>([]);
	let domVersion = $state(0);
	let pendingFocus: PendingFocus | null = null;

	const collection = $derived(createQuestionnaireCollection(items));
	let uncontrolledItem = $state<string | null>(
		untrack(() => getInitialItemName(createQuestionnaireCollection(items), defaultItem))
	);
	const activeItemName = $derived(item !== undefined ? item : uncontrolledItem);
	const resolvedShortcuts = $derived(shortcuts ?? null);

	const runtimeItems = $derived.by(() => {
		// Re-sort whenever items are added to or removed from the DOM.
		void domVersion;
		return registrations
			.filter((registration) => !registration.isDisabled())
			.sort((first, second) => compareDocumentOrder(first.element, second.element));
	});
	const runtimeItemByName = $derived(new Map(runtimeItems.map((r) => [r.name, r])));
	/** `items` is authoritative when provided, so items can be declared before they render. */
	const logicalItems = $derived<readonly { name: string }[]>(
		collection?.enabledItems ?? runtimeItems
	);
	const currentIndex = $derived(logicalItems.findIndex((l) => l.name === activeItemName));
	const activeItem = $derived(
		currentIndex < 0 || !activeItemName ? null : (runtimeItemByName.get(activeItemName) ?? null)
	);
	const activeDefinition = $derived(
		activeItemName ? collection?.itemByName.get(activeItemName) : undefined
	);
	const activeItemRequired = $derived.by(() => {
		if (currentIndex < 0) return null;
		return activeDefinition
			? Boolean(activeDefinition.required)
			: (activeItem?.isRequired() ?? false);
	});
	const activeItemStatus = $derived.by<QuestionnaireItemStatus | null>(() => {
		if (currentIndex < 0) return null;
		return activeItem?.status() ?? (activeItemName ? "unanswered" : null);
	});
	const orderedRegistrations = $derived.by(() => {
		if (!collection) return runtimeItems;
		return collection.enabledItems.flatMap((definition) => {
			const registration = runtimeItemByName.get(definition.name);
			return registration ? [registration] : [];
		});
	});
	const total = $derived(logicalItems.length);
	const current = $derived(currentIndex < 0 ? 0 : currentIndex + 1);
	const first = $derived(total > 0 && currentIndex === 0);
	const last = $derived(total > 0 && currentIndex === total - 1);

	function setItem(nextItem: string, focusTarget: PendingFocus["target"] = "item") {
		if (nextItem === activeItemName) return;
		pendingFocus = { name: nextItem, target: focusTarget };
		uncontrolledItem = nextItem;
		item = nextItem;
		onItemChange?.(nextItem);
	}

	function registerItem(registration: ItemRegistration) {
		registrations = untrack(() => [
			...registrations.filter(
				(r) => r.element !== registration.element && r.name !== registration.name
			),
			registration,
		]);
		return () => {
			registrations = registrations.filter((r) => r !== registration);
		};
	}

	function setItemAt(index: number, focusTarget: PendingFocus["target"] = "item") {
		const nextItem = logicalItems[index];
		if (nextItem) setItem(nextItem.name, focusTarget);
	}

	function goPrevious() {
		if (currentIndex <= 0) return;
		setItemAt(currentIndex - 1);
	}

	function goNext() {
		if (!activeItem || currentIndex >= total - 1) return;
		if (!activeItem.validate()) {
			activeItem.focusInvalid();
			return;
		}
		setItemAt(currentIndex + 1);
	}

	function confirmCurrent() {
		if (!activeItem) return;
		if (!activeItem.validate()) {
			activeItem.focusInvalid();
			return;
		}
		if (last) {
			ref?.requestSubmit();
			return;
		}
		setItemAt(currentIndex + 1);
	}

	function skipCurrent() {
		if (!activeItem || activeItem.isRequired()) return;
		activeItem.skip();
		if (!last) {
			setItemAt(currentIndex + 1);
			return;
		}
		queueMicrotask(() => ref?.requestSubmit());
	}

	function handleReset(event: Event) {
		onreset?.(event);
		if (event.defaultPrevented) return;
		for (const registration of registrations) registration.reset();
		const resetItemName = collection
			? getInitialItemName(collection, defaultItem)
			: (runtimeItems.find((r) => r.name === defaultItem)?.name ?? runtimeItems[0]?.name);
		if (resetItemName) setItem(resetItemName);
	}

	function handleSubmit(event: SubmitEvent) {
		const firstInvalidItem = orderedRegistrations.find((r) => !r.validate());
		if (firstInvalidItem) {
			event.preventDefault();
			setItem(firstInvalidItem.name, "invalid");
			if (firstInvalidItem.name === activeItemName) {
				firstInvalidItem.focusInvalid();
				pendingFocus = null;
			}
			return;
		}
		onsubmit?.(event);
	}

	function handleKeydown(event: KeyboardEvent) {
		if (
			event.defaultPrevented ||
			event.isComposing ||
			event.keyCode === 229 ||
			!activeItem ||
			!(event.target instanceof Element)
		) {
			return;
		}

		if (event.key === "Enter" && (event.metaKey || event.ctrlKey) && !event.altKey && !event.shiftKey) {
			event.preventDefault();
			if (!event.repeat) confirmCurrent();
			return;
		}

		if (event.metaKey || event.ctrlKey || event.altKey) return;

		if (event.key === "ArrowUp" || event.key === "ArrowDown") {
			const moved = activeItem.moveAnswerFocus(
				event.target,
				event.key === "ArrowDown" ? "next" : "previous"
			);
			if (moved) {
				event.preventDefault();
				return;
			}
		}

		if (
			(event.key === "ArrowLeft" || event.key === "ArrowRight") &&
			!isTextEntryTarget(event.target) &&
			!isRadioTarget(event.target)
		) {
			event.preventDefault();
			if (event.repeat) return;
			if (event.key === "ArrowLeft") goPrevious();
			else if (activeItem.status() !== "unanswered") goNext();
			return;
		}

		if (event.key === "Enter") {
			const answer = activeItem.getAnswerByElement(event.target);
			if (!answer) return;
			event.preventDefault();
			if (!event.repeat && isAnswerFilled(answer)) confirmCurrent();
			return;
		}

		if (!resolvedShortcuts || isTextEntryTarget(event.target)) return;

		const shortcut = getShortcutFromKey(event.key, resolvedShortcuts);
		const answer = shortcut ? activeItem.getAnswerByShortcut(shortcut) : null;
		if (!answer) return;

		event.preventDefault();
		if (event.repeat) return;
		answer.element.focus();
		if (answer.type === "choice") answer.element.click();
	}

	let previousActiveItemName: string | null = untrack(() => activeItemName);
	$effect(() => {
		const name = activeItemName;
		const index = currentIndex;
		const count = total;
		const registration = activeItem;
		if (count === 0) return;

		if (index < 0) {
			const firstItem = logicalItems[0];
			if (!firstItem) return;
			if (item === undefined && name === null) {
				uncontrolledItem = firstItem.name;
				return;
			}
			setItem(firstItem.name);
			return;
		}

		const focus = pendingFocus;
		const activeItemChanged = previousActiveItemName !== name;
		previousActiveItemName = name;

		if (!focus || focus.name !== name) {
			if (item !== undefined && activeItemChanged) {
				pendingFocus = null;
				registration?.focus();
			}
			return;
		}

		if (focus.target === "invalid") registration?.focusInvalid();
		else registration?.focus();
		pendingFocus = null;
	});

	onMount(() => {
		if (!ref || typeof MutationObserver === "undefined") return;
		const observer = new MutationObserver(() => {
			domVersion += 1;
		});
		observer.observe(ref, { childList: true, subtree: true });
		return () => observer.disconnect();
	});

	setQuestionnaireRootContext({
		get elevation() {
			return elevation === "auto" ? undefined : elevation;
		},
		get activeItem() {
			return activeItem;
		},
		get activeItemName() {
			return activeItemName;
		},
		get activeItemRequired() {
			return activeItemRequired;
		},
		get activeItemStatus() {
			return activeItemStatus;
		},
		get current() {
			return current;
		},
		get domVersion() {
			return domVersion;
		},
		get first() {
			return first;
		},
		get itemDefinitionByName() {
			return collection?.itemByName ?? null;
		},
		get last() {
			return last;
		},
		get nativeValidation() {
			return noValidate === false;
		},
		get shortcuts() {
			return resolvedShortcuts;
		},
		get total() {
			return total;
		},
		goNext,
		goPrevious,
		registerItem,
		skipCurrent,
	});
</script>

<form
	bind:this={ref}
	data-slot="questionnaire"
	data-shortcuts={resolvedShortcuts ?? undefined}
	novalidate={noValidate}
	class={cn("flex w-full min-w-0 flex-col gap-4", className)}
	onkeydown={handleKeydown}
	onreset={handleReset}
	onsubmit={handleSubmit}
	{...restProps}
>
	{@render children?.({ current, first, last, total })}
</form>

// examples/vue/src/components/ui/questionnaire/Questionnaire.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type {
  ItemRegistration,
  QuestionnaireItemDefinition,
  QuestionnaireShortcutMode,
} from "./useQuestionnaire"
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watch } from "vue"
import { cn } from '@/lib/utils'
import type { Elevation } from '@/components/ui/elevation'
import {
  compareDocumentOrder,
  createQuestionnaireCollection,
  getInitialItemName,
  getShortcutFromKey,
  isAnswerFilled,
  isRadioTarget,
  isTextEntryTarget,
  provideQuestionnaireRootContext,
} from "./useQuestionnaire"

const props = withDefaults(defineProps<{
  class?: HTMLAttributes["class"]
  /** Item shown first. Ignored when `item` is provided. */
  defaultItem?: string
  /** Controlled active item. Use with `v-model:item`. */
  item?: string
  /** Declares the item order, and the choice order shortcuts are assigned in. */
  items?: readonly QuestionnaireItemDefinition[]
  /** Set to `false` to run native constraint validation on answered items. */
  noValidate?: boolean
  /** ✦ depth of every choice and input: sunken -1, flat 0, raised +1, floating +2 */
  elevation?: Elevation
  /** Assigns a keyboard shortcut to every choice. */
  shortcuts?: QuestionnaireShortcutMode
}>(), {
  noValidate: true,
  elevation: undefined,
})

const emits = defineEmits<{
  "reset": [event: Event]
  "submit": [event: Event]
  "update:item": [item: string]
}>()

interface PendingFocus {
  name: string
  target: "invalid" | "item"
}

const rootElement = ref<HTMLFormElement | null>(null)
const registrations = shallowRef<ItemRegistration[]>([])
const domVersion = ref(0)
const pendingFocus = shallowRef<PendingFocus | null>(null)

const collection = computed(() => createQuestionnaireCollection(props.items))
const uncontrolledItem = ref<string | null>(
  getInitialItemName(collection.value, props.defaultItem),
)
const controlled = computed(() => props.item !== undefined)
const activeItemName = computed(() => (controlled.value ? props.item! : uncontrolledItem.value))
const shortcuts = computed(() => props.shortcuts ?? null)
const nativeValidation = computed(() => props.noValidate === false)

let previousActiveItemName = activeItemName.value

const runtimeItems = computed(() => {
  // Re-sort whenever items are added to or removed from the DOM.
  void domVersion.value

  return registrations.value
    .filter(registration => !registration.isDisabled())
    .sort((first, second) => compareDocumentOrder(first.element, second.element))
})
const runtimeItemByName = computed(
  () => new Map(runtimeItems.value.map(runtimeItem => [runtimeItem.name, runtimeItem])),
)
/** `items` is authoritative when provided, so items can be declared before they render. */
const logicalItems = computed<readonly { name: string }[]>(
  () => collection.value?.enabledItems ?? runtimeItems.value,
)
const currentIndex = computed(
  () => logicalItems.value.findIndex(logicalItem => logicalItem.name === activeItemName.value),
)
const activeItem = computed(() => {
  if (currentIndex.value < 0 || !activeItemName.value) {
    return null
  }

  return runtimeItemByName.value.get(activeItemName.value) ?? null
})
const activeDefinition = computed(() =>
  activeItemName.value ? collection.value?.itemByName.get(activeItemName.value) : undefined,
)
const activeItemRequired = computed(() => {
  if (currentIndex.value < 0) {
    return null
  }

  return activeDefinition.value
    ? Boolean(activeDefinition.value.required)
    : (activeItem.value?.isRequired() ?? false)
})
const activeItemStatus = computed(() => {
  if (currentIndex.value < 0) {
    return null
  }

  return activeItem.value?.status() ?? (activeItemName.value ? "unanswered" : null)
})
const orderedRegistrations = computed(() => {
  if (!collection.value) {
    return runtimeItems.value
  }

  return collection.value.enabledItems.flatMap((definition) => {
    const registration = runtimeItemByName.value.get(definition.name)

    return registration ? [registration] : []
  })
})
const total = computed(() => logicalItems.value.length)
const current = computed(() => (currentIndex.value < 0 ? 0 : currentIndex.value + 1))
const first = computed(() => total.value > 0 && currentIndex.value === 0)
const last = computed(() => total.value > 0 && currentIndex.value === total.value - 1)

function setItem(nextItem: string, focusTarget: PendingFocus["target"] = "item") {
  if (nextItem === activeItemName.value) {
    return
  }

  pendingFocus.value = { name: nextItem, target: focusTarget }

  if (!controlled.value) {
    uncontrolledItem.value = nextItem
  }

  emits("update:item", nextItem)
}

function registerItem(registration: ItemRegistration) {
  registrations.value = [
    ...registrations.value.filter(
      current => current.element !== registration.element && current.name !== registration.name,
    ),
    registration,
  ]

  return () => {
    registrations.value = registrations.value.filter(current => current !== registration)
  }
}

function setItemAt(index: number, focusTarget: PendingFocus["target"] = "item") {
  const nextItem = logicalItems.value[index]

  if (nextItem) {
    setItem(nextItem.name, focusTarget)
  }
}

function goPrevious() {
  if (currentIndex.value <= 0) {
    return
  }

  setItemAt(currentIndex.value - 1)
}

function goNext() {
  if (!activeItem.value || currentIndex.value >= total.value - 1) {
    return
  }

  if (!activeItem.value.validate()) {
    activeItem.value.focusInvalid()
    return
  }

  setItemAt(currentIndex.value + 1)
}

function confirmCurrent() {
  if (!activeItem.value) {
    return
  }

  if (!activeItem.value.validate()) {
    activeItem.value.focusInvalid()
    return
  }

  if (last.value) {
    rootElement.value?.requestSubmit()
    return
  }

  setItemAt(currentIndex.value + 1)
}

function skipCurrent() {
  if (!activeItem.value || activeItem.value.isRequired()) {
    return
  }

  activeItem.value.skip()

  if (!last.value) {
    setItemAt(currentIndex.value + 1)
    return
  }

  queueMicrotask(() => {
    rootElement.value?.requestSubmit()
  })
}

function handleReset(event: Event) {
  emits("reset", event)

  if (event.defaultPrevented) {
    return
  }

  for (const registration of registrations.value) {
    registration.reset()
  }

  const resetItemName = collection.value
    ? getInitialItemName(collection.value, props.defaultItem)
    : (runtimeItems.value.find(registration => registration.name === props.defaultItem)?.name
      ?? runtimeItems.value[0]?.name)

  if (resetItemName) {
    setItem(resetItemName)
  }
}

function handleSubmit(event: Event) {
  const firstInvalidItem = orderedRegistrations.value.find(registration => !registration.validate())

  if (firstInvalidItem) {
    event.preventDefault()
    setItem(firstInvalidItem.name, "invalid")

    if (firstInvalidItem.name === activeItemName.value) {
      firstInvalidItem.focusInvalid()
      pendingFocus.value = null
    }

    return
  }

  emits("submit", event)
}

function handleKeydown(event: KeyboardEvent) {
  if (
    event.defaultPrevented
    || event.isComposing
    || event.keyCode === 229
    || !activeItem.value
    || !(event.target instanceof Element)
  ) {
    return
  }

  if (event.key === "Enter" && (event.metaKey || event.ctrlKey) && !event.altKey && !event.shiftKey) {
    event.preventDefault()

    if (!event.repeat) {
      confirmCurrent()
    }

    return
  }

  if (event.metaKey || event.ctrlKey || event.altKey) {
    return
  }

  if (event.key === "ArrowUp" || event.key === "ArrowDown") {
    const moved = activeItem.value.moveAnswerFocus(
      event.target,
      event.key === "ArrowDown" ? "next" : "previous",
    )

    if (moved) {
      event.preventDefault()
      return
    }
  }

  if (
    (event.key === "ArrowLeft" || event.key === "ArrowRight")
    && !isTextEntryTarget(event.target)
    && !isRadioTarget(event.target)
  ) {
    event.preventDefault()

    if (event.repeat) {
      return
    }

    if (event.key === "ArrowLeft") {
      goPrevious()
    }
    else if (activeItem.value.status() !== "unanswered") {
      goNext()
    }

    return
  }

  if (event.key === "Enter") {
    const answer = activeItem.value.getAnswerByElement(event.target)

    if (!answer) {
      return
    }

    event.preventDefault()

    if (!event.repeat && isAnswerFilled(answer)) {
      confirmCurrent()
    }

    return
  }

  if (!shortcuts.value || isTextEntryTarget(event.target)) {
    return
  }

  const shortcut = getShortcutFromKey(event.key, shortcuts.value)
  const answer = shortcut ? activeItem.value.getAnswerByShortcut(shortcut) : null

  if (!answer) {
    return
  }

  event.preventDefault()

  if (event.repeat) {
    return
  }

  answer.element.focus()

  if (answer.type === "choice") {
    answer.element.click()
  }
}

watch(
  () => [activeItemName.value, currentIndex.value, total.value, activeItem.value] as const,
  () => {
    if (total.value === 0) {
      return
    }

    if (currentIndex.value < 0) {
      const firstItem = logicalItems.value[0]

      if (!firstItem) {
        return
      }

      if (!controlled.value && activeItemName.value === null) {
        uncontrolledItem.value = firstItem.name
        return
      }

      setItem(firstItem.name)
      return
    }

    const focus = pendingFocus.value
    const activeItemChanged = previousActiveItemName !== activeItemName.value

    previousActiveItemName = activeItemName.value

    if (!focus || focus.name !== activeItemName.value) {
      if (controlled.value && activeItemChanged) {
        pendingFocus.value = null
        activeItem.value?.focus()
      }

      return
    }

    if (focus.target === "invalid") {
      activeItem.value?.focusInvalid()
    }
    else {
      activeItem.value?.focus()
    }

    pendingFocus.value = null
  },
  { flush: "post", immediate: true },
)

let observer: MutationObserver | null = null

onMounted(() => {
  if (!rootElement.value || typeof MutationObserver === "undefined") {
    return
  }

  observer = new MutationObserver(() => {
    domVersion.value += 1
  })

  observer.observe(rootElement.value, { childList: true, subtree: true })
})

onBeforeUnmount(() => {
  observer?.disconnect()
  observer = null
})

provideQuestionnaireRootContext({
  activeItem,
  activeItemName,
  activeItemRequired,
  activeItemStatus,
  current,
  domVersion,
  first,
  goNext,
  goPrevious,
  itemDefinitionByName: computed(() => collection.value?.itemByName ?? null),
  last,
  nativeValidation,
  elevation: computed(() => props.elevation),
  registerItem,
  shortcuts,
  skipCurrent,
  total,
})
</script>

<template>
  <form
    ref="rootElement"
    data-slot="questionnaire"
    :data-shortcuts="shortcuts ?? undefined"
    :novalidate="props.noValidate"
    :class="cn('flex w-full min-w-0 flex-col gap-4', props.class)"
    @keydown="handleKeydown"
    @reset="handleReset"
    @submit="handleSubmit"
  >
    <slot :current="current" :first="first" :last="last" :total="total" />
  </form>
</template>
